---
title: "Regression for Describing"
date: "2023-03-21"
---


This session will be primarily devoted to mechanics of line-fitting in OLS with a bivariate regression and the idea of statistical control in a multiple regression. Next week will be devoted to uncertainty estimates (i.e. the standard errors, confidence intervals, and p-values). 

## Required readings

- {{< fa book >}} [Sections 4.4-4.5 in *The Effect*](https://theeffectbook.net/ch-DescribingRelationships.html) [@Huntington-Klein:2021]

- {{< fa book >}} [Chapter 13 in *The Effect*](https://theeffectbook.net/ch-StatisticalAdjustment.html) [@Huntington-Klein:2021]



### Guiding questions:

- How is the regression line created? What is an error term? 
- How are explained and residual variance related to the concept of regression line?
- How do we interpret the coefficients of regression variables? 
- What does it mean that we control for a variable, mechanically?  
- What are the assumptions that regression requires? How do we test them? 
- What are the limitations of OLS?


