project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl
description-meta: "Use modern statistical and data scientific tools to measure causal effects"

website:
  title: "Data Analytics and Visualization with R"
  site-url: "https://r4da.live"

  favicon: "/files/icon-512.png"


  open-graph:
    image: "/files/img/sticker.png"
    locale: en_US

  navbar:
    pinned: true
    background: "#800010"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Prepare"
        file: prepare/index.qmd
      - text: "Sessions"
        file: session/index.qmd
      - text: "Assignments"
        file: assignment/index.qmd
      - text: "Resources"
        file: resource/index.qmd
      - icon: github
        href: "https://github.com/r4da-s23"
        aria-label: GitHub
      - icon: cloud-fill
        href: "https://rstudio.cloud"
        aria-label: RStudio.cloud

  sidebar:
    - title: "Prepare"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - prepare/index.qmd
        - section: "Course content"
          contents:
            - text: "1: Meet the Toolkit"
              file: prepare/01-prepare.qmd
            - text: "2: Describing Variables"
              file: prepare/02-prepare.qmd
            - text: "3: Describing Relationships"
              file: prepare/03-prepare.qmd
            - text: "4: Identification and Causal Diagrams"
              file: prepare/04-prepare.qmd
            - text: "5: Causal Diagrams and Treatment Effects"
              file: prepare/05-prepare.qmd
            # - text: "6: Regression for Describing"
            #   file: prepare/06-prepare.qmd
            # - text: "7: Uncertainty and Statistical Inference"
            #   file: prepare/07-prepare.qmd
            # - text: "8: Estimating Heterogeneous Effects"
            #   file: prepare/08-prepare.qmd
            # - text: "9: Binary Dependent Variable"
            #   file: prepare/09-prepare.qmd
            # - text: "10: Matching"
            #   file: prepare/10-prepare.qmd
            # - text: "11: Fixed Effects"
            #   file: prepare/11-prepare.qmd
            # - text: "12: Difference-in-Differences"
            #   file: prepare/12-prepare.qmd
            # - text: "13: Regression Discontinuity"
            #   file: prepare/13-prepare.qmd
            # - text: "14: Review"
            #   file: prepare/14-prepare.qmd

    - title: "Sessions"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - session/index.qmd
        - section: "Course content"
          contents:
            - text: "1: Meet the Toolkit"
              file: session/01-session.qmd
            - text: "2: Describing Variables"
              file: session/02-session.qmd
            - text: "3: Describing Relationships"
              file: session/03-session.qmd
            - text: "4: Identification and Causal Diagrams"
              file: session/04-session.qmd
            - text: "5: Causal Diagrams and Treatment Effects"
              file: session/05-session.qmd
            # - text: "6: Regression for Describing"
            #   file: session/06-session.qmd
            # - text: "7: Uncertainty and Statistical Inference"
            #   file: session/07-session.qmd
            # - text: "8: Estimating Heterogeneous Effects"
            #   file: session/08-session.qmd
            # - text: "9: Binary Dependent Variable"
            #   file: session/09-session.qmd
            # - text: "10: Matching"
            #   file: session/10-session.qmd
            # - text: "11: Fixed Effects"
            #   file: session/11-session.qmd
            # - text: "12: Difference-in-Differences"
            #   file: session/12-session.qmd
            # - text: "13: Regression Discontinuity"
            #   file: session/13-session.qmd
            # - text: "14: Review"
            #   file: session/14-session.qmd

    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Final Project"
          contents:
            - assignment/final-project.qmd
        - section: "Problem sets"
          contents:
            - assignment/01-problem-set.qmd
            - assignment/02-problem-set.qmd
            - assignment/03-problem-set.qmd
            - assignment/04-problem-set.qmd
            # - assignment/05-problem-set.qmd
            # - assignment/06-problem-set.qmd
            # - assignment/07-problem-set.qmd
            # - assignment/08-problem-set.qmd
            # - assignment/09-problem-set.qmd
            # - assignment/10-problem-set.qmd
            # - assignment/11-problem-set.qmd
            # - assignment/12-problem-set.qmd
            # - assignment/13-problem-set.qmd
        - section: "Optional"
          contents:
            - assignment/presentation.qmd

    - title: "Resources"
      contents:
        - section: "Overview"
          contents:
            - resource/index.qmd
            - resource/r.qmd
            - resource/style.qmd
            # - resource/data.qmd
            # - resource/citations.qmd
        - section: "Guides"
          contents:
            - resource/install.qmd
            - resource/markdown.qmd
            - resource/rmarkdown.qmd
            # - resource/unzipping.qmd
            - resource/errors.qmd
            - resource/giterrors.qmd



  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa solid heart >}},  [{{< fa brands github >}}](https://github.com/), [{{< fa brands r-project >}}](https://posit.co/) and [Quarto](https://quarto.org/).

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: github
