{
  "hash": "ff735e658e80208073f3b9f9d2a0e23f",
  "result": {
    "markdown": "---\ntitle: \"Regression for Describing\"\nsubtitle: \"Data Analytics and Visualization with R<br>Session 6\"\ntitle-slide-attributes:\n  data-background-size: stretch\n  data-slide-number: none\nauto-stretch: false\ninstitute: \"University of Mannheim<br>Spring 2023\"\nauthor: \"Viktoriia Semenova\"\nfooter: \"[🔗 r4da.live](https://r4da.live/)\"\nlogo: images/logo.png\nformat:\n  revealjs:\n    theme: ../slides.scss\n    transition: fade\n    incremental: true   \n    slide-number: true\n    chalkboard: true\nexecute:\n  echo: true\neditor_options: \n  chunk_output_type: console\neditor: \n  markdown: \n    wrap: 80\n---\n\n\n\n\n# Intro\n\n\n## Agenda for Today\n\n<br>\n\n**Fitting the line with OLS**\n\n<br>\n\n**Interpretation of Regression Coefficients**\n\n<br>\n\n**Statistical Control**\n\n<!-- ## Cookies and Happiness -->\n\n\n\n\n\n\n\n\n## Cookies and Happiness: OLS Regression Line {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/cookies-lm-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Regression Line Anatomy {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n# Fitting and Interpreting Models\n\n## Workflow\n<br>\n\n\n```{dot}\n//| echo: false\ndigraph G {\n  forcelabels=true;\n  splines=false;\n  fontname=\"AtkinsonHyperlegible-Regular\";\n  causal [\n    label = \"Causal Estimand\";\n    shape = rect; \n    group=a;\n  ];\n  stats [\n    label = \"Statistical Estimand\";\n    shape = rect;\n     group=a;\n  ];\n  est [\n    label = \"Estimate\";\n    shape = rect;\n     group=a;\n  ];\n  mod [\n    label = \"Causal Model\";\n    shape = oval;\n     group=b;\n  ];\n  data [\n    label = \"Data\";\n    shape = oval;\n    group=b;\n  ];\n\n  causal -> stats [xlabel = \"Identification    \" ];\n  stats -> est [ xlabel = \"Estimation   \"; dir = \"backward\"];\n  mod -> stats;\n  data -> est;\n\n{\n    rank=same;\n    causal; mod; \n  }\n  {\n    rank=same;\n    stats; data; \n  }\n\n\n}\n\n```\n\n\n\n## Language of Models {.smaller}\n\n\n-   **True Model**\n    $y = \\underbrace{\\beta_0}_{\\text{intercept}} + \\underbrace{\\beta_1}_{\\text{slope}} x + \\underbrace{\\varepsilon}_{\\text{error}}$\n    -   Population parameters $\\beta$: truth (estimand), unknown to us\n-   **Estimated Model**\n    $y = \\underbrace{\\hat\\beta_0}_{\\text{intercept}} + \\underbrace{\\hat\\beta_1}_{\\text{slope}} x + \\underbrace{\\hat\\varepsilon}_{\\text{residual}}$\n    -   Estimates $\\hat{\\beta}$: our best guess about the estimand given the\n        data\n-   A model has two parts:\n    -   **Systematic Component** of a linear model:\n        $\\underbrace{\\hat y}_{\\text{fitted}\\\\\\text{value}} = \\underbrace{\\hat\\beta_0}_{\\text{intercept}} + \\underbrace{\\hat\\beta_1}_{\\text{slope}} x$\n    -   **Stochastic Component** of a linear model: $\\hat\\varepsilon$\n\n\n## Vocabulary\n\n$$\ny = \\hat \\beta_0 + \\hat \\beta_1 x_1 + \\hat \\varepsilon\n$$\n\n-   $y$: dependent variable, outcome\n-   $x$: independent variable, treatment, explanatory variable, treatment,\n    predictor, feature\n-   $\\hat y$: predicted values of y, y-hat, fitted values, regression line\\\n-   $\\hat \\beta_0$: intercept, prediction when all $x=0$, constant\n-   $\\hat \\beta_k$: slope, the effect of $k$-th variable\n\n\n\n## Modeling Happiness with Cookies\n\n\n$$\ny = \\hat \\beta_0 + \\hat \\beta_1 x_1 + \\hat \\varepsilon\n$$\n\n$$\n\\begin{aligned}\n&{\\text{Happiness}} =  \\hat \\beta_0 +  \\hat \\beta_1 \\text{Cookies} + \\hat \\varepsilon\n\\end{aligned}\n$$\n\n$$\n\\begin{aligned}\n&\\widehat{\\text{Happiness}} =  \\hat \\beta_0 +  \\hat \\beta_1 \\text{Cookies} \n\\end{aligned}\n$$\n\n:::task\n\nWhat are the differences between equations?\n\n:::\n\n## Interpreting Slope Coefficient Poll {.normal}\n\n\n$$\n\\operatorname{\\widehat{Happiness}} = 1.16 + 0.155(\\operatorname{Number\\ of\\ Cookies\\ Eaten})\n$$\n\n\nThe slope of the model for predicting happiness score from number of consumed\ncookies is 0.155. Which of the\nfollowing is the best interpretation of this value?\n\n1.  For every additional cookie eaten, the happiness score goes up by\n    0.155 points, on average.\n2.  For every additional cookie eaten, we expect the happiness score to be\n    higher by 0.155 points, on\n    average.\n3.  For every additional cookie eaten, the happiness score goes up by\n    0.155 points.\n4.  For every one point increase in happiness score, the number of cookies eaten\n    goes up by 0.155 points, on\n    average.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_6421e783\" style=\"right:0;bottom:0;font-size:2;\" data-warnwhen=\"0\">\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">01</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">30</span></code>\n</div>\n```\n:::\n:::\n\n\n## Interpreting Slope and Intercept\n\n::: small\n$$\n\\operatorname{\\widehat{Happiness}} = 1.16 + 0.155(\\operatorname{Number\\ of\\ Cookies\\ Eaten})\n$$\n\n\n> Slope: For every additional cookie eaten, we expect the happiness score to be\n> higher by 0.155 points, on\n> average.\n\n-   Each additional cookie has the same effect on happiness, i.e. *marginal\n    effect* is constant\n    -   Associated increase in happiness is 0.155 for the first and, say, tenth\n        cookie\n\n> Intercept: If the number of eaten cookies is 0, we expect the happiness score\n> to be 1.16 points.\n\n-   Intercept is meaningful in the context of data because the predictor can\n    feasibly take values equal to or near zero\n:::\n\n## What Are Coefficient Values in OLS {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n$$\\text{Sum of Squared Residuals (SSR)} \\\\= \\sum^n_{i=1}\\hat{\\varepsilon_i}^2 \\\\ = \\sum^n_{i=1}(y_i - \\hat{y_i})^2 \\\\ = \\sum^n_{i=1}(y_i - \\hat{\\beta_0} - \\hat{\\beta_1} x_i)^2$$\n\n-   OLS estimator finds values of $\\hat\\beta$ which minimize $SSR$, the\n    unexplained variance\\\n-   We use differential calculus to find these values of $\\hat{\\beta}$\n\n:::\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-535a107dab3663d19c08\" style=\"width:100%;height:100%;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-535a107dab3663d19c08\">{\"x\":{\"visdat\":{\"74f26aa281e8\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"74f26aa281e8\",\"attrs\":{\"74f26aa281e8\":{\"x\":[-0.9,-0.837931034482759,-0.775862068965517,-0.713793103448276,-0.651724137931035,-0.589655172413793,-0.527586206896552,-0.46551724137931,-0.403448275862069,-0.341379310344828,-0.279310344827586,-0.217241379310345,-0.155172413793104,-0.0931034482758621,-0.0310344827586208,0.0310344827586206,0.093103448275862,0.155172413793103,0.217241379310345,0.279310344827586,0.341379310344828,0.403448275862069,0.46551724137931,0.527586206896552,0.589655172413793,0.651724137931034,0.713793103448276,0.775862068965517,0.837931034482759,0.9],\"y\":[-1,-0.931034482758621,-0.862068965517241,-0.793103448275862,-0.724137931034483,-0.655172413793103,-0.586206896551724,-0.517241379310345,-0.448275862068966,-0.379310344827586,-0.310344827586207,-0.241379310344828,-0.172413793103448,-0.103448275862069,-0.0344827586206897,0.0344827586206897,0.103448275862069,0.172413793103448,0.241379310344828,0.310344827586207,0.379310344827586,0.448275862068966,0.517241379310345,0.586206896551724,0.655172413793103,0.724137931034483,0.793103448275862,0.862068965517241,0.931034482758621,1],\"z\":[[1.81,1.67682520808561,1.55316290130797,1.43901307966706,1.3343757431629,1.23925089179548,1.1536385255648,1.07753864447087,1.01095124851367,0.953876337693222,0.906313912009513,0.868263971462545,0.839726516052319,0.820701545778835,0.811189060642093,0.811189060642093,0.820701545778835,0.839726516052319,0.868263971462545,0.906313912009513,0.953876337693222,1.01095124851367,1.07753864447087,1.1536385255648,1.23925089179548,1.3343757431629,1.43901307966706,1.55316290130797,1.67682520808561,1.81],[1.70212841854935,1.56895362663496,1.44529131985731,1.33114149821641,1.22650416171225,1.13137931034483,1.04576694411415,0.969667063020214,0.90307966706302,0.846004756242568,0.798442330558858,0.760392390011891,0.731854934601665,0.712829964328181,0.703317479191439,0.703317479191439,0.712829964328181,0.731854934601665,0.760392390011891,0.798442330558858,0.846004756242568,0.90307966706302,0.969667063020214,1.04576694411415,1.13137931034483,1.22650416171225,1.33114149821641,1.44529131985731,1.56895362663496,1.70212841854935],[1.60196195005945,1.46878715814507,1.34512485136742,1.23097502972652,1.12633769322235,1.03121284185493,0.945600475624257,0.869500594530321,0.802913198573127,0.745838287752675,0.698275862068966,0.660225921521998,0.631688466111772,0.612663495838288,0.603151010701546,0.603151010701546,0.612663495838288,0.631688466111772,0.660225921521998,0.698275862068966,0.745838287752675,0.802913198573127,0.869500594530321,0.945600475624257,1.03121284185493,1.12633769322235,1.23097502972652,1.34512485136742,1.46878715814507,1.60196195005945],[1.50950059453032,1.37632580261593,1.25266349583829,1.13851367419738,1.03387633769322,0.938751486325803,0.853139120095125,0.777039239001189,0.710451843043995,0.653376932223543,0.605814506539833,0.567764565992866,0.53922711058264,0.520202140309156,0.510689655172414,0.510689655172414,0.520202140309156,0.53922711058264,0.567764565992866,0.605814506539833,0.653376932223543,0.710451843043995,0.777039239001189,0.853139120095125,0.938751486325803,1.03387633769322,1.13851367419738,1.25266349583829,1.37632580261593,1.50950059453032],[1.42474435196195,1.29156956004756,1.16790725326992,1.05375743162901,0.949120095124852,0.853995243757432,0.768382877526754,0.692282996432818,0.625695600475624,0.568620689655172,0.521058263971463,0.483008323424495,0.454470868014269,0.435445897740785,0.425933412604043,0.425933412604043,0.435445897740785,0.454470868014269,0.483008323424495,0.521058263971463,0.568620689655173,0.625695600475624,0.692282996432818,0.768382877526754,0.853995243757432,0.949120095124851,1.05375743162901,1.16790725326992,1.29156956004756,1.42474435196195],[1.34769322235434,1.21451843043995,1.09085612366231,0.976706302021403,0.872068965517241,0.776944114149822,0.691331747919144,0.615231866825208,0.548644470868014,0.491569560047562,0.444007134363852,0.405957193816885,0.377419738406659,0.358394768133175,0.348882282996433,0.348882282996433,0.358394768133175,0.377419738406659,0.405957193816885,0.444007134363852,0.491569560047562,0.548644470868014,0.615231866825208,0.691331747919144,0.776944114149822,0.872068965517241,0.976706302021403,1.09085612366231,1.21451843043995,1.34769322235434],[1.27834720570749,1.1451724137931,1.02151010701546,0.907360285374554,0.802722948870393,0.707598097502973,0.621985731272295,0.545885850178359,0.479298454221165,0.422223543400713,0.374661117717004,0.336611177170036,0.30807372175981,0.289048751486326,0.279536266349584,0.279536266349584,0.289048751486326,0.30807372175981,0.336611177170036,0.374661117717004,0.422223543400714,0.479298454221165,0.545885850178359,0.621985731272295,0.707598097502973,0.802722948870392,0.907360285374554,1.02151010701546,1.1451724137931,1.27834720570749],[1.2167063020214,1.08353151010702,0.95986920332937,0.845719381688466,0.741082045184305,0.645957193816885,0.560344827586207,0.484244946492271,0.417657550535077,0.360582639714625,0.313020214030916,0.274970273483948,0.246432818073722,0.227407847800238,0.217895362663496,0.217895362663496,0.227407847800238,0.246432818073722,0.274970273483948,0.313020214030916,0.360582639714626,0.417657550535077,0.484244946492271,0.560344827586207,0.645957193816885,0.741082045184304,0.845719381688466,0.95986920332937,1.08353151010702,1.2167063020214],[1.16277051129608,1.02959571938169,0.905933412604043,0.791783590963139,0.687146254458977,0.592021403091558,0.50640903686088,0.430309155766944,0.36372175980975,0.306646848989298,0.259084423305589,0.221034482758621,0.192497027348395,0.173472057074911,0.163959571938169,0.163959571938169,0.173472057074911,0.192497027348395,0.221034482758621,0.259084423305589,0.306646848989299,0.36372175980975,0.430309155766944,0.50640903686088,0.592021403091558,0.687146254458977,0.791783590963139,0.905933412604043,1.02959571938169,1.16277051129608],[1.11653983353151,0.983365041617122,0.859702734839477,0.745552913198573,0.640915576694411,0.545790725326992,0.460178359096314,0.384078478002378,0.317491082045184,0.260416171224732,0.212853745541023,0.174803804994055,0.146266349583829,0.127241379310345,0.117728894173603,0.117728894173603,0.127241379310345,0.146266349583829,0.174803804994055,0.212853745541023,0.260416171224733,0.317491082045184,0.384078478002378,0.460178359096314,0.545790725326992,0.640915576694411,0.745552913198573,0.859702734839477,0.983365041617122,1.11653983353151],[1.07801426872771,0.944839476813317,0.821177170035672,0.707027348394768,0.602390011890606,0.507265160523187,0.421652794292509,0.345552913198573,0.278965517241379,0.221890606420927,0.174328180737218,0.13627824019025,0.107740784780024,0.0887158145065398,0.0792033293697979,0.0792033293697979,0.0887158145065398,0.107740784780024,0.13627824019025,0.174328180737218,0.221890606420928,0.278965517241379,0.345552913198573,0.421652794292509,0.507265160523187,0.602390011890606,0.707027348394768,0.821177170035672,0.944839476813317,1.07801426872771],[1.04719381688466,0.914019024970273,0.790356718192628,0.676206896551724,0.571569560047562,0.476444708680143,0.390832342449465,0.314732461355529,0.248145065398335,0.191070154577883,0.143507728894174,0.105457788347206,0.0769203329369798,0.0578953626634958,0.0483828775267539,0.0483828775267539,0.0578953626634958,0.0769203329369798,0.105457788347206,0.143507728894174,0.191070154577884,0.248145065398335,0.314732461355529,0.390832342449465,0.476444708680143,0.571569560047562,0.676206896551724,0.790356718192628,0.914019024970273,1.04719381688466],[1.02407847800238,0.890903686087991,0.767241379310345,0.653091557669441,0.54845422116528,0.45332936979786,0.367717003567182,0.291617122473246,0.225029726516052,0.1679548156956,0.120392390011891,0.0823424494649228,0.0538049940546968,0.0347800237812129,0.0252675386444709,0.0252675386444709,0.0347800237812129,0.0538049940546968,0.0823424494649228,0.120392390011891,0.167954815695601,0.225029726516052,0.291617122473246,0.367717003567182,0.45332936979786,0.548454221165279,0.653091557669441,0.767241379310345,0.89090368608799,1.02407847800238],[1.00866825208086,0.875493460166468,0.751831153388823,0.637681331747919,0.533043995243757,0.437919143876338,0.35230677764566,0.276206896551724,0.20961950059453,0.152544589774078,0.104982164090369,0.0669322235434008,0.0383947681331748,0.0193697978596909,0.00985731272294889,0.00985731272294889,0.0193697978596909,0.0383947681331748,0.0669322235434008,0.104982164090369,0.152544589774079,0.20961950059453,0.276206896551724,0.35230677764566,0.437919143876338,0.533043995243757,0.637681331747919,0.751831153388823,0.875493460166468,1.00866825208086],[1.0009631391201,0.867788347205708,0.744126040428062,0.629976218787158,0.525338882282997,0.430214030915577,0.344601664684899,0.268501783590963,0.201914387633769,0.144839476813317,0.0972770511296076,0.0592271105826397,0.0306896551724138,0.0116646848989298,0.00215219976218788,0.00215219976218788,0.0116646848989298,0.0306896551724138,0.0592271105826397,0.0972770511296076,0.144839476813318,0.201914387633769,0.268501783590963,0.344601664684899,0.430214030915577,0.525338882282996,0.629976218787158,0.744126040428062,0.867788347205707,1.0009631391201],[1.0009631391201,0.867788347205708,0.744126040428062,0.629976218787158,0.525338882282997,0.430214030915577,0.344601664684899,0.268501783590963,0.201914387633769,0.144839476813317,0.0972770511296076,0.0592271105826397,0.0306896551724138,0.0116646848989298,0.00215219976218787,0.00215219976218787,0.0116646848989298,0.0306896551724138,0.0592271105826397,0.0972770511296076,0.144839476813318,0.201914387633769,0.268501783590963,0.344601664684899,0.430214030915577,0.525338882282996,0.629976218787158,0.744126040428062,0.867788347205707,1.0009631391201],[1.00866825208086,0.875493460166468,0.751831153388823,0.637681331747919,0.533043995243757,0.437919143876338,0.35230677764566,0.276206896551724,0.20961950059453,0.152544589774078,0.104982164090369,0.0669322235434007,0.0383947681331748,0.0193697978596908,0.00985731272294887,0.00985731272294887,0.0193697978596908,0.0383947681331748,0.0669322235434007,0.104982164090369,0.152544589774079,0.20961950059453,0.276206896551724,0.35230677764566,0.437919143876338,0.533043995243757,0.637681331747919,0.751831153388823,0.875493460166468,1.00866825208086],[1.02407847800238,0.89090368608799,0.767241379310345,0.653091557669441,0.548454221165279,0.45332936979786,0.367717003567182,0.291617122473246,0.225029726516052,0.1679548156956,0.120392390011891,0.0823424494649227,0.0538049940546968,0.0347800237812128,0.0252675386444708,0.0252675386444708,0.0347800237812128,0.0538049940546967,0.0823424494649227,0.120392390011891,0.167954815695601,0.225029726516052,0.291617122473246,0.367717003567182,0.45332936979786,0.548454221165279,0.653091557669441,0.767241379310345,0.89090368608799,1.02407847800238],[1.04719381688466,0.914019024970273,0.790356718192628,0.676206896551724,0.571569560047562,0.476444708680143,0.390832342449465,0.314732461355529,0.248145065398335,0.191070154577883,0.143507728894174,0.105457788347206,0.0769203329369798,0.0578953626634958,0.0483828775267539,0.0483828775267539,0.0578953626634958,0.0769203329369798,0.105457788347206,0.143507728894174,0.191070154577884,0.248145065398335,0.314732461355529,0.390832342449465,0.476444708680143,0.571569560047562,0.676206896551724,0.790356718192628,0.914019024970273,1.04719381688466],[1.07801426872771,0.944839476813317,0.821177170035672,0.707027348394768,0.602390011890606,0.507265160523187,0.421652794292509,0.345552913198573,0.278965517241379,0.221890606420927,0.174328180737218,0.13627824019025,0.107740784780024,0.0887158145065398,0.0792033293697978,0.0792033293697978,0.0887158145065398,0.107740784780024,0.13627824019025,0.174328180737218,0.221890606420927,0.278965517241379,0.345552913198573,0.421652794292509,0.507265160523187,0.602390011890606,0.707027348394768,0.821177170035672,0.944839476813317,1.07801426872771],[1.11653983353151,0.983365041617122,0.859702734839477,0.745552913198573,0.640915576694411,0.545790725326992,0.460178359096314,0.384078478002378,0.317491082045184,0.260416171224732,0.212853745541023,0.174803804994055,0.146266349583829,0.127241379310345,0.117728894173603,0.117728894173603,0.127241379310345,0.146266349583829,0.174803804994055,0.212853745541023,0.260416171224733,0.317491082045184,0.384078478002378,0.460178359096314,0.545790725326992,0.640915576694411,0.745552913198573,0.859702734839477,0.983365041617122,1.11653983353151],[1.16277051129608,1.02959571938169,0.905933412604043,0.791783590963139,0.687146254458977,0.592021403091558,0.50640903686088,0.430309155766944,0.36372175980975,0.306646848989298,0.259084423305589,0.221034482758621,0.192497027348395,0.173472057074911,0.163959571938169,0.163959571938169,0.173472057074911,0.192497027348395,0.221034482758621,0.259084423305589,0.306646848989298,0.36372175980975,0.430309155766944,0.50640903686088,0.592021403091558,0.687146254458977,0.791783590963139,0.905933412604043,1.02959571938169,1.16277051129608],[1.2167063020214,1.08353151010702,0.95986920332937,0.845719381688466,0.741082045184305,0.645957193816885,0.560344827586207,0.484244946492271,0.417657550535077,0.360582639714625,0.313020214030916,0.274970273483948,0.246432818073722,0.227407847800238,0.217895362663496,0.217895362663496,0.227407847800238,0.246432818073722,0.274970273483948,0.313020214030916,0.360582639714626,0.417657550535077,0.484244946492271,0.560344827586207,0.645957193816885,0.741082045184304,0.845719381688466,0.95986920332937,1.08353151010702,1.2167063020214],[1.27834720570749,1.1451724137931,1.02151010701546,0.907360285374554,0.802722948870392,0.707598097502973,0.621985731272295,0.545885850178359,0.479298454221165,0.422223543400713,0.374661117717003,0.336611177170036,0.30807372175981,0.289048751486326,0.279536266349584,0.279536266349584,0.289048751486326,0.30807372175981,0.336611177170036,0.374661117717003,0.422223543400713,0.479298454221165,0.545885850178359,0.621985731272295,0.707598097502973,0.802722948870392,0.907360285374554,1.02151010701546,1.1451724137931,1.27834720570749],[1.34769322235434,1.21451843043995,1.09085612366231,0.976706302021403,0.872068965517241,0.776944114149821,0.691331747919144,0.615231866825208,0.548644470868014,0.491569560047562,0.444007134363852,0.405957193816885,0.377419738406659,0.358394768133175,0.348882282996433,0.348882282996433,0.358394768133175,0.377419738406659,0.405957193816885,0.444007134363852,0.491569560047562,0.548644470868014,0.615231866825208,0.691331747919144,0.776944114149821,0.872068965517241,0.976706302021403,1.09085612366231,1.21451843043995,1.34769322235434],[1.42474435196195,1.29156956004756,1.16790725326992,1.05375743162901,0.949120095124851,0.853995243757432,0.768382877526754,0.692282996432818,0.625695600475624,0.568620689655172,0.521058263971462,0.483008323424495,0.454470868014269,0.435445897740785,0.425933412604043,0.425933412604043,0.435445897740785,0.454470868014269,0.483008323424495,0.521058263971462,0.568620689655172,0.625695600475624,0.692282996432818,0.768382877526754,0.853995243757432,0.949120095124851,1.05375743162901,1.16790725326992,1.29156956004756,1.42474435196195],[1.50950059453032,1.37632580261593,1.25266349583829,1.13851367419738,1.03387633769322,0.938751486325802,0.853139120095125,0.777039239001189,0.710451843043995,0.653376932223543,0.605814506539833,0.567764565992865,0.53922711058264,0.520202140309156,0.510689655172414,0.510689655172414,0.520202140309156,0.53922711058264,0.567764565992865,0.605814506539833,0.653376932223543,0.710451843043995,0.777039239001189,0.853139120095125,0.938751486325802,1.03387633769322,1.13851367419738,1.25266349583829,1.37632580261593,1.50950059453032],[1.60196195005945,1.46878715814507,1.34512485136742,1.23097502972652,1.12633769322235,1.03121284185493,0.945600475624257,0.869500594530321,0.802913198573127,0.745838287752675,0.698275862068966,0.660225921521998,0.631688466111772,0.612663495838288,0.603151010701546,0.603151010701546,0.612663495838288,0.631688466111772,0.660225921521998,0.698275862068966,0.745838287752675,0.802913198573127,0.869500594530321,0.945600475624257,1.03121284185493,1.12633769322235,1.23097502972652,1.34512485136742,1.46878715814507,1.60196195005945],[1.70212841854935,1.56895362663496,1.44529131985731,1.33114149821641,1.22650416171225,1.13137931034483,1.04576694411415,0.969667063020214,0.90307966706302,0.846004756242568,0.798442330558858,0.76039239001189,0.731854934601665,0.712829964328181,0.703317479191439,0.703317479191439,0.712829964328181,0.731854934601665,0.76039239001189,0.798442330558858,0.846004756242568,0.90307966706302,0.969667063020214,1.04576694411415,1.13137931034483,1.22650416171225,1.33114149821641,1.44529131985731,1.56895362663496,1.70212841854935],[1.81,1.67682520808561,1.55316290130797,1.43901307966706,1.3343757431629,1.23925089179548,1.1536385255648,1.07753864447087,1.01095124851367,0.953876337693222,0.906313912009513,0.868263971462545,0.839726516052319,0.820701545778835,0.811189060642093,0.811189060642093,0.820701545778835,0.839726516052319,0.868263971462545,0.906313912009513,0.953876337693222,1.01095124851367,1.07753864447087,1.1536385255648,1.23925089179548,1.3343757431629,1.43901307966706,1.55316290130797,1.67682520808561,1.81]],\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"surface\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"\",\"scene\":{\"xaxis\":{\"title\":\"β₀\",\"showticklabels\":false},\"yaxis\":{\"title\":\"β₁\",\"showticklabels\":false},\"zaxis\":{\"title\":\"Sum of Squared Residuals\",\"showticklabels\":false}},\"hovermode\":\"closest\",\"showlegend\":false,\"legend\":{\"yanchor\":\"top\",\"y\":0.5}},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"colorbar\":{\"title\":\"\",\"ticklen\":2,\"len\":0.5,\"lenmode\":\"fraction\",\"y\":1,\"yanchor\":\"top\"},\"colorscale\":[[\"0\",\"rgba(68,1,84,1)\"],[\"0.0416666666666667\",\"rgba(70,19,97,1)\"],[\"0.0833333333333333\",\"rgba(72,32,111,1)\"],[\"0.125\",\"rgba(71,45,122,1)\"],[\"0.166666666666667\",\"rgba(68,58,128,1)\"],[\"0.208333333333333\",\"rgba(64,70,135,1)\"],[\"0.25\",\"rgba(60,82,138,1)\"],[\"0.291666666666667\",\"rgba(56,93,140,1)\"],[\"0.333333333333333\",\"rgba(49,104,142,1)\"],[\"0.375\",\"rgba(46,114,142,1)\"],[\"0.416666666666667\",\"rgba(42,123,142,1)\"],[\"0.458333333333333\",\"rgba(38,133,141,1)\"],[\"0.5\",\"rgba(37,144,140,1)\"],[\"0.541666666666667\",\"rgba(33,154,138,1)\"],[\"0.583333333333333\",\"rgba(39,164,133,1)\"],[\"0.625\",\"rgba(47,174,127,1)\"],[\"0.666666666666667\",\"rgba(53,183,121,1)\"],[\"0.708333333333333\",\"rgba(79,191,110,1)\"],[\"0.75\",\"rgba(98,199,98,1)\"],[\"0.791666666666667\",\"rgba(119,207,85,1)\"],[\"0.833333333333333\",\"rgba(147,214,70,1)\"],[\"0.875\",\"rgba(172,220,52,1)\"],[\"0.916666666666667\",\"rgba(199,225,42,1)\"],[\"0.958333333333333\",\"rgba(226,228,40,1)\"],[\"1\",\"rgba(253,231,37,1)\"]],\"showscale\":false,\"x\":[-0.9,-0.837931034482759,-0.775862068965517,-0.713793103448276,-0.651724137931035,-0.589655172413793,-0.527586206896552,-0.46551724137931,-0.403448275862069,-0.341379310344828,-0.279310344827586,-0.217241379310345,-0.155172413793104,-0.0931034482758621,-0.0310344827586208,0.0310344827586206,0.093103448275862,0.155172413793103,0.217241379310345,0.279310344827586,0.341379310344828,0.403448275862069,0.46551724137931,0.527586206896552,0.589655172413793,0.651724137931034,0.713793103448276,0.775862068965517,0.837931034482759,0.9],\"y\":[-1,-0.931034482758621,-0.862068965517241,-0.793103448275862,-0.724137931034483,-0.655172413793103,-0.586206896551724,-0.517241379310345,-0.448275862068966,-0.379310344827586,-0.310344827586207,-0.241379310344828,-0.172413793103448,-0.103448275862069,-0.0344827586206897,0.0344827586206897,0.103448275862069,0.172413793103448,0.241379310344828,0.310344827586207,0.379310344827586,0.448275862068966,0.517241379310345,0.586206896551724,0.655172413793103,0.724137931034483,0.793103448275862,0.862068965517241,0.931034482758621,1],\"z\":[[1.81,1.67682520808561,1.55316290130797,1.43901307966706,1.3343757431629,1.23925089179548,1.1536385255648,1.07753864447087,1.01095124851367,0.953876337693222,0.906313912009513,0.868263971462545,0.839726516052319,0.820701545778835,0.811189060642093,0.811189060642093,0.820701545778835,0.839726516052319,0.868263971462545,0.906313912009513,0.953876337693222,1.01095124851367,1.07753864447087,1.1536385255648,1.23925089179548,1.3343757431629,1.43901307966706,1.55316290130797,1.67682520808561,1.81],[1.70212841854935,1.56895362663496,1.44529131985731,1.33114149821641,1.22650416171225,1.13137931034483,1.04576694411415,0.969667063020214,0.90307966706302,0.846004756242568,0.798442330558858,0.760392390011891,0.731854934601665,0.712829964328181,0.703317479191439,0.703317479191439,0.712829964328181,0.731854934601665,0.760392390011891,0.798442330558858,0.846004756242568,0.90307966706302,0.969667063020214,1.04576694411415,1.13137931034483,1.22650416171225,1.33114149821641,1.44529131985731,1.56895362663496,1.70212841854935],[1.60196195005945,1.46878715814507,1.34512485136742,1.23097502972652,1.12633769322235,1.03121284185493,0.945600475624257,0.869500594530321,0.802913198573127,0.745838287752675,0.698275862068966,0.660225921521998,0.631688466111772,0.612663495838288,0.603151010701546,0.603151010701546,0.612663495838288,0.631688466111772,0.660225921521998,0.698275862068966,0.745838287752675,0.802913198573127,0.869500594530321,0.945600475624257,1.03121284185493,1.12633769322235,1.23097502972652,1.34512485136742,1.46878715814507,1.60196195005945],[1.50950059453032,1.37632580261593,1.25266349583829,1.13851367419738,1.03387633769322,0.938751486325803,0.853139120095125,0.777039239001189,0.710451843043995,0.653376932223543,0.605814506539833,0.567764565992866,0.53922711058264,0.520202140309156,0.510689655172414,0.510689655172414,0.520202140309156,0.53922711058264,0.567764565992866,0.605814506539833,0.653376932223543,0.710451843043995,0.777039239001189,0.853139120095125,0.938751486325803,1.03387633769322,1.13851367419738,1.25266349583829,1.37632580261593,1.50950059453032],[1.42474435196195,1.29156956004756,1.16790725326992,1.05375743162901,0.949120095124852,0.853995243757432,0.768382877526754,0.692282996432818,0.625695600475624,0.568620689655172,0.521058263971463,0.483008323424495,0.454470868014269,0.435445897740785,0.425933412604043,0.425933412604043,0.435445897740785,0.454470868014269,0.483008323424495,0.521058263971463,0.568620689655173,0.625695600475624,0.692282996432818,0.768382877526754,0.853995243757432,0.949120095124851,1.05375743162901,1.16790725326992,1.29156956004756,1.42474435196195],[1.34769322235434,1.21451843043995,1.09085612366231,0.976706302021403,0.872068965517241,0.776944114149822,0.691331747919144,0.615231866825208,0.548644470868014,0.491569560047562,0.444007134363852,0.405957193816885,0.377419738406659,0.358394768133175,0.348882282996433,0.348882282996433,0.358394768133175,0.377419738406659,0.405957193816885,0.444007134363852,0.491569560047562,0.548644470868014,0.615231866825208,0.691331747919144,0.776944114149822,0.872068965517241,0.976706302021403,1.09085612366231,1.21451843043995,1.34769322235434],[1.27834720570749,1.1451724137931,1.02151010701546,0.907360285374554,0.802722948870393,0.707598097502973,0.621985731272295,0.545885850178359,0.479298454221165,0.422223543400713,0.374661117717004,0.336611177170036,0.30807372175981,0.289048751486326,0.279536266349584,0.279536266349584,0.289048751486326,0.30807372175981,0.336611177170036,0.374661117717004,0.422223543400714,0.479298454221165,0.545885850178359,0.621985731272295,0.707598097502973,0.802722948870392,0.907360285374554,1.02151010701546,1.1451724137931,1.27834720570749],[1.2167063020214,1.08353151010702,0.95986920332937,0.845719381688466,0.741082045184305,0.645957193816885,0.560344827586207,0.484244946492271,0.417657550535077,0.360582639714625,0.313020214030916,0.274970273483948,0.246432818073722,0.227407847800238,0.217895362663496,0.217895362663496,0.227407847800238,0.246432818073722,0.274970273483948,0.313020214030916,0.360582639714626,0.417657550535077,0.484244946492271,0.560344827586207,0.645957193816885,0.741082045184304,0.845719381688466,0.95986920332937,1.08353151010702,1.2167063020214],[1.16277051129608,1.02959571938169,0.905933412604043,0.791783590963139,0.687146254458977,0.592021403091558,0.50640903686088,0.430309155766944,0.36372175980975,0.306646848989298,0.259084423305589,0.221034482758621,0.192497027348395,0.173472057074911,0.163959571938169,0.163959571938169,0.173472057074911,0.192497027348395,0.221034482758621,0.259084423305589,0.306646848989299,0.36372175980975,0.430309155766944,0.50640903686088,0.592021403091558,0.687146254458977,0.791783590963139,0.905933412604043,1.02959571938169,1.16277051129608],[1.11653983353151,0.983365041617122,0.859702734839477,0.745552913198573,0.640915576694411,0.545790725326992,0.460178359096314,0.384078478002378,0.317491082045184,0.260416171224732,0.212853745541023,0.174803804994055,0.146266349583829,0.127241379310345,0.117728894173603,0.117728894173603,0.127241379310345,0.146266349583829,0.174803804994055,0.212853745541023,0.260416171224733,0.317491082045184,0.384078478002378,0.460178359096314,0.545790725326992,0.640915576694411,0.745552913198573,0.859702734839477,0.983365041617122,1.11653983353151],[1.07801426872771,0.944839476813317,0.821177170035672,0.707027348394768,0.602390011890606,0.507265160523187,0.421652794292509,0.345552913198573,0.278965517241379,0.221890606420927,0.174328180737218,0.13627824019025,0.107740784780024,0.0887158145065398,0.0792033293697979,0.0792033293697979,0.0887158145065398,0.107740784780024,0.13627824019025,0.174328180737218,0.221890606420928,0.278965517241379,0.345552913198573,0.421652794292509,0.507265160523187,0.602390011890606,0.707027348394768,0.821177170035672,0.944839476813317,1.07801426872771],[1.04719381688466,0.914019024970273,0.790356718192628,0.676206896551724,0.571569560047562,0.476444708680143,0.390832342449465,0.314732461355529,0.248145065398335,0.191070154577883,0.143507728894174,0.105457788347206,0.0769203329369798,0.0578953626634958,0.0483828775267539,0.0483828775267539,0.0578953626634958,0.0769203329369798,0.105457788347206,0.143507728894174,0.191070154577884,0.248145065398335,0.314732461355529,0.390832342449465,0.476444708680143,0.571569560047562,0.676206896551724,0.790356718192628,0.914019024970273,1.04719381688466],[1.02407847800238,0.890903686087991,0.767241379310345,0.653091557669441,0.54845422116528,0.45332936979786,0.367717003567182,0.291617122473246,0.225029726516052,0.1679548156956,0.120392390011891,0.0823424494649228,0.0538049940546968,0.0347800237812129,0.0252675386444709,0.0252675386444709,0.0347800237812129,0.0538049940546968,0.0823424494649228,0.120392390011891,0.167954815695601,0.225029726516052,0.291617122473246,0.367717003567182,0.45332936979786,0.548454221165279,0.653091557669441,0.767241379310345,0.89090368608799,1.02407847800238],[1.00866825208086,0.875493460166468,0.751831153388823,0.637681331747919,0.533043995243757,0.437919143876338,0.35230677764566,0.276206896551724,0.20961950059453,0.152544589774078,0.104982164090369,0.0669322235434008,0.0383947681331748,0.0193697978596909,0.00985731272294889,0.00985731272294889,0.0193697978596909,0.0383947681331748,0.0669322235434008,0.104982164090369,0.152544589774079,0.20961950059453,0.276206896551724,0.35230677764566,0.437919143876338,0.533043995243757,0.637681331747919,0.751831153388823,0.875493460166468,1.00866825208086],[1.0009631391201,0.867788347205708,0.744126040428062,0.629976218787158,0.525338882282997,0.430214030915577,0.344601664684899,0.268501783590963,0.201914387633769,0.144839476813317,0.0972770511296076,0.0592271105826397,0.0306896551724138,0.0116646848989298,0.00215219976218788,0.00215219976218788,0.0116646848989298,0.0306896551724138,0.0592271105826397,0.0972770511296076,0.144839476813318,0.201914387633769,0.268501783590963,0.344601664684899,0.430214030915577,0.525338882282996,0.629976218787158,0.744126040428062,0.867788347205707,1.0009631391201],[1.0009631391201,0.867788347205708,0.744126040428062,0.629976218787158,0.525338882282997,0.430214030915577,0.344601664684899,0.268501783590963,0.201914387633769,0.144839476813317,0.0972770511296076,0.0592271105826397,0.0306896551724138,0.0116646848989298,0.00215219976218787,0.00215219976218787,0.0116646848989298,0.0306896551724138,0.0592271105826397,0.0972770511296076,0.144839476813318,0.201914387633769,0.268501783590963,0.344601664684899,0.430214030915577,0.525338882282996,0.629976218787158,0.744126040428062,0.867788347205707,1.0009631391201],[1.00866825208086,0.875493460166468,0.751831153388823,0.637681331747919,0.533043995243757,0.437919143876338,0.35230677764566,0.276206896551724,0.20961950059453,0.152544589774078,0.104982164090369,0.0669322235434007,0.0383947681331748,0.0193697978596908,0.00985731272294887,0.00985731272294887,0.0193697978596908,0.0383947681331748,0.0669322235434007,0.104982164090369,0.152544589774079,0.20961950059453,0.276206896551724,0.35230677764566,0.437919143876338,0.533043995243757,0.637681331747919,0.751831153388823,0.875493460166468,1.00866825208086],[1.02407847800238,0.89090368608799,0.767241379310345,0.653091557669441,0.548454221165279,0.45332936979786,0.367717003567182,0.291617122473246,0.225029726516052,0.1679548156956,0.120392390011891,0.0823424494649227,0.0538049940546968,0.0347800237812128,0.0252675386444708,0.0252675386444708,0.0347800237812128,0.0538049940546967,0.0823424494649227,0.120392390011891,0.167954815695601,0.225029726516052,0.291617122473246,0.367717003567182,0.45332936979786,0.548454221165279,0.653091557669441,0.767241379310345,0.89090368608799,1.02407847800238],[1.04719381688466,0.914019024970273,0.790356718192628,0.676206896551724,0.571569560047562,0.476444708680143,0.390832342449465,0.314732461355529,0.248145065398335,0.191070154577883,0.143507728894174,0.105457788347206,0.0769203329369798,0.0578953626634958,0.0483828775267539,0.0483828775267539,0.0578953626634958,0.0769203329369798,0.105457788347206,0.143507728894174,0.191070154577884,0.248145065398335,0.314732461355529,0.390832342449465,0.476444708680143,0.571569560047562,0.676206896551724,0.790356718192628,0.914019024970273,1.04719381688466],[1.07801426872771,0.944839476813317,0.821177170035672,0.707027348394768,0.602390011890606,0.507265160523187,0.421652794292509,0.345552913198573,0.278965517241379,0.221890606420927,0.174328180737218,0.13627824019025,0.107740784780024,0.0887158145065398,0.0792033293697978,0.0792033293697978,0.0887158145065398,0.107740784780024,0.13627824019025,0.174328180737218,0.221890606420927,0.278965517241379,0.345552913198573,0.421652794292509,0.507265160523187,0.602390011890606,0.707027348394768,0.821177170035672,0.944839476813317,1.07801426872771],[1.11653983353151,0.983365041617122,0.859702734839477,0.745552913198573,0.640915576694411,0.545790725326992,0.460178359096314,0.384078478002378,0.317491082045184,0.260416171224732,0.212853745541023,0.174803804994055,0.146266349583829,0.127241379310345,0.117728894173603,0.117728894173603,0.127241379310345,0.146266349583829,0.174803804994055,0.212853745541023,0.260416171224733,0.317491082045184,0.384078478002378,0.460178359096314,0.545790725326992,0.640915576694411,0.745552913198573,0.859702734839477,0.983365041617122,1.11653983353151],[1.16277051129608,1.02959571938169,0.905933412604043,0.791783590963139,0.687146254458977,0.592021403091558,0.50640903686088,0.430309155766944,0.36372175980975,0.306646848989298,0.259084423305589,0.221034482758621,0.192497027348395,0.173472057074911,0.163959571938169,0.163959571938169,0.173472057074911,0.192497027348395,0.221034482758621,0.259084423305589,0.306646848989298,0.36372175980975,0.430309155766944,0.50640903686088,0.592021403091558,0.687146254458977,0.791783590963139,0.905933412604043,1.02959571938169,1.16277051129608],[1.2167063020214,1.08353151010702,0.95986920332937,0.845719381688466,0.741082045184305,0.645957193816885,0.560344827586207,0.484244946492271,0.417657550535077,0.360582639714625,0.313020214030916,0.274970273483948,0.246432818073722,0.227407847800238,0.217895362663496,0.217895362663496,0.227407847800238,0.246432818073722,0.274970273483948,0.313020214030916,0.360582639714626,0.417657550535077,0.484244946492271,0.560344827586207,0.645957193816885,0.741082045184304,0.845719381688466,0.95986920332937,1.08353151010702,1.2167063020214],[1.27834720570749,1.1451724137931,1.02151010701546,0.907360285374554,0.802722948870392,0.707598097502973,0.621985731272295,0.545885850178359,0.479298454221165,0.422223543400713,0.374661117717003,0.336611177170036,0.30807372175981,0.289048751486326,0.279536266349584,0.279536266349584,0.289048751486326,0.30807372175981,0.336611177170036,0.374661117717003,0.422223543400713,0.479298454221165,0.545885850178359,0.621985731272295,0.707598097502973,0.802722948870392,0.907360285374554,1.02151010701546,1.1451724137931,1.27834720570749],[1.34769322235434,1.21451843043995,1.09085612366231,0.976706302021403,0.872068965517241,0.776944114149821,0.691331747919144,0.615231866825208,0.548644470868014,0.491569560047562,0.444007134363852,0.405957193816885,0.377419738406659,0.358394768133175,0.348882282996433,0.348882282996433,0.358394768133175,0.377419738406659,0.405957193816885,0.444007134363852,0.491569560047562,0.548644470868014,0.615231866825208,0.691331747919144,0.776944114149821,0.872068965517241,0.976706302021403,1.09085612366231,1.21451843043995,1.34769322235434],[1.42474435196195,1.29156956004756,1.16790725326992,1.05375743162901,0.949120095124851,0.853995243757432,0.768382877526754,0.692282996432818,0.625695600475624,0.568620689655172,0.521058263971462,0.483008323424495,0.454470868014269,0.435445897740785,0.425933412604043,0.425933412604043,0.435445897740785,0.454470868014269,0.483008323424495,0.521058263971462,0.568620689655172,0.625695600475624,0.692282996432818,0.768382877526754,0.853995243757432,0.949120095124851,1.05375743162901,1.16790725326992,1.29156956004756,1.42474435196195],[1.50950059453032,1.37632580261593,1.25266349583829,1.13851367419738,1.03387633769322,0.938751486325802,0.853139120095125,0.777039239001189,0.710451843043995,0.653376932223543,0.605814506539833,0.567764565992865,0.53922711058264,0.520202140309156,0.510689655172414,0.510689655172414,0.520202140309156,0.53922711058264,0.567764565992865,0.605814506539833,0.653376932223543,0.710451843043995,0.777039239001189,0.853139120095125,0.938751486325802,1.03387633769322,1.13851367419738,1.25266349583829,1.37632580261593,1.50950059453032],[1.60196195005945,1.46878715814507,1.34512485136742,1.23097502972652,1.12633769322235,1.03121284185493,0.945600475624257,0.869500594530321,0.802913198573127,0.745838287752675,0.698275862068966,0.660225921521998,0.631688466111772,0.612663495838288,0.603151010701546,0.603151010701546,0.612663495838288,0.631688466111772,0.660225921521998,0.698275862068966,0.745838287752675,0.802913198573127,0.869500594530321,0.945600475624257,1.03121284185493,1.12633769322235,1.23097502972652,1.34512485136742,1.46878715814507,1.60196195005945],[1.70212841854935,1.56895362663496,1.44529131985731,1.33114149821641,1.22650416171225,1.13137931034483,1.04576694411415,0.969667063020214,0.90307966706302,0.846004756242568,0.798442330558858,0.76039239001189,0.731854934601665,0.712829964328181,0.703317479191439,0.703317479191439,0.712829964328181,0.731854934601665,0.76039239001189,0.798442330558858,0.846004756242568,0.90307966706302,0.969667063020214,1.04576694411415,1.13137931034483,1.22650416171225,1.33114149821641,1.44529131985731,1.56895362663496,1.70212841854935],[1.81,1.67682520808561,1.55316290130797,1.43901307966706,1.3343757431629,1.23925089179548,1.1536385255648,1.07753864447087,1.01095124851367,0.953876337693222,0.906313912009513,0.868263971462545,0.839726516052319,0.820701545778835,0.811189060642093,0.811189060642093,0.820701545778835,0.839726516052319,0.868263971462545,0.906313912009513,0.953876337693222,1.01095124851367,1.07753864447087,1.1536385255648,1.23925089179548,1.3343757431629,1.43901307966706,1.55316290130797,1.67682520808561,1.81]],\"type\":\"surface\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\",\".hideLegend\":true},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n:::\n:::\n\n-   Check [Resources](https://r4da.live/resource/slr.html) on the class website\n    if you want to see the math behind it\n\n## Fitting Line Example I {.smaller}\n\n\n$$\n\\begin{aligned}\n&\\widehat{\\text{Happiness}} =  2 - 0.1 \\cdot \\text{Cookies} \n\\end{aligned}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=1950}\n:::\n:::\n\n\n## Fitting Line Example II {.smaller}\n\n\n\n$$\n\\begin{aligned}\n&\\widehat{\\text{Happiness}} =  2 + 0 \\cdot \\text{Cookies} = \\overline{\\text{Happiness}} \n\\end{aligned}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=1950}\n:::\n:::\n\n\n## Fitting Line Example III {.smaller}\n\n\n\n$$\n\\begin{aligned}\n&\\widehat{\\text{Happiness}} = 1.1 + 0.1 \\cdot \\text{Cookies}\n\\end{aligned}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=1950}\n:::\n:::\n\n\n## Fitting Line Example IV: OLS Solution {.smaller}\n\n\n\n$$\n\\begin{aligned}\n&\\widehat{\\text{Happiness}} =   1.16 + 0.155 \\cdot \\text{Cookies} \n\\end{aligned}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=1950}\n:::\n:::\n\n\n## Properties of Least Squares Regression\n\n::: smaller\n-   The regression line goes through the center of mass point, the coordinates\n    corresponding to average $X$ and average $Y$, $(\\bar{X}, \\bar{Y})$:\n\n$$\\bar{Y} = \\hat \\beta_0 + \\hat \\beta_1 \\bar{X} ~ \\rightarrow ~ \\hat \\beta_0 = \\bar{y} - \\hat \\beta_1 \\bar{x}$$\n\n-   The slope has the same sign as the correlation coefficient:\n    $\\beta_X = Corr(X,Y) \\dfrac{{\\sigma_Y}}{{\\sigma_X}}$\n\n-   The sum of the residuals is zero (by design): $\\sum_{i = 1}^n e_i = 0$\n:::\n\n# Beyond the Regression Line\n\n## Unexplained Variance in Y (a.k.a. Errors/Residuals) {.smaller}\n\n- random noise, the *stochastic* component of the model: the sum of “everything else” not in the systematic component of the model\n- we assume errors to be, on average, zero given every value of X: $\\mathbb{E}(\\varepsilon|X) = 0$\n\n<!-- $\\varepsilon \\sim \\mathcal{N}(0, \\sigma^2)$) --> \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=1950 height=80%}\n:::\n:::\n\n\n\n## Explained vs. Unexplained Variation\n\n::: smaller\n**Explained Sum of Squares:** $$ESS = \\sum^{n}_{i=1}(\\hat y_i - \\bar y)^2$$\n\n**Sum of Squared Residuals:**\n$$RSS = \\sum^n_{i=1}\\hat{\\varepsilon_i}^2 = \\sum^n_{i=1}(y_i - \\hat{y_i})^2$$\n\n**Total Sum of Squares:** $$TSS = \\sum^{n}_{i=1}(y_i - \\bar y)^2 = ESS + RSS$$\n:::\n\n## Explained vs. Unexplained Variation\n\n::: r-stack\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n::: fragment\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::: fragment\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::: fragment\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n:::\n\n\n\n\n\n\n\n\n## Residuals Plot\n\n-   Scatterplot of the regression residuals against the explanatory variable X\n    (or the predicted values of Y)\n<!-- -   Patterns in residuals signal that systematic influences on Y still have not -->\n<!--     been captured by our model, or that our model misrepresents the data, or -->\n<!--     that errors do not have a constant variance. -->\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=1950 height=90%}\n:::\n:::\n\n\n## Residuals from More Cookies Data (N = 100)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=1950}\n:::\n:::\n\n\n# Multiple Linear Regression (MLR)\n\n## Multiple ~~Multivariate~~ Linear Regression (MLR)\n\n$$ y = \\hat\\beta_0 + \\hat\\beta_1 x_1 +\n\\hat\\beta_2 x_2 + \\cdots + \\hat\\beta_k x_k\n+\\hat\\varepsilon$$\n\n::: small\n> A one unit increase in $x_k$ is *associated* with, **on average**, a $\\beta_k$\n> increase (decrease) in $y$, **holding all else constant**.\n\n<!-- > Categorical X: On average, **Y** is $\\hat\\beta_k$ units larger (or smaller) in **x_k**, compared to **x_k**<sub>omitted</sub>, **holding all else constant**. -->\n\n-   We obtain our coefficient for $x_k$ *independent of all other variables*\n-   We are comparing observations as though they had same value of other\n    variables\n-   You can also think of it as comparing *within* values of other variables\n-   Coefficient $\\hat\\beta_k$ tells us what is the value of a predictor $x$,\n    once we know other predictors in the model\n-   $\\hat \\beta_k$ captures the effect of $x_k$, which can be uniquely\n    attributed to this variable $x_k$.\n:::\n\n## Cookies and Weekend Predict Happiness\n\n$$ {\\text{Happiness}}  = \\hat\\beta_0 + \\hat\\beta_1 {\\text{Cookies}}  +\n\\hat\\beta_2 {\\text{Weekend}}+\\hat\\varepsilon$$\n\n::: columns\n::: {.column width=\"40%\"}\n\n```{dot}\n//| echo: false\n//| fig-width: 3\n//| fig-height: 2.5\n//| out-width: 100%\ndigraph D {\n  node [shape=oval, fontname=\"AtkinsonHyperlegible-Regular\"];\n  edge [minlen = 1.2, arrowhead = vee, arrowsize=0.5];\n  a [label = \"Cookies\"];\n  b [label = \"Happiness\"];\n  c [label = \"Weekend\"];\n  \n  {rank=same a b};\n  {rank=sink c};\n  a->b;\n  c->a;\n  c->b;\n}\n```\n\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhappiness_m2 <- lm(happiness ~ cookies + weekend, \n                   data = more_cookies)\ntidy(happiness_m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    0.163    0.0882      1.85 6.79e- 2\n2 cookies        0.154    0.0162      9.49 1.68e-15\n3 weekend        1.32     0.0503     26.1  1.08e-45\n```\n:::\n:::\n\n:::\n:::\n\n::: small\n> Reported happiness score is expected to be, on average,\n> 0.163 points on weekdays when having no cookies\n> eaten.\\\n> Each additional cookie eaten is *associated* with, **on average**, a\n> 0.154 increase in happiness level, **holding all\n> else constant**.\\\n> **On average**, happiness score is 1.315 points\n> higher on weekends than on weekdays, **holding cookies consumption constant**.\n:::\n\n## Regression Line Turns into a Hyperplane\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n<iframe src=\"p.html\" width=\"70%\" height=\"100%\" id=\"igraph\" scrolling=\"no\" seamless=\"seamless\" frameBorder=\"0\">\n\n</iframe>\n\n# Statistical Control\n\n## Confounders and Statistical Control\n\nClosing paths means ensuring we are comparing within the same values of\nconfounders. What does this mean statistically?\n\n1.  Remove the effect of the confounder W (*Weekend*) on X (*Cookies*) \n2.  Remove the effect of the confounder W (*Weekend*) on Y (*Happiness*)\n3.  Regress the leftovers of Y (*Happiness*), the residuals from step 2, on leftovers of X  (*Cookies*), the residuals from step 1.\n\n## Venn Diagrams: Variance and Covariance {.smaller}\n\n<br>\n\n![](images/correlation-simp.png){fig-align=\"center\" width=\"700\"}\n\n## Venn Diagrams: Slope Coefficients {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n::: smaller\nSlope coefficient for $X$, is the ratio between [*covariance of* $X$ and\n$Y$]{style=\"color: #003056;\"} and [*variance of* $X$]{style=\"color: #61993B;\"}\n\n$$\\beta_{x} = \\frac{cov(x,y)}{var(x)}= \\frac{B}{A+B}$$ Slope coefficient for\n$Z$, is the ratio between [*covariance of* $Z$ and $Y$]{style=\"color: #cc2c24;\"}\nand [*variance of* $Z$]{style=\"color: #a1a1a0;\"}\n\n$$\\beta_{z} = \\frac{cov(z,y)}{var(z)}= \\frac{D}{D+E}$$\n:::\n:::\n\n::: {.column width=\"50%\"}\n![](images/corr3.png)\n:::\n:::\n\n## Venn Diagrams: Statistical Control {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n::: smaller\nHere $X$ and $Z$ are correlated. If we did not include $Z$, our slope will still\nbe:\n\n$$\\beta_{biased} = \\frac{B + F}{A+B + F + G}$$\n\nIf we include $Z$, the slope becomes: $$\\beta_{unbiased} = \\frac{B}{A+B}$$\n\nSince we cannot attribute [*the effect of both* $X$ and $Z$\ntogether]{style=\"color: #058B8C;\"} to one single variable, that part ([section\nF]{style=\"color: #058B8C;\"}) is tossed out of the slope calculations.\n:::\n:::\n\n::: {.column width=\"50%\"}\n![](images/corr2.png)\n:::\n:::\n\n## Statistical Control: Data Example\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n<!-- ## Statistical Control in `R` -->\n\n<!-- ::: columns -->\n\n<!-- ::: {.column width=\"50%\"} -->\n\n<!-- # ```{r} -->\n\n<!-- # full_model <- lm(happiness ~ cookies + weekend,  -->\n\n<!-- #                  data = more_cookies)  -->\n\n<!-- # tidy(full_model) -->\n\n<!-- # ggplot(more_cookies, aes( -->\n\n<!-- #   x = cookies, -->\n\n<!-- #   y = happiness, -->\n\n<!-- #   color = as_factor(weekend) -->\n\n<!-- # )) + -->\n\n<!-- #   geom_jitter(width = 0.1) + -->\n\n<!-- #   guides(color = F) + -->\n\n<!-- #   geom_smooth(method = \"lm\") + -->\n\n<!-- #   scale_color_viridis_d() + -->\n\n<!-- #   labs(x = \"Cookies eaten\", y = \"Level of happiness\") + -->\n\n<!-- #   scale_x_continuous(breaks = scales::pretty_breaks(),  -->\n\n<!-- #                      limits = c(0, 10)) -->\n\n<!-- # ``` -->\n\n<!-- :::  -->\n\n<!-- ::: {.column width=\"50%\"} -->\n\n<!-- ## Statistical Control in `R`: Manually  -->\n\n<!-- ```{r} -->\n\n<!-- # Remove the effect of the confounder W (weekend) on X (cookies) -->\n\n<!-- step1 <- lm(cookies ~ weekend, data = more_cookies) -->\n\n<!-- step1$residuals %>% summary() -->\n\n<!-- # Remove the effect of the confounder W (weekend) on Y (happiness) -->\n\n<!-- step2 <- lm(happiness ~ weekend, data = more_cookies) -->\n\n<!-- step2$residuals %>% summary() -->\n\n<!-- # Regress the leftovers of Y on leftovers of X -->\n\n<!-- step3 <- lm(step2$residuals ~ step1$residuals) -->\n\n<!-- tidy(step3) -->\n\n<!-- ``` -->\n\n<!-- :::  -->\n\n<!-- ::: -->\n\n## Predictions (a.k.a. Expected or Fitted Values) {.smaller}\n\n$$\\operatorname{\\widehat{Happiness}} = 0.163 + 0.154 \\cdot \\operatorname{Cookies} + 1.315 \\cdot \\text{Weekend}$$\n\n<br>\n\nFitted values for Happiness given Weekend $= 1$:\n\n$$\\operatorname{\\widehat{Happiness}_{Weekend}} = 0.163 + 0.154 \\cdot \\operatorname{Cookies} + 1.315 \\cdot 1 \\\\ = 1.478 + 0.154\\cdot\\operatorname{Cookies}$$\nFitted values for Happiness given Weekend $= 0$:\n\n$$\\operatorname{\\widehat{Happiness}_{Weekday}} = 0.163 + 0.154 \\cdot \\operatorname{Cookies} + 1.315 \\cdot 0 \\\\ = 0.163 + 0.154\\cdot\\operatorname{Cookies}$$\n\nExpected value for Happiness given Cookies $= 5$ & Weekend $= 0$:\n\n$$\\mathbb{E}[\\operatorname{Happiness|Cookies = 5, Weekend = 0}] = 0.163 + 0.154 \\cdot 5 + 1.315 \\cdot 0 \\\\ = 0.163 + 0.154\\cdot\\operatorname{5} = 0.933$$\n\n## Predictions for MLR: Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-regression_files/figure-revealjs/unnamed-chunk-20-1.png){fig-align='center' width=1950 height=80%}\n:::\n:::\n\n\n\n## Building models in `R`\n\n<br>\n\n##### Base `R` Functions\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nname_of_model <- lm(<Y> ~ <X>, data = <DATA>)\n\nsummary(name_of_model)  # See model details\n```\n:::\n\n\n::: small\n<br> Only complete observations are used for estimation: `R` removes rows with\nNAs by default <br>\n:::\n\n##### Tidy functions from `broom`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(broom)\n\n# Convert model results to a data frame for plotting\ntidy(name_of_model)\n\n# Convert model diagnostics to a data frame\nglance(name_of_model)\n\n# Add columns of fitted values, residuals, and some other stuff \naugment(name_of_model)\n```\n:::\n\n\n# Building Models in R\n\n## Modeling Happiness with Cookies\n\n<br>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhappiness_model <- lm(happiness ~ cookies, data = cookies_data)\nsummary(happiness_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = happiness ~ cookies, data = cookies_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.81455 -0.61455  0.03091  0.54682  1.06727 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)  \n(Intercept)   1.1600     0.4901   2.367   0.0455 *\ncookies       0.1545     0.0790   1.956   0.0861 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7175 on 8 degrees of freedom\nMultiple R-squared:  0.3236,\tAdjusted R-squared:  0.2391 \nF-statistic: 3.827 on 1 and 8 DF,  p-value: 0.08614\n```\n:::\n:::\n\n\n\n<!-- ```{r} -->\n<!-- happines_res <- resid(happiness_model) # residuals  -->\n<!-- happiness_fitted <- fitted(happiness_model) # fitted values  -->\n<!-- ``` -->\n\n## Modeling Happiness with Cookies: Tidy Functions\n\n<br>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(happiness_model, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 7\n  term        estimate std.error statistic p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 (Intercept)    1.16     0.490       2.37  0.0455   0.0297     2.29 \n2 cookies        0.155    0.0790      1.96  0.0861  -0.0276     0.337\n```\n:::\n:::\n\n\n<br>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(happiness_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.s…¹ sigma stati…² p.value    df logLik   AIC   BIC devia…³ df.re…⁴  nobs\n      <dbl>     <dbl> <dbl>   <dbl>   <dbl> <dbl>  <dbl> <dbl> <dbl>   <dbl>   <int> <int>\n1     0.324     0.239 0.718    3.83  0.0861     1  -9.75  25.5  26.4    4.12       8    10\n# … with abbreviated variable names ¹​adj.r.squared, ²​statistic, ³​deviance, ⁴​df.residual\n```\n:::\n:::\n\n\n## Main Take Aways \n\n- Regression model represents our idea of the data-generation process (DAG) in the systematic component, everything else is captured in the error term\n- Slope represents the expected change in $y$ in response to one-unit change in $x_k$, and is constant across every value in $x_k$\n- The procedure of statistical control ensures that we we only obtain the effects that are uniquely attributed to that explanatory variable \n",
    "supporting": [
      "06-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/countdown-0.3.5/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/countdown-0.3.5/countdown.js\"></script>\n<script src=\"../../site_libs/htmlwidgets-1.5.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.1/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}