<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Learning to use data and statistics to explore the social, political, and economic world">

<title>R for Data Analysis - Problem Set 7: Suggested Solutions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="..//files/icon-512.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="R for Data Analysis - Problem Set 7: Suggested Solutions">
<meta property="og:description" content="We will be working with the following specification of the model:">
<meta property="og:image" content="https://r4da.netlify.app/files/icon-512.png">
<meta property="og:site-name" content="R for Data Analysis">
<meta property="og:locale" content="en_US">
<meta property="og:image:height" content="512">
<meta property="og:image:width" content="512">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">R for Data Analysis</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html">
 <span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html">
 <span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../material/index.html">
 <span class="menu-text">Course Material</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resource/index.html">
 <span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../s23/index.html">
 <span class="menu-text">Spring 2023</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/r4da-f23"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://rstudio.cloud"><i class="bi bi-cloud-fill" role="img" aria-label="RStudio.cloud">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#task-1-modeling" id="toc-task-1-modeling" class="nav-link active" data-scroll-target="#task-1-modeling">Task 1: Modeling</a></li>
  <li><a href="#task-2-uncertainty" id="toc-task-2-uncertainty" class="nav-link" data-scroll-target="#task-2-uncertainty">Task 2: Uncertainty</a></li>
  <li><a href="#task-3-marginal-effects-plots" id="toc-task-3-marginal-effects-plots" class="nav-link" data-scroll-target="#task-3-marginal-effects-plots">Task 3: Marginal Effects Plots</a></li>
  <li><a href="#task-4-quarto-chunk-options" id="toc-task-4-quarto-chunk-options" class="nav-link" data-scroll-target="#task-4-quarto-chunk-options">Task 4: Quarto Chunk Options</a></li>
  <li><a href="#task-5-knitting-and-formatting" id="toc-task-5-knitting-and-formatting" class="nav-link" data-scroll-target="#task-5-knitting-and-formatting">Task 5: Knitting and Formatting</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Problem Set 7: Suggested Solutions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="task-1-modeling" class="level2">
<h2 class="anchored" data-anchor-id="task-1-modeling">Task 1: Modeling</h2>
<p>We will be working with the following specification of the model:</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{{\% \ Progressive\ Votes}} &amp;= {\beta}_{0}\ + {\beta}_{1} \cdot \operatorname{At \ least \ 1 \ daughter}\ +  \ {\beta}_{2} \cdot \operatorname{Woman}\ +  \ {\beta}_{3} \cdot \operatorname{Age}\ + \\
&amp;\quad {\beta}_{4} \cdot \operatorname{Catholic}\ +  \ {\beta}_{5} \cdot \operatorname{Asian}\ +  \ {\beta}_{6} \cdot \operatorname{African}\ +  \ {\beta}_{7} \cdot \operatorname{Hispanic}\ + \\
&amp;\quad {\beta}_{8} \cdot \operatorname{Republican}\ +  \ {\beta}_{9} \cdot \operatorname{Number \ of \ kids}\ + \ \varepsilon \\
\varepsilon \sim {\mathcal{N}(0, \sigma^2)}
\end{aligned}
\]</span></p>
<p>1.1. What does the part <span class="math inline">\(\mathcal{N}(0, \sigma^2)\)</span> in this equation imply?</p>
<blockquote class="blockquote">
<p>The error term is normally distributed with the mean of 0 and a standard deviation of <span class="math inline">\(\sigma\)</span>, which is a constant value across all values of the dependent variable. In otehr words, the zero mean of the error term distribution means that on average, our predictions are correct (error is zero) and that variance of our predictions stays the same, i.e.&nbsp;there are no values that we can predict better (smaller error) or worse (larger error). This assumption is required for us to use confidence intervals and hypotheses testing for our estimates.</p>
</blockquote>
<p>1.2. Estimate the model with this specification on (1) all judges (store in <code>m1</code>), (2) only parents (store in <code>m2</code>), and (3) only parents with 1 - 4 kids (store in <code>m3</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: models</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  progressive_vote <span class="sc">~</span> woman <span class="sc">+</span> age <span class="sc">+</span> republican <span class="sc">+</span> asian <span class="sc">+</span> african <span class="sc">+</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    hispanic <span class="sc">+</span> catholic <span class="sc">+</span> kids <span class="sc">+</span> any_girls,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> judges</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  progressive_vote <span class="sc">~</span> woman <span class="sc">+</span> age <span class="sc">+</span> republican <span class="sc">+</span> asian <span class="sc">+</span> african <span class="sc">+</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    hispanic <span class="sc">+</span> catholic <span class="sc">+</span> kids <span class="sc">+</span> any_girls,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> judges <span class="sc">%&gt;%</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(kids <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  progressive_vote <span class="sc">~</span> woman <span class="sc">+</span> age <span class="sc">+</span> republican <span class="sc">+</span> asian <span class="sc">+</span> african <span class="sc">+</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    hispanic <span class="sc">+</span> catholic <span class="sc">+</span> kids <span class="sc">+</span> any_girls,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> judges <span class="sc">%&gt;%</span> <span class="fu">subset</span>(kids <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> kids <span class="sc">&lt;</span> <span class="dv">5</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>1.3. Put the regression results in a well-formatted regression table. You are provided with the template below. Make sure that the table fulfills all the following criteria.</p>
<p><em>Well-formatted table (i.e.&nbsp;something you would always want to have in your papers) means that:</em></p>
<ol type="1">
<li><em>A table has a descriptive title</em></li>
<li><em>All variable names are meaningful and clear (not the raw variable names in <code>R</code>)</em></li>
<li><em>Names of dummy variables should be meaningful, with the title indicating the category for</em> <span class="math inline">\(X = 1\)</span> <em>(e.g.&nbsp;Female, not Gender).</em></li>
<li><em>Should there be any categorical variables that were recoded as dummies (like <code>race</code> in our case), the baseline, i.e.&nbsp;the omitted, category should be mentioned in the notes to the table. If a categorical variable was included with only one category (like catholic here), you don’t need to mention the other categories as long as the variable name is clear.</em></li>
<li><em>Should you be including p-values as stars, make sure to indicate the corresponding significance levels.</em></li>
</ol>
<p>You can learn more about the syntax of this function on the package webpage: <a href="https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html" class="uri">https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: regression-table</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: true # add echo: false to hide source code</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">models =</span> <span class="fu">list</span>(m1, m2, m3),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"The Effect of Having Daughters on Judges' Ruling"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">gof_omit =</span> <span class="st">"IC|F|Log."</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">align =</span> <span class="st">"lccc"</span>, <span class="co"># left-align first column, center other three</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">coef_map =</span> <span class="fu">c</span>(</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"any_girls"</span> <span class="ot">=</span> <span class="st">"At least 1 daughter"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"woman"</span> <span class="ot">=</span> <span class="st">"Female"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"age"</span> <span class="ot">=</span> <span class="st">"Age (years)"</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"catholic"</span> <span class="ot">=</span> <span class="st">"Catholic"</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"asian"</span> <span class="ot">=</span> <span class="st">"Race: Asian"</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"african"</span> <span class="ot">=</span> <span class="st">"Race: African"</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"hispanic"</span> <span class="ot">=</span> <span class="st">"Race: Hispanic"</span>,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"republican"</span> <span class="ot">=</span> <span class="st">"Republican"</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"kids"</span> <span class="ot">=</span> <span class="st">"Number of Kids"</span>,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"(Intercept)"</span> <span class="ot">=</span> <span class="st">"Intercept"</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">notes =</span> <span class="fu">list</span>(</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Notes: Standard errors in parentheses. White is the baseline category for race variable."</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">fmt =</span> <span class="dv">3</span>,</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># round to 3 digits after zero</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">stars =</span> T <span class="co"># include p-values</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">add_header_above</span>( <span class="co"># add an extra row with</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>      <span class="st">" "</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="co"># nothing in column 1</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>      <span class="st">"DV: Proportion of Progressive Votes"</span> <span class="ot">=</span> <span class="dv">3</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">bold =</span> F,</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">italic =</span> T</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">add_header_above</span>(<span class="fu">c</span>( <span class="co"># add info about samples</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">" "</span> <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">"All judges"</span> <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Parents"</span> <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Parents (1-4 kids)"</span> <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">column_spec</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">width =</span> <span class="st">"3cm"</span>) <span class="co"># set the size of 2, 3, 4 columns in table to 3 cm</span></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table style="NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;" class="table">
<caption>The Effect of Having Daughters on Judges' Ruling</caption>
 <thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1"></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">All judges</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Parents</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Parents (1-4 kids)</div></th>
</tr>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1"></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; font-style: italic; " colspan="3"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">DV: Proportion of Progressive Votes</div></th>
</tr>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> &nbsp;(1) </th>
   <th style="text-align:center;"> &nbsp;&nbsp;(2) </th>
   <th style="text-align:center;"> &nbsp;&nbsp;(3) </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> At least 1 daughter </td>
   <td style="text-align:center;width: 3cm; "> 0.050 </td>
   <td style="text-align:center;width: 3cm; "> 0.097 </td>
   <td style="text-align:center;width: 3cm; "> 0.108+ </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;width: 3cm; "> (0.053) </td>
   <td style="text-align:center;width: 3cm; "> (0.058) </td>
   <td style="text-align:center;width: 3cm; "> (0.059) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Female </td>
   <td style="text-align:center;width: 3cm; "> −0.042 </td>
   <td style="text-align:center;width: 3cm; "> −0.006 </td>
   <td style="text-align:center;width: 3cm; "> −0.006 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;width: 3cm; "> (0.065) </td>
   <td style="text-align:center;width: 3cm; "> (0.075) </td>
   <td style="text-align:center;width: 3cm; "> (0.074) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Age (years) </td>
   <td style="text-align:center;width: 3cm; "> 0.003 </td>
   <td style="text-align:center;width: 3cm; "> 0.004 </td>
   <td style="text-align:center;width: 3cm; "> 0.003 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;width: 3cm; "> (0.003) </td>
   <td style="text-align:center;width: 3cm; "> (0.003) </td>
   <td style="text-align:center;width: 3cm; "> (0.004) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Catholic </td>
   <td style="text-align:center;width: 3cm; "> −0.056 </td>
   <td style="text-align:center;width: 3cm; "> −0.056 </td>
   <td style="text-align:center;width: 3cm; "> −0.044 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;width: 3cm; "> (0.045) </td>
   <td style="text-align:center;width: 3cm; "> (0.048) </td>
   <td style="text-align:center;width: 3cm; "> (0.049) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Race: Asian </td>
   <td style="text-align:center;width: 3cm; "> −0.009 </td>
   <td style="text-align:center;width: 3cm; "> −0.009 </td>
   <td style="text-align:center;width: 3cm; "> 0.005 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;width: 3cm; "> (0.252) </td>
   <td style="text-align:center;width: 3cm; "> (0.252) </td>
   <td style="text-align:center;width: 3cm; "> (0.246) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Race: African </td>
   <td style="text-align:center;width: 3cm; "> −0.046 </td>
   <td style="text-align:center;width: 3cm; "> −0.027 </td>
   <td style="text-align:center;width: 3cm; "> −0.045 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;width: 3cm; "> (0.102) </td>
   <td style="text-align:center;width: 3cm; "> (0.109) </td>
   <td style="text-align:center;width: 3cm; "> (0.117) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Race: Hispanic </td>
   <td style="text-align:center;width: 3cm; "> −0.115 </td>
   <td style="text-align:center;width: 3cm; "> −0.155 </td>
   <td style="text-align:center;width: 3cm; "> −0.161 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;width: 3cm; "> (0.132) </td>
   <td style="text-align:center;width: 3cm; "> (0.152) </td>
   <td style="text-align:center;width: 3cm; "> (0.149) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Republican </td>
   <td style="text-align:center;width: 3cm; "> −0.118* </td>
   <td style="text-align:center;width: 3cm; "> −0.113* </td>
   <td style="text-align:center;width: 3cm; "> −0.116* </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;width: 3cm; "> (0.046) </td>
   <td style="text-align:center;width: 3cm; "> (0.048) </td>
   <td style="text-align:center;width: 3cm; "> (0.049) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Number of Kids </td>
   <td style="text-align:center;width: 3cm; "> −0.020 </td>
   <td style="text-align:center;width: 3cm; "> −0.008 </td>
   <td style="text-align:center;width: 3cm; "> −0.028 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;width: 3cm; "> (0.015) </td>
   <td style="text-align:center;width: 3cm; "> (0.016) </td>
   <td style="text-align:center;width: 3cm; "> (0.025) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Intercept </td>
   <td style="text-align:center;width: 3cm; "> 0.392* </td>
   <td style="text-align:center;width: 3cm; "> 0.271 </td>
   <td style="text-align:center;width: 3cm; "> 0.320 </td>
  </tr>
  <tr>
   <td style="text-align:left;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 3cm; "> (0.176) </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 3cm; "> (0.198) </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 3cm; "> (0.210) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Num.Obs. </td>
   <td style="text-align:center;width: 3cm; "> 161 </td>
   <td style="text-align:center;width: 3cm; "> 144 </td>
   <td style="text-align:center;width: 3cm; "> 130 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R2 </td>
   <td style="text-align:center;width: 3cm; "> 0.074 </td>
   <td style="text-align:center;width: 3cm; "> 0.084 </td>
   <td style="text-align:center;width: 3cm; "> 0.094 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R2 Adj. </td>
   <td style="text-align:center;width: 3cm; "> 0.019 </td>
   <td style="text-align:center;width: 3cm; "> 0.023 </td>
   <td style="text-align:center;width: 3cm; "> 0.026 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RMSE </td>
   <td style="text-align:center;width: 3cm; "> 0.24 </td>
   <td style="text-align:center;width: 3cm; "> 0.24 </td>
   <td style="text-align:center;width: 3cm; "> 0.23 </td>
  </tr>
</tbody>
<tfoot>
<tr><td style="padding: 0; " colspan="100%">
<sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr>
<tr><td style="padding: 0; " colspan="100%">
<sup></sup> Notes: Standard errors in parentheses. White is the baseline category for race variable.</td></tr>
</tfoot>
</table>

</div>
</div>
<p>1.4. Interpret the regression results in 2-3 sentences. Key things to mention:</p>
<ul>
<li><em>The effect of your main explanatory variable across the models taking into account both the uncertainty about the estimate and the size of the effect.</em></li>
<li><em>You don’t need to interpret the effects of control variables, but if you do, always frame it as a correlation, not a causal relationship.</em></li>
</ul>
<blockquote class="blockquote">
<p>Since judges who have no kids may be systematically different from those who choose to have kids, it is reasonable to restrict the sample to parents alone. The subsample of parents with one to four kids excludes potential outliers that could be driving the results. On this subsample, holding all else constant, having one daughter or more, on average, results in 10 percentage point increase in progressive vote at the 0.1 level of significance. However, we cannot reject the null hypothesis of no effect at the 0.05 level of significance for this subsample, as well as for subsamples of all parents and all judges.</p>
</blockquote>
<div style="page-break-after: always;"></div>
</section>
<section id="task-2-uncertainty" class="level2">
<h2 class="anchored" data-anchor-id="task-2-uncertainty">Task 2: Uncertainty</h2>
<p>2.1. Using model 3, calculate 90% and 95% confidence intervals for your estimates (<code>tidy()</code> from <code>broom</code> package can help, or you can use <code>modelsummary()</code> and specify arguments as <code>statistic = 'conf.int', conf_level = .90</code>). Interpret the effect of the <code>any_girls</code> variable using interval estimates rather than the point estimate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: cis</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m3, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(<span class="fu">tidy</span>(m3, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"any_girls"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(term, estimate, <span class="fu">starts_with</span>(<span class="st">"conf"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="fu">c</span>(<span class="st">"90% CI"</span>, <span class="st">"95% CI"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> term </th>
   <th style="text-align:right;"> estimate </th>
   <th style="text-align:right;"> conf.low </th>
   <th style="text-align:right;"> conf.high </th>
   <th style="text-align:left;"> level </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> any_girls </td>
   <td style="text-align:right;"> 0.108 </td>
   <td style="text-align:right;"> 0.009 </td>
   <td style="text-align:right;"> 0.206 </td>
   <td style="text-align:left;"> 90% CI </td>
  </tr>
  <tr>
   <td style="text-align:left;"> any_girls </td>
   <td style="text-align:right;"> 0.108 </td>
   <td style="text-align:right;"> -0.010 </td>
   <td style="text-align:right;"> 0.225 </td>
   <td style="text-align:left;"> 95% CI </td>
  </tr>
</tbody>
</table>

</div>
</div>
<blockquote class="blockquote">
<p>With 90% confidence, we can expect that having at least one daughter is associated with an expected increase of 0.009 to 0.206 in the proportion of progressive votes for a judges, holding all else constant. When relying on the 95% confidence intervals, we can expect an effect of having daughters to range from -0.9 to 22.5 percentage points, which means that the associated increase in progressive voteshare is not significantly different from zero at this level.<br>
Generally speaking, confidence intervals are constructed such that, when repeating the sampling a large number of times and estimating the parameters on each of these samples, at least 90% (or 95%) of these calculated intervals cover the true parameter.</p>
</blockquote>
<p>2.2. Which of the confidence intervals is wider, the 90% or the 95% one? Which one is more conservative (conservative means that using an interval, it is harder for us to reject the null hypothesis of, say, the effect being zero)?</p>
<blockquote class="blockquote">
<p>The 95% confidence interval is wider, it is also more conversative.</p>
</blockquote>
<p>2.3. Generally speaking, what is the trade-off when choosing a narrow vs.&nbsp;wider confidence interval to report?</p>
<blockquote class="blockquote">
<p>The general trade-off when reporting interval measures is teh one between accuracy and precision. Accuracy implies that we estimate the parameter correctly, while precision means that varianec of our estimates is smaller. When having a wider interval, we have better chances of reporting the true value of the effect (i.e.&nbsp;we are more accurate) yet wider intervals may become uninformative. An extreme case of this would be a confidence interval of 100%, which would range from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(+\infty\)</span>, definitely covers the true value, but is useless for interpretation.</p>
</blockquote>
<p>2.4. Based on the CIs you calculated for the effect of <code>any_girls</code>, which of the statements are correct? Why (not)?</p>
<p>2.4.1. The probability that the intervals we calculated, <span class="math inline">\([-0.01, 0.225]\)</span> and <span class="math inline">\([0.009, 0.206]\)</span>, include the true effect of <code>any_girls</code> on the <code>progressive_vote</code> is 95% and 90%, respectively.</p>
<blockquote class="blockquote">
<p>This is incorrect: confidence intervals contain the true parameter at least 95% (90%) of the times if we repeat the experiment (i.e.&nbsp;sampling process and estimation) a large number of times. Our calculated CI either covers the true value or not.</p>
</blockquote>
<p>2.4.2. If we were to collect many more samples and estimate the effect <span class="math inline">\(\hat\beta_1\)</span> of having at least one daughter on feminist voting, there is a 90% chance that the effects <span class="math inline">\(\hat\beta_1\)</span> estimated on those other sample would also range between <span class="math inline">\([0.009, 0.206]\)</span>.</p>
<blockquote class="blockquote">
<p>This is incorrect: a single confidence interval calculated on one sample does not tell us anything about the confidence intervals estimates on other subsamples. The procedure of confidence intervals construction is about the true value of the parameter only.</p>
</blockquote>
<p>2.4.3. The effect <span class="math inline">\(\hat\beta_1\)</span> of having at least one daughter on feminist voting is significantly different from zero at 90% confidence level, but not at the 95% confidence level.</p>
<blockquote class="blockquote">
<p>This is correct: whether zero is included in the confidence interval allows us to see if the effect is different from that value at a specified significance/confidence level. 95% CI <span class="math inline">\([-0.01, 0.225]\)</span> includes zero and 90% CI <span class="math inline">\([0.009, 0.206]\)</span> does not.</p>
</blockquote>
<p>2.4.4. The effect <span class="math inline">\(\hat\beta_1\)</span> of having at least one daughter on feminist voting is significantly different from 0.5 at both 90% and 95% confidence levels.</p>
<blockquote class="blockquote">
<p>This is correct: like with zero, we can compare if a certain value is included in the confidence interval or not and conclude whetehr the effect is different from that value at a specified significance/confidence level. Neither 95% CI <span class="math inline">\([-0.01, 0.225]\)</span> nor 90% CI <span class="math inline">\([0.009, 0.206]\)</span> include 0.5, hence the effect of having at least one daughter on feminist voting is significantly different from 0.5 on both levels.</p>
</blockquote>
<p>2.4.5. The probability that the intervals we calculated, <span class="math inline">\([-0.01, 0.225]\)</span> and <span class="math inline">\([0.009, 0.206]\)</span>, include the true effect of <code>any_girls</code> on the <code>progressive_vote</code> is 0 or 1 in each case, respectively.</p>
<blockquote class="blockquote">
<p>This is correct: each calculated confidence interval either includes the true value or not. Us knowing whether the true value is covered or not does not affect the probability of the true value being covered by the calculated confidence interval.</p>
</blockquote>
<div style="page-break-after: always;"></div>
</section>
<section id="task-3-marginal-effects-plots" class="level2">
<h2 class="anchored" data-anchor-id="task-3-marginal-effects-plots">Task 3: Marginal Effects Plots</h2>
<p>Now we will move to constructing a marginal effect plot for our main variable of interest, <code>any_girls</code>.</p>
<p>3.1. You may see different versions of marginal effects plots: sometimes, marginal effect plots show the values of the coefficient depending on the values of the main predictor directly. Would such a plot be informative in our case? Why (not)?</p>
<blockquote class="blockquote">
<p>Such a plot will not be very informative as the effect is constant across the values of the predictor variable. The estimated effect of the variable is equal to 0.108 and does not depend on the values of any other variable. The same information would be available to us when Here is how such a plot would look like:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: me-plot</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># generate the marginal effects plot data </span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>cdat <span class="ot">&lt;-</span> margins<span class="sc">::</span><span class="fu">cplot</span>(m3, <span class="co"># model object </span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"any_girls"</span>, <span class="co"># variable name </span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">what =</span> <span class="st">"effect"</span>, <span class="co"># type of plot </span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">draw =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(xvals <span class="sc">%in%</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>) <span class="co"># only select the 0 &amp; 1 values </span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cdat, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">if_else</span>(xvals <span class="sc">==</span> <span class="dv">0</span>, <span class="st">"No"</span>, <span class="st">"Yes"</span>))) <span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">y =</span> yvals, <span class="at">ymin =</span> lower,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>                      <span class="at">ymax =</span> upper)) <span class="sc">+</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Having Daughters"</span>,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="fu">expression</span>(<span class="st">"Marginal Effect of Having Daughters: "</span> <span class="sc">*</span> beta[<span class="dv">1</span>]),</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Marginal Effects Plot for Linear Model"</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Mean and 95% confidence intervals"</span>) <span class="sc">+</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span><span class="fl">0.1</span>, <span class="fl">0.5</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-problem-set_files/figure-html/me-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>3.2. Construct the plot with the <em>fitted values</em> over the different values of the predictor variable <code>any_girls</code>. To isolate the effect of <code>any_girls</code>, set all other variables used in the model to a constant, meaningful, existing in the data, value.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-me</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "The Effect of Having at Least One Daughter on Progressive Voting: Average Case"</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: "center"</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">any_girls =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">woman =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>woman), </span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>age),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">catholic =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>catholic),</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">asian =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>asian),</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">african =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>african),</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">hispanic =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>hispanic),</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">republican =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>republican),</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">kids =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>kids)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate CIs for expected values </span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>ci_90 <span class="ot">&lt;-</span> <span class="fu">predict</span>(m3,</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>                 <span class="at">newdata =</span> new_data,</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>                 <span class="at">level =</span> <span class="fl">0.9</span>,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>                 <span class="at">interval =</span> <span class="st">"c"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="st">"0.9"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(new_data)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>ci_95 <span class="ot">&lt;-</span> <span class="fu">predict</span>(m3,</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>                 <span class="at">newdata =</span> new_data,</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>                 <span class="at">level =</span> <span class="fl">0.95</span>,</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>                 <span class="at">interval =</span> <span class="st">"c"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="st">"0.95"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(new_data)</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(ci_90, ci_95) <span class="sc">%&gt;%</span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> fit,</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="fu">factor</span>(any_girls),</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="fu">factor</span>(any_girls)</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">xmin =</span> lwr,</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">xmax =</span> upr,</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> level</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> broom<span class="sc">::</span><span class="fu">augment</span>(m3),</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> .fitted),</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.1</span>,</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">2.5</span>,</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span></span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">direction =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No daughters"</span>, <span class="st">"At least one</span><span class="sc">\n</span><span class="st">daughter"</span>)) <span class="sc">+</span></span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linewidth_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"none"</span>,</span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fu">guide_legend</span>(<span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">size =</span> .<span class="dv">5</span>)),</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fu">guide_legend</span>(<span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">linewidth =</span> <span class="dv">0</span>))</span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Proportion of Feminist Rulings"</span>,</span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">""</span>,</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="st">"Confidence level:"</span>,</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: Glynn &amp; Sen (2015)"</span>,</span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="st">""</span>,</span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"The Effect of Having at Least One Daughter on Progressive Voting"</span>,</span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Sample: U.S. Courts of Appeals Judges, 1996-2002, Gender-Related Cases"</span></span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> scales<span class="sc">::</span><span class="fu">pretty_breaks</span>(), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title.position =</span> <span class="st">"plot"</span>)</span>
<span id="cb5-73"><a href="#cb5-73" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-me" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-problem-set_files/figure-html/fig-me-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: The Effect of Having at Least One Daughter on Progressive Voting: Average Case</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>3.3. Interpret the plot in 2-3 sentences.</p>
<blockquote class="blockquote">
<p>This plot shows us the expected shares of progressive votes for a typical judge (all other variables were set to median in the data) depending on whether they have at least one daughter or not. When having no daughters, the expected proportion of feminist rulings is on average, 28.7 percentage points, but ranges from 19 to 38 percentage points based on the 90% confidence interval. The expected share of feminist votes when having a daughter or more is 39.5 percentage points (33.1 to 45.8 with 90% confidence). This is in line with our expectation that having at least one daughter is associated with an increase in feminst voting for judges.</p>
</blockquote>
<p>3.4. Can we, theoretically, observe values above 1 or below 0 for the <em>Proportion of Feminist Rulings</em>? Why do the confidence intervals still include these values?</p>
<blockquote class="blockquote">
<p>The <em>dependent variable</em>, the proportion by definition ranges from 0 to 1. However, when we are using a linear model, which assumes unbounded dependent variable (i.e.&nbsp;any value of the DV is possible), we may end up in a situation where the point estimates and/or the confidence intervals include values lower than 0 or larger than 1. This is the result of the DV variable being modeled as unbounded. &nbsp;In this case, for example, we have very few cases with Asian judges, hence the uncertainty for expected values for this group could be very large, and CIs for the expected proportion go beyond the 0 and 1. Using a different modelling approach could allow us to ensure that the predictions are bounded to certain values only. &nbsp;At the same time, the <em>effects</em>, i.e.&nbsp;the coefficients and their estimates, are not restricted in most models, and there is no limitation for the CIs for coefficients.</p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-me-asian</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "The Effect of Having at Least One Daughter on Progressive Voting: Asian Judge"</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: "center"</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">any_girls =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">woman =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>woman), </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>age),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">catholic =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>catholic),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">asian =</span> <span class="dv">1</span>,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">african =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>african),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">hispanic =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>hispanic),</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">republican =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>republican),</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">kids =</span> <span class="fu">median</span>(m3<span class="sc">$</span>model<span class="sc">$</span>kids)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate CIs for expected values </span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>ci_90 <span class="ot">&lt;-</span> <span class="fu">predict</span>(m3,</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>                 <span class="at">newdata =</span> new_data,</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>                 <span class="at">level =</span> <span class="fl">0.9</span>,</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>                 <span class="at">interval =</span> <span class="st">"c"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="st">"0.9"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(new_data)</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>ci_95 <span class="ot">&lt;-</span> <span class="fu">predict</span>(m3,</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>                 <span class="at">newdata =</span> new_data,</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>                 <span class="at">level =</span> <span class="fl">0.95</span>,</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>                 <span class="at">interval =</span> <span class="st">"c"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="st">"0.95"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(new_data)</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(ci_90, ci_95) <span class="sc">%&gt;%</span></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> fit,</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="fu">factor</span>(any_girls),</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="fu">factor</span>(any_girls)</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">xmin =</span> lwr,</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">xmax =</span> upr,</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> level</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(</span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> broom<span class="sc">::</span><span class="fu">augment</span>(m3),</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> .fitted),</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.1</span>,</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">2.5</span>,</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span></span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">direction =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No daughters"</span>, <span class="st">"At least one</span><span class="sc">\n</span><span class="st">daughter"</span>)) <span class="sc">+</span></span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linewidth_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(</span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"none"</span>,</span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fu">guide_legend</span>(<span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">size =</span> .<span class="dv">5</span>)),</span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fu">guide_legend</span>(<span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">linewidth =</span> <span class="dv">0</span>))</span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Proportion of Feminist Rulings"</span>,</span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">""</span>,</span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="st">"Confidence level:"</span>,</span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: Glynn &amp; Sen (2015)"</span>,</span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="st">""</span>,</span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"The Effect of Having at Least One Daughter on Progressive Voting"</span>,</span>
<span id="cb6-68"><a href="#cb6-68" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Sample: U.S. Courts of Appeals Judges, 1996-2002, Gender-Related Cases"</span></span>
<span id="cb6-69"><a href="#cb6-69" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-70"><a href="#cb6-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> scales<span class="sc">::</span><span class="fu">pretty_breaks</span>()) <span class="sc">+</span></span>
<span id="cb6-71"><a href="#cb6-71" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb6-72"><a href="#cb6-72" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title.position =</span> <span class="st">"plot"</span>)</span>
<span id="cb6-73"><a href="#cb6-73" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-me-asian" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-problem-set_files/figure-html/fig-me-asian-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: The Effect of Having at Least One Daughter on Progressive Voting: Asian Judge</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="task-4-quarto-chunk-options" class="level2">
<h2 class="anchored" data-anchor-id="task-4-quarto-chunk-options">Task 4: Quarto Chunk Options</h2>
<p>The chunks in this (and other quarto documents) contain so-called chunk options (<code>#|</code>) that control things like whether we execute the chunk or not, whether we include the source code or only the chunk output in the final document, and many other things. In this task you will need to add one or two of such options to the chunks above. Some of the most basic chunk options are:</p>
<table class="table">
<colgroup>
<col style="width: 23%">
<col style="width: 76%">
</colgroup>
<thead>
<tr class="header">
<th>Option</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>eval</code></td>
<td>Evaluate the code chunk (if <code>false</code>, just echos the code into the output).</td>
</tr>
<tr class="even">
<td><code>echo</code></td>
<td>Include the source code in output</td>
</tr>
<tr class="odd">
<td><code>output</code></td>
<td>Include the results of executing the code in the output (<code>true</code>, <code>false</code>, or <code>asis</code> to indicate that the output is raw markdown and should not have any of Quarto’s standard enclosing markdown).</td>
</tr>
<tr class="even">
<td><code>warning</code></td>
<td>Include warnings in the output.</td>
</tr>
<tr class="odd">
<td><code>error</code></td>
<td>Include errors in the output (note that this implies that errors executing code will not halt processing of the document).</td>
</tr>
<tr class="even">
<td><code>include</code></td>
<td>Catch all for preventing any output (code or results) from being included (e.g.&nbsp;<code>include: false</code> suppresses all output from the code block).</td>
</tr>
</tbody>
</table>
<p>You can find many more of them here: https://quarto.org/docs/reference/cells/cells-knitr.html.</p>
<p>4.1. In academic papers, people often put figure captions in the text rather than on the plot directly. In the chunk with label <code>fig-me</code>, adjust the <code>fig-cap</code> option to specify a meaningful title for the plot.</p>
<p>4.2. Add meaningful labels to all other chucks. The labels must be unique!</p>
<p>4.3. Using chunk options, hide all the output of the <code>setup</code> chunk as well as the source code.</p>
<p>4.4. In the <code>regression-table</code>, make sure the code is executed when rendering the file. Also, hide the source code so that only the output (i.e.&nbsp;the table) is shown in the rendered document.</p>
</section>
<section id="task-5-knitting-and-formatting" class="level2">
<h2 class="anchored" data-anchor-id="task-5-knitting-and-formatting">Task 5: Knitting and Formatting</h2>
<p>Please knit your file to PDF. Make sure that all code lines are visible (there are no hanging lines), and that your code is well-styled (running <code>styler::style_dir()</code> in the console should do the styling automatically for you). Upload the latest version of the project (primarily the <code>qmd</code> file) to the repo.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Content <i class="fa-brands fa-creative-commons" aria-hidden="true"></i> 2023 by <a href="https://www.sowi.uni-mannheim.de/gschwend/team/postdocs-and-doctoral-students/viktoriia-semenova/">Viktoriia Semenova</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-by" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-nc" aria-hidden="true"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></div>   
    <div class="nav-footer-right">Made with <i class="fa-solid fa-heart" aria-hidden="true"></i>, <a href="https://github.com/"><i class="fa-brands fa-github" aria-hidden="true"></i></a>, <a href="https://posit.co/"><i class="fa-brands fa-r-project" aria-hidden="true"></i></a> and <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>