<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Learning to use data and statistics to explore the social, political, and economic world">

<title>R for Data Analysis - Problem Set 10: Suggested Solutions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="..//files/icon-512.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="R for Data Analysis - Problem Set 10: Suggested Solutions">
<meta property="og:description" content="We will work with the data from the following article and try to replicate the analysis that the author conducted there:">
<meta property="og:image" content="https://r4da.netlify.app/files/icon-512.png">
<meta property="og:site-name" content="R for Data Analysis">
<meta property="og:locale" content="en_US">
<meta property="og:image:height" content="512">
<meta property="og:image:width" content="512">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">R for Data Analysis</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html">
 <span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html">
 <span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../material/index.html">
 <span class="menu-text">Course Material</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resource/index.html">
 <span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../s23/index.html">
 <span class="menu-text">Spring 2023</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/r4da-f23"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://rstudio.cloud"><i class="bi bi-cloud-fill" role="img" aria-label="RStudio.cloud">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#dataset" id="toc-dataset" class="nav-link active" data-scroll-target="#dataset">Dataset</a></li>
  <li><a href="#task-1-dag" id="toc-task-1-dag" class="nav-link" data-scroll-target="#task-1-dag">Task 1: DAG</a></li>
  <li><a href="#task-2-explore-the-dataset" id="toc-task-2-explore-the-dataset" class="nav-link" data-scroll-target="#task-2-explore-the-dataset">Task 2: Explore the Dataset</a></li>
  <li><a href="#task-3-exact-matching" id="toc-task-3-exact-matching" class="nav-link" data-scroll-target="#task-3-exact-matching">Task 3: Exact Matching</a></li>
  <li><a href="#task-4-nearest-neghbor-matching" id="toc-task-4-nearest-neghbor-matching" class="nav-link" data-scroll-target="#task-4-nearest-neghbor-matching">Task 4: Nearest Neghbor Matching</a></li>
  <li><a href="#task-5-estimation-on-matched-datasets" id="toc-task-5-estimation-on-matched-datasets" class="nav-link" data-scroll-target="#task-5-estimation-on-matched-datasets">Task 5: Estimation on Matched Datasets</a></li>
  <li><a href="#task-6-inverse-probability-weighting" id="toc-task-6-inverse-probability-weighting" class="nav-link" data-scroll-target="#task-6-inverse-probability-weighting">Task 6: Inverse Probability Weighting</a></li>
  <li><a href="#optional-task-7-matching-by-hand" id="toc-optional-task-7-matching-by-hand" class="nav-link" data-scroll-target="#optional-task-7-matching-by-hand">(Optional) Task 7: Matching by Hand</a>
  <ul class="collapse">
  <li><a href="#exact-matching" id="toc-exact-matching" class="nav-link" data-scroll-target="#exact-matching">Exact Matching</a></li>
  <li><a href="#cem" id="toc-cem" class="nav-link" data-scroll-target="#cem">CEM</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Problem Set 10: Suggested Solutions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<p>We will work with the data from the following article and try to replicate the analysis that the author conducted there:</p>
<blockquote class="blockquote">
<p>Broockman, David E. 2013. “Black Politicians Are More Intrinsically Motivated to Advance Blacks’ Interests: A Field Experiment Manipulating Political Incentives.” <em>American Journal of Political Science</em> 57 (3): 521–36.</p>
</blockquote>
<p>Here is the abstract from the study:</p>
<blockquote class="blockquote">
<p>Why are politicians more likely to advance the interests of those of their race? I present a field experiment demonstrating that black politicians are more intrinsically motivated to advance blacks’ interests than are their counterparts. Guided by elite interviews, I emailed 6,928 U.S. state legislators from a putatively black alias asking for help signing up for state unemployment benefits. Crucially, I varied the legislators’ political incentive to respond by randomizing whether the sender purported to live within or far from each legislator’s district. While nonblack legislators were markedly less likely to respond when their political incentives to do so were diminished, black legislators typically continued to respond even when doing so promised little political reward. Black legislators thus appear substantially more intrinsically motivated to advance blacks’ interests. As political decision making is often difficult for voters to observe, intrinsically motivated descriptive representatives play a crucial role in advancing minorities’ political interests.</p>
</blockquote>
<table class="table">
<colgroup>
<col style="width: 27%">
<col style="width: 72%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>leg_black</code></td>
<td>Legislator receiving email is Black</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>treat_out</code></td>
<td>Email is from out-of-district</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>responded</code></td>
<td>Legislator responded to email</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>totalpop</code></td>
<td>District population</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>medianhhincom</code></td>
<td>District median household income</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>black_medianhh</code></td>
<td>District median household income among Black people</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>white_medianhh</code></td>
<td>District median household income among White people</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>blackpercent</code></td>
<td>Percentage of district that is Black</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>statessquireindex</code></td>
<td>State’s Squire index</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>nonblacknonwhite</code></td>
<td>Legislator receiving email is neither Black nor White</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>urbanpercent</code></td>
<td>Percentage of district that is urban</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>leg_senator</code></td>
<td>Legislator receiving email is a senator</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>leg_democrat</code></td>
<td>Legislator receiving email is in the Democratic party</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>south</code></td>
<td>Legislator receiving email is in the Southern United States</td>
</tr>
</tbody>
</table>
</section>
<section id="task-1-dag" class="level2">
<h2 class="anchored" data-anchor-id="task-1-dag">Task 1: DAG</h2>
<blockquote class="blockquote">
<p>Normally in (field) experiments, the variable(s) manipulated/randomized by researchers is(are) called the <em>treatment</em> variable(s). Here, we will be referring to treatment variables in the context of matching, i.e.&nbsp;the predictor that is not randomly distributed but for which we would like to mimic the randomization. In other words, the variables which we are matching on.</p>
</blockquote>
<p>Below you can find a DAG that depicts the relationship between the “treatment” variable, <code>leg_black</code>, and the <code>responded</code>, the outcome variable as well as number of confounders to this relationship. The field experiment, however, included sending emails to legislators, randomizing between the messages from in- and out-of-district. Add this variable to the DAG. You can adapt the DAG below or add the one made with <code>daggify.net</code>.</p>
<div class="cell" data-fig-width="6" data-fig-height="4" data-out-width="100%">
<div class="cell-output-display">
<div>
<p>
<svg width="576" height="384" viewbox="0.00 0.00 500.39 188.00" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 184)">
<title>
D
</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-184 496.39,-184 496.39,4 -4,4"></polygon> <!-- a --> <g id="node1" class="node">
<title>
a
</title>
<ellipse fill="none" stroke="black" cx="194.29" cy="-90" rx="75.25" ry="18"></ellipse> <text text-anchor="middle" x="194.29" y="-85.8" font-family="Times,serif" font-size="14.00">Black Legislator</text> </g> <!-- b --> <g id="node2" class="node">
<title>
b
</title>
<ellipse fill="none" stroke="black" cx="371.29" cy="-90" rx="83.41" ry="18"></ellipse> <text text-anchor="middle" x="371.29" y="-85.8" font-family="Times,serif" font-size="14.00">Response to Email</text> </g> <!-- a&#45;&gt;b --> <g id="edge1" class="edge">
<title>
a-&gt;b
</title>
<path fill="none" stroke="black" d="M269.65,-90C272.26,-90 274.86,-90 277.47,-90"></path> <polygon fill="black" stroke="black" points="287.52,-90 277.52,-94.5 282.52,-90 277.52,-90 277.52,-90 277.52,-90 282.52,-90 277.52,-85.5 287.52,-90 287.52,-90"></polygon> </g> <!-- c --> <g id="node3" class="node">
<title>
c
</title>
<ellipse fill="none" stroke="black" cx="103.29" cy="-162" rx="103.07" ry="18"></ellipse> <text text-anchor="middle" x="103.29" y="-157.8" font-family="Times,serif" font-size="14.00">District Median Income</text> </g> <!-- c&#45;&gt;a --> <g id="edge2" class="edge">
<title>
c-&gt;a
</title>
<path fill="none" stroke="black" d="M125.32,-144.05C137.22,-134.89 152.09,-123.46 164.96,-113.56"></path> <polygon fill="black" stroke="black" points="173.09,-107.31 167.91,-116.97 169.12,-110.36 165.16,-113.4 165.16,-113.4 165.16,-113.4 169.12,-110.36 162.42,-109.84 173.09,-107.31 173.09,-107.31"></polygon> </g> <!-- c&#45;&gt;b --> <g id="edge3" class="edge">
<title>
c-&gt;b
</title>
<path fill="none" stroke="black" d="M158.17,-146.67C202.39,-135.11 264.54,-118.88 310.31,-106.93"></path> <polygon fill="black" stroke="black" points="320.11,-104.37 311.57,-111.25 315.27,-105.63 310.44,-106.89 310.44,-106.89 310.44,-106.89 315.27,-105.63 309.3,-102.54 320.11,-104.37 320.11,-104.37"></polygon> </g> <!-- d --> <g id="node4" class="node">
<title>
d
</title>
<ellipse fill="none" stroke="black" cx="300.29" cy="-162" rx="75.3" ry="18"></ellipse> <text text-anchor="middle" x="300.29" y="-157.8" font-family="Times,serif" font-size="14.00">District % Black</text> </g> <!-- d&#45;&gt;a --> <g id="edge4" class="edge">
<title>
d-&gt;a
</title>
<path fill="none" stroke="black" d="M275.97,-144.94C261.53,-135.4 243.02,-123.18 227.28,-112.79"></path> <polygon fill="black" stroke="black" points="218.86,-107.23 229.68,-108.98 223.03,-109.98 227.2,-112.74 227.2,-112.74 227.2,-112.74 223.03,-109.98 224.72,-116.49 218.86,-107.23 218.86,-107.23"></polygon> </g> <!-- d&#45;&gt;b --> <g id="edge5" class="edge">
<title>
d-&gt;b
</title>
<path fill="none" stroke="black" d="M317.11,-144.41C326,-135.65 337.07,-124.73 346.89,-115.06"></path> <polygon fill="black" stroke="black" points="354.09,-107.96 350.13,-118.18 350.53,-111.47 346.97,-114.98 346.97,-114.98 346.97,-114.98 350.53,-111.47 343.81,-111.77 354.09,-107.96 354.09,-107.96"></polygon> </g> <!-- e --> <g id="node5" class="node">
<title>
e
</title>
<ellipse fill="none" stroke="black" cx="443.29" cy="-162" rx="49.22" ry="18"></ellipse> <text text-anchor="middle" x="443.29" y="-157.8" font-family="Times,serif" font-size="14.00">Democrat</text> </g> <!-- e&#45;&gt;a --> <g id="edge6" class="edge">
<title>
e-&gt;a
</title>
<path fill="none" stroke="black" d="M405.85,-150.16C398.69,-148.1 391.26,-145.98 384.29,-144 339.68,-131.35 289.1,-117.26 251.36,-106.78"></path> <polygon fill="black" stroke="black" points="241.56,-104.07 252.4,-102.4 246.38,-105.4 251.19,-106.74 251.19,-106.74 251.19,-106.74 246.38,-105.4 249.99,-111.07 241.56,-104.07 241.56,-104.07"></polygon> </g> <!-- e&#45;&gt;b --> <g id="edge7" class="edge">
<title>
e-&gt;b
</title>
<path fill="none" stroke="black" d="M426.59,-144.76C417.45,-135.88 405.96,-124.71 395.82,-114.85"></path> <polygon fill="black" stroke="black" points="388.4,-107.63 398.7,-111.38 391.98,-111.12 395.57,-114.6 395.57,-114.6 395.57,-114.6 391.98,-111.12 392.43,-117.83 388.4,-107.63 388.4,-107.63"></polygon> </g> <!-- f --> <g id="node6" class="node">
<title>
f
</title>
<ellipse fill="none" stroke="black" cx="371.29" cy="-18" rx="92.09" ry="18"></ellipse> <text text-anchor="middle" x="371.29" y="-13.8" font-family="Times,serif" font-size="14.00">Out-of-district Email</text> </g> <!-- f&#45;&gt;b --> <g id="edge8" class="edge">
<title>
f-&gt;b
</title>
<path fill="none" stroke="black" d="M371.29,-36.1C371.29,-43.79 371.29,-53.05 371.29,-61.67"></path> <polygon fill="black" stroke="black" points="371.29,-71.7 366.79,-61.7 371.29,-66.7 371.29,-61.7 371.29,-61.7 371.29,-61.7 371.29,-66.7 375.79,-61.7 371.29,-71.7 371.29,-71.7"></polygon> </g> </g>
</svg>
</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>The fact that email was in/out-of-district was randomly assigned by the researcher, so it does not open any backdoors.</p>
</blockquote>
</section>
<section id="task-2-explore-the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="task-2-explore-the-dataset">Task 2: Explore the Dataset</h2>
<ol type="1">
<li>Generate a plot representing the data on legislator response rates (<code>responded</code>) for black vs.&nbsp;non-black legislators over the type of emails they received. Comment on the plot in 2-3 sentences.</li>
</ol>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Bar Plot I</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Bar Plot II</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Stacked Bar Plot I</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">Stacked Bar Plot II</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false">Raw Data</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>black_politicians <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(leg_black, treat_out, responded) <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">if_else</span>(treat_out <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Out-of-district</span><span class="sc">\n</span><span class="st">Email"</span>, <span class="st">"In-district</span><span class="sc">\n</span><span class="st">Email"</span>),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> n,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="fu">if_else</span>(responded <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>) <span class="sc">%&gt;%</span> <span class="fu">as_factor</span>() <span class="sc">%&gt;%</span> <span class="fu">fct_rev</span>()</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(), <span class="at">color =</span> <span class="st">"white"</span>, ) <span class="sc">+</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> <span class="fu">if_else</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Black Legislator"</span>, <span class="st">"Non-Black Legislator"</span>)) <span class="sc">+</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Legislator Responded"</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">""</span>,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">""</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="figures/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>black_politicians <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(leg_black, treat_out, responded) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">if_else</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Black</span><span class="sc">\n</span><span class="st">Legislators"</span>, <span class="st">"Non-Black</span><span class="sc">\n</span><span class="st">Legislators"</span>),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> n,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="fu">if_else</span>(responded <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>) <span class="sc">%&gt;%</span> <span class="fu">as_factor</span>() <span class="sc">%&gt;%</span> <span class="fu">fct_rev</span>()</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(), <span class="at">color =</span> <span class="st">"white"</span>, ) <span class="sc">+</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> <span class="fu">if_else</span>(treat_out <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Out-of-district Email"</span>, <span class="st">"In-district Email"</span>)) <span class="sc">+</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Legislator Responded"</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">""</span>,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">""</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="figures/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>black_politicians <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(leg_black, treat_out, responded) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">if_else</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Black</span><span class="sc">\n</span><span class="st">Legislators"</span>, <span class="st">"Non-Black</span><span class="sc">\n</span><span class="st">Legislators"</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> n,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="fu">if_else</span>(responded <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>) <span class="sc">%&gt;%</span> <span class="fu">as_factor</span>() <span class="sc">%&gt;%</span> <span class="fu">fct_rev</span>()</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">position =</span> <span class="fu">position_stack</span>(), <span class="at">color =</span> <span class="st">"white"</span>, ) <span class="sc">+</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> <span class="fu">if_else</span>(treat_out <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Out-of-district Email"</span>, <span class="st">"In-district Email"</span>)) <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Legislator Responded"</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">""</span>,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">""</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="figures/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>black_politicians <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(leg_black, treat_out, responded) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">if_else</span>(treat_out <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Out-of-district</span><span class="sc">\n</span><span class="st">Email"</span>, <span class="st">"In-district</span><span class="sc">\n</span><span class="st">Email"</span>),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> n,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="fu">if_else</span>(responded <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>) <span class="sc">%&gt;%</span> <span class="fu">as_factor</span>() <span class="sc">%&gt;%</span> <span class="fu">fct_rev</span>()</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">position =</span> <span class="fu">position_stack</span>(), <span class="at">color =</span> <span class="st">"white"</span>, ) <span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> <span class="fu">if_else</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Black Legislator"</span>, <span class="st">"Non-Black Legislator"</span>)) <span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Legislator Responded"</span>,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">""</span>,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">""</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="figures/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  black_politicians <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(responded),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">if_else</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Black</span><span class="sc">\n</span><span class="st">Legislator"</span>, <span class="st">"Non-Black</span><span class="sc">\n</span><span class="st">Legislator"</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="fu">if_else</span>(treat_out <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Out-of-district</span><span class="sc">\n</span><span class="st">Email"</span>, <span class="st">"In-district</span><span class="sc">\n</span><span class="st">Email"</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="fu">if_else</span>(responded <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>) <span class="sc">%&gt;%</span> <span class="fu">as.factor</span>() <span class="sc">%&gt;%</span> <span class="fu">fct_rev</span>()</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">pch =</span> <span class="dv">21</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Legislator Responded"</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">""</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="figures/main-dv-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>From all of these plot (to a varying extent), we can observe a few things: first, there are far more non-black legislators, in general and within both experimental treatment groups. This is evident from all types of plots, although bar plots give us exact numbers, unlike the raw data ones. As for the randomized treatment, <em>in- vs.&nbsp;out-of-district email</em>, stacked bar plots show us clearly that experimental treatment groups were of equal sizes. Coming to the response rates, we can spot that for both black and non-black legislators, the response to in-district email was more likely in comparison to an out-of-district email. However, for black legislators the difference in the response rate between treatment conditions seems to be smaller than for non-black legislators.</p>
</blockquote>
<ol start="2" type="1">
<li>Run a linear regression model to explore if black legislators are more likely to respond to emails from out-of-district vs.&nbsp;in-district ones in comparison to non-black legislators. Control for the legislator party, senator status, South, and other available sociodemographic characteristics for the districts. You can print out the output with <code>summary()</code> for this task. Comment on the findings:</li>
</ol>
<ul>
<li>How responsive were legislators when their political incentives were decreased?</li>
<li>How did the effect of decreasing legislators’ political incentives vary between legislators of different race?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  responded <span class="sc">~</span> leg_black <span class="sc">*</span> treat_out <span class="sc">+</span> nonblacknonwhite <span class="sc">+</span>  black_medianhh <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    white_medianhh <span class="sc">+</span> statessquireindex <span class="sc">+</span>  totalpop <span class="sc">+</span> urbanpercent <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    medianhhincom <span class="sc">+</span> blackpercent <span class="sc">+</span> leg_democrat,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> black_politicians</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = responded ~ leg_black * treat_out + nonblacknonwhite + 
    black_medianhh + white_medianhh + statessquireindex + totalpop + 
    urbanpercent + medianhhincom + blackpercent + leg_democrat, 
    data = black_politicians)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.7482 -0.3711 -0.2445  0.4566  0.8726 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          0.4661291  0.0252500  18.461  &lt; 2e-16 ***
leg_black           -0.1140716  0.0449939  -2.535 0.011263 *  
treat_out           -0.2755611  0.0130894 -21.052  &lt; 2e-16 ***
nonblacknonwhite    -0.0382547  0.0309062  -1.238 0.215854    
black_medianhh      -0.0015864  0.0072346  -0.219 0.826443    
white_medianhh       0.0162761  0.0149473   1.089 0.276247    
statessquireindex    0.4034100  0.0667769   6.041 1.63e-09 ***
totalpop            -0.0016359  0.0007579  -2.159 0.030927 *  
urbanpercent         0.0146757  0.0235744   0.623 0.533620    
medianhhincom        0.0022886  0.0083705   0.273 0.784545    
blackpercent         0.0764460  0.0625127   1.223 0.221424    
leg_democrat        -0.0493432  0.0138265  -3.569 0.000362 ***
leg_black:treat_out  0.1288274  0.0513152   2.511 0.012084 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.473 on 5580 degrees of freedom
Multiple R-squared:  0.08528,   Adjusted R-squared:  0.08331 
F-statistic: 43.35 on 12 and 5580 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>With decreased political incentives, i.e.&nbsp;when an email came outside of the district of the candidate, both types of legislators were less likely to respond: holding all else constant, for non-black candidates the probability decreased by on average 0.28 points, while for black legislators the decrease was not as strong, on average 0.15 points. Technically, the positive sign of the interaction term showed us that the negative effect of treatment was mitigated by race to a certain extent.</p>
</blockquote>
<ol start="3" type="1">
<li>Why could the non-random distribution of race variable be problematic for the analysis? How does matching address this issue?</li>
</ol>
<blockquote class="blockquote">
<p>The race of the elected candidate is not randomly distributed across districts. The fact that many nonblack legislators represent districts where blacks would be unlikely to get elected and/or would be unlikely to run thus constitutes a selection bias. Legislators from districts with modest black representation might have been suspicious of a letter from a putatively black individual or less knowledgeable about unemployment benefits, hence making them less likely to respond to such an email. Matching potentially removes this variation between districts by ensuring that the districts are comparable to one another based on a set of matching variables. Ideally, these matching variables should account for potential differences in response rates.</p>
</blockquote>
</section>
<section id="task-3-exact-matching" class="level2">
<h2 class="anchored" data-anchor-id="task-3-exact-matching">Task 3: Exact Matching</h2>
<ol type="1">
<li>When using matching for preprocessing, we need to disregard the dependent variable, thus we will only be working with treatment and matching variables at this stage. Look at the plot below, which shows the data across all three matching variables and points are colored by the values of the treatment variable. What do you observe regarding the distribution of the treatment variable <code>leg_black</code> across the three matching variables?</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="10-problem-set_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>There are many more blacks among Democratic in comparison to Republican legislators. We are also much more likely to see a black candidate where the share of black legislators is higher, and median household income is lower. We can also see that there are many cases where for a combination of matching variables, only districts with one kind of race exist. This shows that there is some overlap between the joint distributions of the variables, but the common support is not very large. Hence finding, say, an exact match would not be easy.</p>
</blockquote>
<ol start="2" type="1">
<li>Apply the exact matching algorithm to the dataset, and match based on the values of legislator race variable. Store the dataset in <code>exact_df</code> object.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># matchit object </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>exact <span class="ot">&lt;-</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">matchit</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    leg_black <span class="sc">~</span> medianhhincom <span class="sc">+</span> blackpercent <span class="sc">+</span> leg_democrat,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> black_politicians <span class="sc">%&gt;%</span> </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">arrange</span>(blackpercent),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"exact"</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co"># resulting dataset </span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>exact_df <span class="ot">&lt;-</span> exact <span class="sc">%&gt;%</span> <span class="fu">match.data</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>Explore the visualized distribution over matching variables for the matched dataset. The size of the points represents the ratio between the number of treated units to untreated ones within each unique combination of values, subgroup. What do you observe from this plot:</li>
</ol>
<ul>
<li>what changes in the distribution of the variables in comparison to the raw data?</li>
<li>to what extent do the distributions within treated and untreated groups overlap, in comparison to raw data?</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  exact_df <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(subclass) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">if_else</span>(</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>      leg_black <span class="sc">==</span> <span class="dv">1</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>      <span class="dv">1</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">leg_black =</span> <span class="fu">if_else</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Black"</span>, <span class="st">"Non-black"</span>) <span class="sc">%&gt;%</span> <span class="fu">as_factor</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(leg_black, n),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    medianhhincom,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    blackpercent,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="fu">factor</span>(leg_black),</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> n</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.7</span>,</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">pch =</span> <span class="dv">21</span>,</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"grey80"</span>,</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.1</span>,</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">height =</span> <span class="fl">0.01</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(leg_party)) <span class="sc">+</span></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Legislator Race"</span>,</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="st">"Units in Subgroup"</span>,</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Share of Black Voters in District"</span>,</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Median Household Income in District"</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.box =</span> <span class="st">"vertical"</span></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="10-problem-set_files/figure-html/exact-matching-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>By definition of the procedure, we are looking for exact matches for combinations of matching variables between treated and untreated units (<code>geom_jitter</code> adds a bit of random noise to help with overlap), hence there is perfect overlap between the distributions. In comparison to raw data, we also have much fewer points. There are no exact matches for Republican legislators, but among Democrats, we could find 68 observations: 27 of them are black and 41 are non-black. For some combinations of matching variables, there was more than one matched non-black legislator per one black legislator. On the plot, these are subgroups with a big purple point and a a few smaller green ones. Also, sometimes there were multiple black legislators with the same combination of values in matching variables matched to one non-black legislator. On the plot, these are subgroups with bigger green points and few green ones.</p>
</blockquote>
<ol start="4" type="1">
<li>What can you say about the covariate balance in this matched dataset? Construct the covariate balance plot if you need to answer this question.</li>
</ol>
<blockquote class="blockquote">
<p>By definition of the procedure, covariate balance is perfect in this case, as the observations match perfectly on the values of matching variables.</p>
</blockquote>
</section>
<section id="task-4-nearest-neghbor-matching" class="level2">
<h2 class="anchored" data-anchor-id="task-4-nearest-neghbor-matching">Task 4: Nearest Neghbor Matching</h2>
<ol type="1">
<li>Let’s try out a different matching algorithm: nearest neighbor matching with Mahalanobis distance. In a few sentences, explain what is the logic underlying this matching algorithm.</li>
</ol>
<blockquote class="blockquote">
<p>Unlike exact matching, this approach quantifies the differences between observations in terms of distance estimated based on the values of matching variables. There are different distance measures one can use, but the Mahalanobis distance accounts for the correlation in the data and allows it to, in essence, not match on highly correlated variables more than once. Computationally, the algorithm does the following: A distance is computed between each treated unit and each control unit, and, one by one, each treated unit is assigned a control unit as a match. When matching without replacement, the matched untreated unit can no longer be matched to other observations. The matching is thus “greedy” in the sense that there is no action taken to optimize an overall criterion; each match is selected without considering the other matches that may occur subsequently. It is thus fast but sensitive to the order of samples (unless sampled with replacement, in which case more than one control observation can be matched to a treated unit). Optimal matching, another type of matching, on the other hand, minimizes the <em>total</em> distance across all pairs, not individual distances, but it also takes longer to work.</p>
</blockquote>
<ol start="2" type="1">
<li>Now implement the algorithm. Explore if the ordering of observations makes a difference when you match <em>without</em> replacement. Compare the original order vs.&nbsp;order by <code>blackpercent</code> (<code>arrange()</code> function can help). Compare the resulting datasets with <code>setdiff()</code> or <code>intersect()</code>.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># matchit object </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>nearest <span class="ot">&lt;-</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">matchit</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    leg_black <span class="sc">~</span> medianhhincom <span class="sc">+</span> blackpercent <span class="sc">+</span> leg_democrat,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> black_politicians,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"nearest"</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">distance =</span> <span class="st">"mahalanobis"</span>, <span class="at">replace =</span> F</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>nearest_ordered <span class="ot">&lt;-</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">matchit</span>(</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    leg_black <span class="sc">~</span> medianhhincom <span class="sc">+</span> blackpercent <span class="sc">+</span> leg_democrat,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> black_politicians <span class="sc">%&gt;%</span> </span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">arrange</span>(blackpercent),</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"nearest"</span>,</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">distance =</span> <span class="st">"mahalanobis"</span>, <span class="at">replace =</span> F</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="co"># resulting dataset </span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>nearest_df <span class="ot">&lt;-</span> nearest <span class="sc">%&gt;%</span> <span class="fu">match.data</span>()</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>nearest_ordered_df <span class="ot">&lt;-</span> nearest_ordered <span class="sc">%&gt;%</span> <span class="fu">match.data</span>()</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a><span class="co"># compare datasets </span></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="co"># nrow() of rows in nearest_df but not in nearest_ordered_df</span></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a><span class="fu">setdiff</span>(nearest_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>subclass),</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>        nearest_ordered_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>subclass)) <span class="sc">%&gt;%</span> <span class="fu">nrow</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nrow() of rows in nearest_df but not in nearest_ordered_df and vica versa</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">symdiff</span>(nearest_ordered_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>subclass),</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>        nearest_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>subclass)) <span class="sc">%&gt;%</span> <span class="fu">nrow</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nrow() of rows in both nearest_df and nearest_ordered_df</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">intersect</span>(nearest_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>subclass),</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>          nearest_ordered_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>subclass)) <span class="sc">%&gt;%</span> <span class="fu">nrow</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 705</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">love.plot</span>(nearest) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Original Order"</span>) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">love.plot</span>(nearest_ordered)  <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ordered by Race"</span>) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_annotation</span>(<span class="at">title =</span> <span class="st">"Covariate Balance"</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_layout</span>(<span class="at">guides =</span> <span class="st">"collect"</span>) <span class="sc">&amp;</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Standardized mean differences and raw mean differences are present in the same plot. 
Use the `stars` argument to distinguish between them and appropriately label the x-axis.
Standardized mean differences and raw mean differences are present in the same plot. 
Use the `stars` argument to distinguish between them and appropriately label the x-axis.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="10-problem-set_files/figure-html/nnm-order-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Because of the order of observations, the datasets differ to some extent. As matching adds a column <code>subclass</code> into the dataset, it needs to be removed from the comparison. As <code>setdiff()</code> shows us, there are 19 observations in the <code>nearest_df</code> that are not in <code>nearest_ordered_df</code> and 18 observations vice versa. There are 705 observations present in both datasets.</p>
</blockquote>
<ol start="3" type="1">
<li>What does covariate balance mean in the context of matching? Which variables would we use to assess covariate balance? E.g., do we need to access balance for main dependent variable, treatment (the variable we used to match on), the matching variables, other variables in the dataset? Why (not)?</li>
</ol>
<blockquote class="blockquote">
<p>Covariate balance is the degree to which the distribution of matching variables is similar across values of the treatment. Balance is a way to assess the quality of the resulting matches. When covariate balance is achieved, the resulting effect estimate is less sensitive to model misspecification and ideally close to the true treatment effect. We need to check covariate balance for the variables we used for matching, but not the main outcome variable as the information about the main outcome should not be affecting the matching process in any way.</p>
</blockquote>
<ol start="4" type="1">
<li>Compare the matched datasets when matching <em>with</em> and <em>without</em> replacement. Which one produces better covariate balance? Why? Generate a covariate balance plot if you need to answer this question.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>nearest_replacement <span class="ot">&lt;-</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">matchit</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    leg_black <span class="sc">~</span> medianhhincom <span class="sc">+</span> blackpercent <span class="sc">+</span> leg_democrat,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> black_politicians,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"nearest"</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">distance =</span> <span class="st">"mahalanobis"</span>, </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">replace =</span> T</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>nearest_replacement_df <span class="ot">&lt;-</span> nearest_replacement <span class="sc">%&gt;%</span> <span class="fu">match.data</span>() </span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="fu">love.plot</span>(nearest) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Without Replacement"</span>) <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">love.plot</span>(nearest_replacement)  <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"With Replacement"</span>) <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_annotation</span>(<span class="at">title =</span> <span class="st">"Covariate Balance"</span>) <span class="sc">+</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_layout</span>(<span class="at">guides =</span> <span class="st">"collect"</span>) <span class="sc">&amp;</span> </span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Standardized mean differences and raw mean differences are present in the same plot. 
Use the `stars` argument to distinguish between them and appropriately label the x-axis.
Standardized mean differences and raw mean differences are present in the same plot. 
Use the `stars` argument to distinguish between them and appropriately label the x-axis.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="10-problem-set_files/figure-html/nnm-replacement-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Matching with replacement results in better covariate balance (i.e.&nbsp;the mean differences are nearly zero for adjusted samples in this case). This is because the algorithm is allowed to find the best match among untreated units, rather than discarding the observations that were already matched to something.</p>
</blockquote>
<ol start="5" type="1">
<li>Explore the <em>distributions</em> of matching variables for all three matching variables. What do you observe on the plots? Comment in 3-4 sentences.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">bal.plot</span>(nearest_replacement, <span class="co"># matchit object</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">var.name =</span> <span class="st">"blackpercent"</span> <span class="co"># name of the variable you are comparing</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">bal.plot</span>(nearest_replacement, <span class="co"># matchit object</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">var.name =</span> <span class="st">"medianhhincom"</span> <span class="co"># name of the variable you are comparing</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">bal.plot</span>(nearest_replacement, <span class="co"># matchit object</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">var.name =</span> <span class="st">"leg_democrat"</span> <span class="co"># name of the variable you are comparing</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">/</span> p2 <span class="sc">/</span> p3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="10-problem-set_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>The plots above show the results of distributional balance for NN matching with replacement. For each of the variables, we observe a strong overlap between the distributions for treated (black legislators) vs.&nbsp;untreated (non-black legislators) units. While the distributions do not overlap perfectly, this is still a significant improvement over the unbalanced dataset. This plot, however, does not show us their <em>joint</em> distributions, evaluating which would be ideal.</p>
</blockquote>
<ol start="6" type="1">
<li>Adapt the code from <code>exact-matching-plot</code> chunk to show the distributions for the dataset with the best covariate balance that you have obtained so far with nearest neighbor matching. What are the differences to the same plot from exact matching? How do you explain them?</li>
</ol>
<blockquote class="blockquote">
<p>The plot shows that we were able to match many more observations than with exact matching. For instance, we now have a few observations where the legislator is Republican. The size of the points in this case corresponds to the weight that is assigned to each of the control units, as it is possible that one control unit is matched to more than one treated unit.</p>
</blockquote>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  nearest_replacement_df <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="sc">-</span>leg_black, weights),</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    medianhhincom,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    blackpercent,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="fu">if_else</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Black"</span>, <span class="st">"Non-black"</span>),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> weights</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.7</span>,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">pch =</span> <span class="dv">21</span>,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"grey80"</span>,</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.1</span>,</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">height =</span> <span class="fl">0.01</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(leg_party)) <span class="sc">+</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Race"</span>,</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="st">"Weights"</span>,</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Share of Black Voters in District"</span>,</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Median Household Income in District"</span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.box =</span> <span class="st">"vertical"</span></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">size =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="10-problem-set_files/figure-html/nnm-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Each treated observation has a weight of 1, while the untreated observations’ weight accounts for how many observations in the treated group it was matched to and is also normalized so that the total share of weights is equal to the number of observations in treated vs.&nbsp;untreated groups.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># number of treated vs. untreated units </span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>nearest_replacement_df <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(leg_black) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  leg_black     n
      &lt;dbl&gt; &lt;int&gt;
1         0   138
2         1   364</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sums of weights </span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>nearest_replacement_df <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(leg_black) <span class="sc">%&gt;%</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">sum</span>(weights)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  leg_black `sum(weights)`
      &lt;dbl&gt;          &lt;dbl&gt;
1         0            138
2         1            364</code></pre>
</div>
</div>
</section>
<section id="task-5-estimation-on-matched-datasets" class="level2">
<h2 class="anchored" data-anchor-id="task-5-estimation-on-matched-datasets">Task 5: Estimation on Matched Datasets</h2>
<p>Finally, let’s move to the estimation part. You will now need to run the regression with the main dependent variable, i.e.&nbsp;whether the legislator responded to the email or not, and estimate the same model as in task 2.</p>
<ol type="1">
<li>Use the matched dataset that provided you with the best covariate balance so far as well as had a reasonable number of observations. Don’t forget to include the <em>weights</em> argument to account for the fact that some untreated units may be in the dataset more than once! Explain your findings. Do the results hold after improving balance between the districts with and without black legislators?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  responded <span class="sc">~</span> leg_black <span class="sc">*</span> treat_out <span class="sc">+</span> nonblacknonwhite <span class="sc">+</span>  black_medianhh <span class="sc">+</span> white_medianhh <span class="sc">+</span> statessquireindex <span class="sc">+</span>  totalpop <span class="sc">+</span> urbanpercent <span class="sc">+</span>    medianhhincom <span class="sc">+</span> blackpercent <span class="sc">+</span> leg_democrat,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> nearest_replacement_df,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> weights</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = responded ~ leg_black * treat_out + nonblacknonwhite + 
    black_medianhh + white_medianhh + statessquireindex + totalpop + 
    urbanpercent + medianhhincom + blackpercent + leg_democrat, 
    data = nearest_replacement_df, weights = weights)

Weighted Residuals:
    Min      1Q  Median      3Q     Max 
-1.1014 -0.3794 -0.1937  0.4745  1.3062 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          0.571025   0.180717   3.160  0.00168 ** 
leg_black           -0.209517   0.068367  -3.065  0.00230 ** 
treat_out           -0.457473   0.081780  -5.594  3.7e-08 ***
nonblacknonwhite    -0.237738   0.261858  -0.908  0.36439    
black_medianhh       0.133707   0.122686   1.090  0.27633    
white_medianhh      -0.086500   0.045322  -1.909  0.05690 .  
statessquireindex    0.171651   0.258290   0.665  0.50664    
totalpop             0.002511   0.003233   0.777  0.43773    
urbanpercent         0.120395   0.093337   1.290  0.19769    
medianhhincom        0.013620   0.047110   0.289  0.77262    
blackpercent         0.073421   0.121160   0.606  0.54481    
leg_democrat        -0.141165   0.154295  -0.915  0.36069    
leg_black:treat_out  0.315802   0.095480   3.308  0.00101 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4673 on 489 degrees of freedom
Multiple R-squared:  0.1087,    Adjusted R-squared:  0.08688 
F-statistic: 4.972 on 12 and 489 DF,  p-value: 8.358e-08</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The original results seem to hold well when replicating the analysis on the matched dataset. Treatment still has a negative effect for both black and non-black legislators, but as before, the effect for black legislators is smaller in size.</p>
</blockquote>
<ol start="2" type="1">
<li>(Optional) Use simulations to present the results and calculate first differences for the relevant scenarios. To save you a bit of time, I provide you with a list of average case scenarios for the control variables that could be passed into the <code>sim_setx()</code> function.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>evs <span class="ot">&lt;-</span> <span class="fu">sim</span>(m2) <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sim_setx</span>(<span class="at">x =</span> <span class="fu">list</span>(</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">leg_black =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">treat_out =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">nonblacknonwhite =</span> <span class="fu">median</span>(black_politicians<span class="sc">$</span>nonblacknonwhite),</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">black_medianhh =</span> <span class="fu">median</span>(black_politicians<span class="sc">$</span>black_medianhh),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">white_medianhh =</span> <span class="fu">median</span>(black_politicians<span class="sc">$</span>white_medianhh),</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">statessquireindex =</span> <span class="fu">median</span>(black_politicians<span class="sc">$</span>statessquireindex),</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">totalpop =</span> <span class="fu">median</span>(black_politicians<span class="sc">$</span>totalpop),</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">urbanpercent =</span> <span class="fu">median</span>(black_politicians<span class="sc">$</span>urbanpercent)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span> </span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transform</span>(<span class="st">`</span><span class="at">FD: black, in vs. out</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">leg_black = 1, treat_out = 0</span><span class="st">`</span> <span class="sc">-</span> </span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>              <span class="st">`</span><span class="at">leg_black = 1, treat_out = 1</span><span class="st">`</span>,</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">FD: non-black, in vs. out</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">leg_black = 0, treat_out = 0</span><span class="st">`</span> <span class="sc">-</span> </span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>              <span class="st">`</span><span class="at">leg_black = 0, treat_out = 1</span><span class="st">`</span>,</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">FD: out, black vs. non-black</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">leg_black = 1, treat_out = 1</span><span class="st">`</span> <span class="sc">-</span> </span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>              <span class="st">`</span><span class="at">leg_black = 0, treat_out = 1</span><span class="st">`</span>,</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">FD: in, black vs. non-black</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">leg_black = 1, treat_out = 0</span><span class="st">`</span> <span class="sc">-</span> </span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>              <span class="st">`</span><span class="at">leg_black = 0, treat_out = 0</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transform</span>(<span class="st">`</span><span class="at">FD: black vs. non-black, </span><span class="sc">\n</span><span class="at">in vs. out</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">FD: black, in vs. out</span><span class="st">`</span> <span class="sc">-</span> <span class="st">`</span><span class="at">FD: non-black, in vs. out</span><span class="st">`</span>)</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(evs) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="10-problem-set_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Plots depict the distributions of expected probabilities to respond for an average legislator with 95% confidence intervals as well as the distributions of first differences between all relevant combinations of scenarios. We can conclude that for out-of-district emails, there is no significant difference between black vs.&nbsp;non-black legislators’ response rates (plot <em>FD: out, black vs.&nbsp;non-black</em>). For in-district emails, black legislators have a lower probability to respond (-0.2095 on average, plot <em>FD: in, black vs.&nbsp;non-black</em>). When we compare the effect of race within treatment conditions, both black and non-black legislators are more likely to respond to in-district emails, but for black legislators, the difference in probabilities to respond between in- vs.&nbsp;out-of-district emails is smaller: 0.14 vs.&nbsp;0.45. Moreover, the difference between these differences is statistically significant, too.</p>
</blockquote>
</section>
<section id="task-6-inverse-probability-weighting" class="level2">
<h2 class="anchored" data-anchor-id="task-6-inverse-probability-weighting">Task 6: Inverse Probability Weighting</h2>
<p>Recall that the last method we talked about was related to propensity scores.</p>
<ol type="1">
<li>What does a propensity score for each observation depict?</li>
</ol>
<blockquote class="blockquote">
<p>It depicts the probability of each observation receiving treatment conditional on the values of matching variables/covariates.</p>
</blockquote>
<ol start="2" type="1">
<li>In a simplified version of the DAG (without the in-district vs.&nbsp;out-of-district orogins of email), propensity score can be depicted as follows. Explain in a few sentences how accounting for it impacts the open paths between the <em>Race</em> and <em>Response</em> variables.</li>
</ol>
<blockquote class="blockquote">
<p>Answer goes here</p>
</blockquote>
<div class="cell" data-fig-width="6" data-fig-height="4" data-out-width="100%">
<div class="cell-output-display">
<div>
<p>
<svg width="576" height="384" viewbox="0.00 0.00 511.74 188.00" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 184)">
<title>
D
</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-184 507.74,-184 507.74,4 -4,4"></polygon> <!-- a --> <g id="node1" class="node">
<title>
a
</title>
<ellipse fill="none" stroke="black" cx="243.29" cy="-18" rx="75.25" ry="18"></ellipse> <text text-anchor="middle" x="243.29" y="-13.8" font-family="Times,serif" font-size="14.00">Black Legislator</text> </g> <!-- b --> <g id="node2" class="node">
<title>
b
</title>
<ellipse fill="none" stroke="black" cx="420.29" cy="-18" rx="83.41" ry="18"></ellipse> <text text-anchor="middle" x="420.29" y="-13.8" font-family="Times,serif" font-size="14.00">Response to Email</text> </g> <!-- a&#45;&gt;b --> <g id="edge1" class="edge">
<title>
a-&gt;b
</title>
<path fill="none" stroke="black" d="M318.65,-18C321.26,-18 323.86,-18 326.47,-18"></path> <polygon fill="black" stroke="black" points="336.52,-18 326.52,-22.5 331.52,-18 326.52,-18 326.52,-18 326.52,-18 331.52,-18 326.52,-13.5 336.52,-18 336.52,-18"></polygon> </g> <!-- d --> <g id="node3" class="node">
<title>
d
</title>
<ellipse fill="none" stroke="black" cx="103.29" cy="-162" rx="103.07" ry="18"></ellipse> <text text-anchor="middle" x="103.29" y="-157.8" font-family="Times,serif" font-size="14.00">District Median Income</text> </g> <!-- d&#45;&gt;b --> <g id="edge5" class="edge">
<title>
d-&gt;b
</title>
<path fill="none" stroke="black" d="M110.37,-143.95C119.78,-123.49 138.42,-89.74 165.29,-72 173.07,-66.86 276.74,-46.33 349.47,-32.38"></path> <polygon fill="black" stroke="black" points="359.51,-30.46 350.53,-36.76 354.6,-31.4 349.69,-32.34 349.69,-32.34 349.69,-32.34 354.6,-31.4 348.84,-27.92 359.51,-30.46 359.51,-30.46"></polygon> </g> <!-- f --> <g id="node6" class="node">
<title>
f
</title>
<ellipse fill="none" stroke="black" cx="251.29" cy="-90" rx="77" ry="18"></ellipse> <text text-anchor="middle" x="251.29" y="-85.8" font-family="Times,serif" font-size="14.00">Propensity Score</text> </g> <!-- d&#45;&gt;f --> <g id="edge4" class="edge">
<title>
d-&gt;f
</title>
<path fill="none" stroke="black" d="M137.24,-144.94C158.77,-134.76 186.76,-121.52 209.63,-110.7"></path> <polygon fill="black" stroke="black" points="218.76,-106.38 211.65,-114.73 214.24,-108.52 209.72,-110.66 209.72,-110.66 209.72,-110.66 214.24,-108.52 207.8,-106.59 218.76,-106.38 218.76,-106.38"></polygon> </g> <!-- c --> <g id="node4" class="node">
<title>
c
</title>
<ellipse fill="none" stroke="black" cx="300.29" cy="-162" rx="75.3" ry="18"></ellipse> <text text-anchor="middle" x="300.29" y="-157.8" font-family="Times,serif" font-size="14.00">District % Black</text> </g> <!-- c&#45;&gt;b --> <g id="edge3" class="edge">
<title>
c-&gt;b
</title>
<path fill="none" stroke="black" d="M314.52,-144.15C335.54,-119.28 375.01,-72.57 399.34,-43.79"></path> <polygon fill="black" stroke="black" points="406.07,-35.82 403.05,-46.37 402.84,-39.64 399.61,-43.46 399.61,-43.46 399.61,-43.46 402.84,-39.64 396.18,-40.56 406.07,-35.82 406.07,-35.82"></polygon> </g> <!-- c&#45;&gt;f --> <g id="edge2" class="edge">
<title>
c-&gt;f
</title>
<path fill="none" stroke="black" d="M288.43,-144.05C282.59,-135.71 275.43,-125.49 268.96,-116.25"></path> <polygon fill="black" stroke="black" points="263.04,-107.79 272.46,-113.4 265.91,-111.89 268.77,-115.98 268.77,-115.98 268.77,-115.98 265.91,-111.89 265.09,-118.56 263.04,-107.79 263.04,-107.79"></polygon> </g> <!-- e --> <g id="node5" class="node">
<title>
e
</title>
<ellipse fill="none" stroke="black" cx="443.29" cy="-162" rx="49.22" ry="18"></ellipse> <text text-anchor="middle" x="443.29" y="-157.8" font-family="Times,serif" font-size="14.00">Democrat</text> </g> <!-- e&#45;&gt;b --> <g id="edge6" class="edge">
<title>
e-&gt;b
</title>
<path fill="none" stroke="black" d="M440.51,-143.87C436.59,-119.67 429.39,-75.21 424.72,-46.39"></path> <polygon fill="black" stroke="black" points="423.07,-36.19 429.11,-45.34 423.87,-41.12 424.67,-46.06 424.67,-46.06 424.67,-46.06 423.87,-41.12 420.23,-46.78 423.07,-36.19 423.07,-36.19"></polygon> </g> <!-- e&#45;&gt;f --> <g id="edge7" class="edge">
<title>
e-&gt;f
</title>
<path fill="none" stroke="black" d="M409.84,-148.81C379.72,-137.83 335.06,-121.54 300.8,-109.05"></path> <polygon fill="black" stroke="black" points="290.98,-105.47 301.92,-104.67 295.68,-107.18 300.38,-108.9 300.38,-108.9 300.38,-108.9 295.68,-107.18 298.84,-113.13 290.98,-105.47 290.98,-105.47"></polygon> </g> <!-- f&#45;&gt;a --> <g id="edge8" class="edge">
<title>
f-&gt;a
</title>
<path fill="none" stroke="black" d="M249.31,-71.7C248.43,-63.98 247.37,-54.71 246.39,-46.11"></path> <polygon fill="black" stroke="black" points="245.24,-36.1 250.85,-45.53 245.81,-41.07 246.38,-46.04 246.38,-46.04 246.38,-46.04 245.81,-41.07 241.91,-46.55 245.24,-36.1 245.24,-36.1"></polygon> </g> </g>
</svg>
</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Propensity score blocks backdoor paths through confounders. Thus accounting for it closes these back doors.</p>
</blockquote>
<ol start="3" type="1">
<li>Below you can find the code that calculates the propensity scores as well as the inverse probability weights from them. Note that it’s important to check the values of your inverse probability weights, as sometimes they can get too big (like if the very-very unlikely-to-be-treated unit actually was in the treatment group), which could mess with the estimation. To fix this, we can truncate weights at some lower level. There’s no universal rule of thumb for a good maximum weight, and we can often see 10 used as such a cutoff.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>ps_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  leg_black <span class="sc">~</span> medianhhincom <span class="sc">+</span> blackpercent <span class="sc">+</span> leg_democrat,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> black_politicians,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>ipw_df <span class="ot">&lt;-</span> <span class="fu">augment_columns</span>( <span class="co"># unlike augment(), this adds more columns</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  ps_model,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  black_politicians,</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">type.predict =</span> <span class="st">"response"</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># The predictions are in a column named ".fitted", so we rename it here</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">propensity =</span> .fitted) <span class="sc">%&gt;%</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">ipw =</span> (leg_black <span class="sc">/</span> propensity) <span class="sc">+</span> ((<span class="dv">1</span> <span class="sc">-</span> leg_black) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> propensity)),</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">ipw =</span> <span class="fu">if_else</span>(ipw <span class="sc">&gt;</span> <span class="dv">10</span>, <span class="dv">10</span>, ipw) <span class="co"># truncate very high IPWs</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="4" type="1">
<li>Use the calculated weights to re-estimate your main model. Do the results hold again?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  responded <span class="sc">~</span> leg_black <span class="sc">*</span> treat_out <span class="sc">+</span> nonblacknonwhite <span class="sc">+</span>  black_medianhh <span class="sc">+</span> white_medianhh <span class="sc">+</span> statessquireindex <span class="sc">+</span>  totalpop <span class="sc">+</span> urbanpercent <span class="sc">+</span>    medianhhincom <span class="sc">+</span> blackpercent <span class="sc">+</span> leg_democrat,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> ipw_df,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> ipw</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = responded ~ leg_black * treat_out + nonblacknonwhite + 
    black_medianhh + white_medianhh + statessquireindex + totalpop + 
    urbanpercent + medianhhincom + blackpercent + leg_democrat, 
    data = ipw_df, weights = ipw)

Weighted Residuals:
    Min      1Q  Median      3Q     Max 
-1.8332 -0.3804 -0.2400  0.4628  2.4580 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          0.4754313  0.0259544  18.318  &lt; 2e-16 ***
leg_black           -0.0826062  0.0259853  -3.179 0.001486 ** 
treat_out           -0.2778764  0.0137854 -20.157  &lt; 2e-16 ***
nonblacknonwhite    -0.0274272  0.0328572  -0.835 0.403899    
black_medianhh      -0.0019218  0.0078014  -0.246 0.805423    
white_medianhh      -0.0020618  0.0147377  -0.140 0.888745    
statessquireindex    0.3545395  0.0662617   5.351 9.12e-08 ***
totalpop            -0.0008658  0.0007613  -1.137 0.255498    
urbanpercent         0.0434147  0.0241054   1.801 0.071750 .  
medianhhincom        0.0079429  0.0082599   0.962 0.336281    
blackpercent        -0.0446586  0.0423600  -1.054 0.291808    
leg_democrat        -0.0555326  0.0145268  -3.823 0.000133 ***
leg_black:treat_out  0.1184080  0.0344362   3.438 0.000589 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5149 on 5580 degrees of freedom
Multiple R-squared:  0.08338,   Adjusted R-squared:  0.08141 
F-statistic:  42.3 on 12 and 5580 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Yes, the results are robust and hold when using inverse probability weighting, too.</p>
</blockquote>
<ol start="5" type="1">
<li>(Option) Create a nice table for all the models you estimated.</li>
</ol>
</section>
<section id="optional-task-7-matching-by-hand" class="level2">
<h2 class="anchored" data-anchor-id="optional-task-7-matching-by-hand">(Optional) Task 7: Matching by Hand</h2>
<p>This part of the problem set walks you through the process of exact matching when done by hand. Based on this code, you can do the coarsened exact matching and explore how the cut-offs used for coarsening impact the outcomes.</p>
<section id="exact-matching" class="level3">
<h3 class="anchored" data-anchor-id="exact-matching">Exact Matching</h3>
<p>Let’s start with exact matching. You can find the code in the chunk below. Here is what we do step-by-step:</p>
<ul>
<li>We use <code>group_by()</code> to create groups with every unique combination of matching variables. In this case, we are using <code>blackpercent</code>, <code>medianhhincom</code>, <code>leg_democrat</code> as our matching variables.</li>
<li>We then create new variables:
<ul>
<li><code>n</code> is the size of the group, i.e.&nbsp;how many observations have that unique combination in matching variables</li>
<li><code>treated_in_group</code> counts the number of treated units within each group</li>
<li><code>untreated_in_group</code> counts the number of untreated units within each group</li>
</ul></li>
<li>Next, we move on and remove the groups, subclasses, that have only one observation in them (i.e.&nbsp;cases where there are no matches found at all). We also remove the groups that contain only the treated units and only untreated units as they also did not match the treated units to untreated ones.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>manual_exact_df <span class="ot">&lt;-</span> black_politicians <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(blackpercent, medianhhincom, leg_party) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">group_id =</span> <span class="fu">cur_group_id</span>(),</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">treated_in_group =</span> <span class="fu">sum</span>(leg_black),</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">untreated_in_group =</span> <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    n <span class="sc">&gt;</span> <span class="dv">1</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    untreated_in_group <span class="sc">&gt;</span> <span class="dv">0</span>,</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>    treated_in_group <span class="sc">&gt;</span> <span class="dv">0</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="co"># check ourselves with the package</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>exact_df <span class="ot">&lt;-</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">matchit</span>(</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>    leg_black <span class="sc">~</span> medianhhincom <span class="sc">+</span> blackpercent <span class="sc">+</span> leg_party,</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> black_politicians,</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"exact"</span>,</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">match.data</span>()</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a><span class="co"># compare the datasets (only the first 14 columns with actual data)</span></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="fu">setdiff</span>(manual_exact_df[, <span class="dv">1</span><span class="sc">:</span><span class="dv">14</span>], exact_df[, <span class="dv">1</span><span class="sc">:</span><span class="dv">14</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 14
# Groups:   blackpercent, medianhhincom [0]
# ℹ 14 variables: leg_black &lt;dbl&gt;, treat_out &lt;dbl&gt;, responded &lt;dbl&gt;,
#   totalpop &lt;dbl&gt;, medianhhincom &lt;dbl&gt;, black_medianhh &lt;dbl&gt;,
#   white_medianhh &lt;dbl&gt;, blackpercent &lt;dbl&gt;, statessquireindex &lt;dbl&gt;,
#   nonblacknonwhite &lt;dbl&gt;, urbanpercent &lt;dbl&gt;, leg_senator &lt;dbl&gt;,
#   leg_democrat &lt;dbl&gt;, south &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Recall that we are trying to estimate the average treatment effect on the treated, so to compare the actual outcome of the dependent variable, responding to email, given that the <em>treatment</em> was administered (i.e.&nbsp;the legislator was black) to the <em>counterfactual</em>, i.e.&nbsp;the hypothetical situation of the legislator in that same district not being black. This means that we want to have the situation of just one matched untreated unit per every treated unit. Let’s see if it is the case:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>manual_exact_df <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">reframe</span>(<span class="at">ratio_in_group =</span> treated_in_group <span class="sc">/</span> untreated_in_group) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>() <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(ratio_in_group) <span class="sc">%&gt;%</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>.
0.333333333333333               0.5 0.666666666666667                 1 
                6                 6                 1                 4 
                2                 3 
                3                 1 </code></pre>
</div>
</div>
<p>As we see, the ratio is equal only in 4 subgroups. In 6 groups, we have 3 treated per one treated, while in 1 subgroup, we have 3 treated vs.&nbsp;1 untreated units (0.33 ratio). In order to balance out our observations within groups to the 1:1 ratio, we need to “upweight” the untreated units when <span class="math inline">\(n_{untreated} &lt; n_{treated}\)</span> within a subgroup and “downweight” them if <span class="math inline">\(n_{untreated} &gt; n_{treated}\)</span>. This way, we would obtain the difference in means for the outcome variable within the subgroup. Thus we need to weigh the untreated units with this ratio:</p>
<p><span class="math display">\[
w^{untreated}_{subgroup} = \frac{n_{treated}}{n_{untreated}}, ~\text{ and }~w^{treated}_{subgroup} = 1
\]</span></p>
<p>In addition to the part of the weights that equals out the relative shares of treated vs.&nbsp;untreated units, we want normalize these weights so that their sum equals the number of observations in the matched dataset. This is important for calculating the standard errors. Hence we additionally add the ratio of <span class="math inline">\(N_{untreated}/N_{treated}\)</span> for the complete matched dataset (not within each subgroup as before). The weights then become:</p>
<p><span class="math display">\[
w^{untreated} = \frac{N_{untreated}}{N_{treated}}\times \frac{n_{treated}}{n_{untreated}}, ~\text{ and }~w^{treated} = 1
\]</span></p>
<p>This is the manual implementation in <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>manual_exact_df <span class="ot">&lt;-</span> manual_exact_df <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ratio_in_group =</span> treated_in_group <span class="sc">/</span> untreated_in_group) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">ratio_total =</span> <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>),</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> (ratio_total <span class="sc">*</span> ratio_in_group),</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> <span class="fu">if_else</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, weights)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="co"># check with package</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Manual"</span> <span class="ot">=</span> manual_exact_df<span class="sc">$</span>weights <span class="sc">%&gt;%</span> <span class="fu">table</span>(),</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"MatchIt"</span> <span class="ot">=</span> exact_df<span class="sc">$</span>weights <span class="sc">%&gt;%</span> <span class="fu">table</span>()</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Manual</th>
<th style="text-align: right;">MatchIt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0.506172839506173</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.759259259259259</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">27</td>
</tr>
<tr class="even">
<td style="text-align: left;">1.01234567901235</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1.51851851851852</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">3.03703703703704</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4.55555555555556</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now we can proceed to the estimation step (with a simplified model):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># same with linear regression</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(responded <span class="sc">~</span> leg_black, exact_df, <span class="at">weights =</span> weights)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = responded ~ leg_black, data = exact_df, weights = weights)

Weighted Residuals:
    Min      1Q  Median      3Q     Max 
-0.9750 -0.4074 -0.3250  0.4916  0.9467 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.45679    0.07854   5.816 1.92e-07 ***
leg_black   -0.04938    0.12464  -0.396    0.693    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5029 on 66 degrees of freedom
Multiple R-squared:  0.002373,  Adjusted R-squared:  -0.01274 
F-statistic: 0.157 on 1 and 66 DF,  p-value: 0.6932</code></pre>
</div>
</div>
<p>The average treatment effect is equal to -0.04, but uncertainty about it does not allow us to say that it is statistically different from zero.</p>
<p>Note that we did not need to control for the matching variables any more, as we artificially removed the variation in them, which could explain the differences in the outcome. The coefficient for our treatment variable does not change if we include matching variables as the controls:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(responded <span class="sc">~</span> leg_black <span class="sc">+</span> blackpercent <span class="sc">+</span> medianhhincom <span class="sc">+</span> leg_democrat,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  exact_df,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> weights</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = responded ~ leg_black + blackpercent + medianhhincom + 
    leg_democrat, data = exact_df, weights = weights)

Weighted Residuals:
    Min      1Q  Median      3Q     Max 
-1.2102 -0.3742 -0.2896  0.4951  0.8799 

Coefficients: (1 not defined because of singularities)
                Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)    0.3697938  0.2326204   1.590    0.117
leg_black     -0.0493827  0.1258499  -0.392    0.696
blackpercent   0.2399234  0.2793993   0.859    0.394
medianhhincom  0.0007816  0.0383657   0.020    0.984
leg_democrat          NA         NA      NA       NA

Residual standard error: 0.5078 on 64 degrees of freedom
Multiple R-squared:  0.01375,   Adjusted R-squared:  -0.03248 
F-statistic: 0.2975 on 3 and 64 DF,  p-value: 0.8271</code></pre>
</div>
</div>
</section>
<section id="cem" class="level3">
<h3 class="anchored" data-anchor-id="cem">CEM</h3>
<p>Your job now is to adjust the code above for the CEM application. Recall that we need to split the continuous variables into a number of bins to reduce the dimensionality. You can use <code>cut()</code> function to make such bins:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cut</span>(black_politicians<span class="sc">$</span>blackpercent, <span class="at">breaks =</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">.</th>
<th style="text-align: right;">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(-0.000673,0.195]</td>
<td style="text-align: right;">4799</td>
</tr>
<tr class="even">
<td style="text-align: left;">(0.195,0.39]</td>
<td style="text-align: right;">432</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(0.39,0.585]</td>
<td style="text-align: right;">178</td>
</tr>
<tr class="even">
<td style="text-align: left;">(0.585,0.78]</td>
<td style="text-align: right;">161</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(0.78,0.975]</td>
<td style="text-align: right;">23</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="1">
<li>Adjust the code below to create such binned versions of the variables. Split <code>blackpercent</code> into 10 bins and <code>medianhhincom</code> into 12 (these are arbitrary values). Note that <code>leg_democrat</code> is categorical, so you don’t need to split it.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>manual_cem_df <span class="ot">&lt;-</span> black_politicians <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">mutate</span>(</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">medianhhincom_coarse =</span> <span class="fu">cut</span>(medianhhincom, <span class="at">breaks =</span> <span class="dv">12</span>),</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">blackpercent_coarse =</span> <span class="fu">cut</span>(blackpercent, <span class="at">breaks =</span> <span class="dv">10</span>),</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(blackpercent_coarse, medianhhincom_coarse, leg_party) <span class="sc">%&gt;%</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">subclass =</span> <span class="fu">cur_group_id</span>(),</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">treated_in_group =</span> <span class="fu">sum</span>(leg_black),</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">untreated_in_group =</span> <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>    n <span class="sc">&gt;</span> <span class="dv">1</span>,</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>    untreated_in_group <span class="sc">&gt;</span> <span class="dv">0</span>,</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>    treated_in_group <span class="sc">&gt;</span> <span class="dv">0</span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ratio_in_group =</span> treated_in_group <span class="sc">/</span> untreated_in_group) <span class="sc">%&gt;%</span></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">ratio_total =</span> <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>),</span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> (ratio_total <span class="sc">*</span> ratio_in_group),</span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> <span class="fu">if_else</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, weights)</span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a><span class="co"># quick &amp; dirty plots to assess the balance</span></span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a><span class="co"># note that we need to apply weights, too!</span></span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a>blackpercent <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a>  manual_cem_df,</span>
<span id="cb42-30"><a href="#cb42-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb42-31"><a href="#cb42-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> blackpercent,</span>
<span id="cb42-32"><a href="#cb42-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="fu">factor</span>(leg_black),</span>
<span id="cb42-33"><a href="#cb42-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">group =</span> <span class="fu">factor</span>(leg_black)</span>
<span id="cb42-34"><a href="#cb42-34" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb42-35"><a href="#cb42-35" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb42-36"><a href="#cb42-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">weight =</span> weights))</span>
<span id="cb42-37"><a href="#cb42-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-38"><a href="#cb42-38" aria-hidden="true" tabindex="-1"></a>medianhhincom <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb42-39"><a href="#cb42-39" aria-hidden="true" tabindex="-1"></a>  manual_cem_df,</span>
<span id="cb42-40"><a href="#cb42-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb42-41"><a href="#cb42-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> medianhhincom,</span>
<span id="cb42-42"><a href="#cb42-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="fu">factor</span>(leg_black),</span>
<span id="cb42-43"><a href="#cb42-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">group =</span> <span class="fu">factor</span>(leg_black)</span>
<span id="cb42-44"><a href="#cb42-44" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb42-45"><a href="#cb42-45" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb42-46"><a href="#cb42-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">weight =</span> weights))</span>
<span id="cb42-47"><a href="#cb42-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-48"><a href="#cb42-48" aria-hidden="true" tabindex="-1"></a>leg_democrat <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb42-49"><a href="#cb42-49" aria-hidden="true" tabindex="-1"></a>  manual_cem_df,</span>
<span id="cb42-50"><a href="#cb42-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb42-51"><a href="#cb42-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> leg_democrat,</span>
<span id="cb42-52"><a href="#cb42-52" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="fu">factor</span>(leg_black),</span>
<span id="cb42-53"><a href="#cb42-53" aria-hidden="true" tabindex="-1"></a>    <span class="at">group =</span> <span class="fu">factor</span>(leg_black)</span>
<span id="cb42-54"><a href="#cb42-54" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb42-55"><a href="#cb42-55" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb42-56"><a href="#cb42-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">weight =</span> weights))</span>
<span id="cb42-57"><a href="#cb42-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-58"><a href="#cb42-58" aria-hidden="true" tabindex="-1"></a><span class="co"># plot all conditional distributions</span></span>
<span id="cb42-59"><a href="#cb42-59" aria-hidden="true" tabindex="-1"></a>leg_democrat <span class="sc">/</span> blackpercent <span class="sc">/</span> medianhhincom</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="10-problem-set_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="2" type="1">
<li>Try out a few different values for thresholds to see which ones produce best distributions. Show the combination that produced best covariate balance.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>manual_cem_df <span class="ot">&lt;-</span> black_politicians <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">mutate</span>(</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">medianhhincom_coarse =</span> <span class="fu">cut</span>(medianhhincom, <span class="at">breaks =</span> <span class="dv">15</span>),</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">blackpercent_coarse =</span> <span class="fu">cut</span>(blackpercent, <span class="at">breaks =</span> <span class="dv">15</span>),</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(blackpercent_coarse, medianhhincom_coarse, leg_party) <span class="sc">%&gt;%</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">subclass =</span> <span class="fu">cur_group_id</span>(),</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">treated_in_group =</span> <span class="fu">sum</span>(leg_black),</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">untreated_in_group =</span> <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>    n <span class="sc">&gt;</span> <span class="dv">1</span>,</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>    untreated_in_group <span class="sc">&gt;</span> <span class="dv">0</span>,</span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>    treated_in_group <span class="sc">&gt;</span> <span class="dv">0</span></span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ratio_in_group =</span> treated_in_group <span class="sc">/</span> untreated_in_group) <span class="sc">%&gt;%</span></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">ratio_total =</span> <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>),</span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> (ratio_total <span class="sc">*</span> ratio_in_group),</span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> <span class="fu">if_else</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, weights)</span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="3" type="1">
<li>Comment on the plot generated from your matched dataset. How does the ratio between treated and untreated units seem to look across the variables? What are the differences to exact matching?</li>
</ol>
<blockquote class="blockquote">
<p>In comparison to exact matching, there are many more than one untreated units per treated unit. Tthis ratio increases the more the subgroups we create (10 <span class="math inline">\(\times\)</span> 12 $ gave us 240 subgroups, the somewhat better option of 15 <span class="math inline">\(\times\)</span> 15 $ gave us 450 subgroups). We are thus seeing the trade-off between the number of matched units vs.&nbsp;the potential bias in the resuts due to imperfect matches.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  manual_cem_df <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(subclass) <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">if_else</span>(</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>      leg_black <span class="sc">==</span> <span class="dv">1</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>      <span class="dv">1</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="fu">sum</span>(leg_black <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    )) <span class="sc">%&gt;%</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(leg_black, n),</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>    medianhhincom,</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>    blackpercent,</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="fu">factor</span>(leg_black),</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> n</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.7</span>,</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">pch =</span> <span class="dv">21</span>,</span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"grey80"</span></span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(leg_party)) <span class="sc">+</span></span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Treatment Variable (Legislator is Black)"</span>,</span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="st">"Units in Subgroup"</span>,</span>
<span id="cb44-27"><a href="#cb44-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Share of Black Voters in District"</span>,</span>
<span id="cb44-28"><a href="#cb44-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Median Household Income in District"</span></span>
<span id="cb44-29"><a href="#cb44-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb44-30"><a href="#cb44-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb44-31"><a href="#cb44-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb44-32"><a href="#cb44-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.box =</span> <span class="st">"vertical"</span></span>
<span id="cb44-33"><a href="#cb44-33" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="10-problem-set_files/figure-html/cem-manual-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Content <i class="fa-brands fa-creative-commons" aria-hidden="true"></i> 2023 by <a href="https://www.sowi.uni-mannheim.de/gschwend/team/postdocs-and-doctoral-students/viktoriia-semenova/">Viktoriia Semenova</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-by" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-nc" aria-hidden="true"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></div>   
    <div class="nav-footer-right">Made with <i class="fa-solid fa-heart" aria-hidden="true"></i>, <a href="https://github.com/"><i class="fa-brands fa-github" aria-hidden="true"></i></a>, <a href="https://posit.co/"><i class="fa-brands fa-r-project" aria-hidden="true"></i></a> and <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>