---
title: "Roadmap"
sidebar: false
toc: false
page-layout: full
---

```{r packages-data, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)

withr::with_dir(here::here(), {
  schedule_nested <- targets::tar_read(schedule_page_data)
  targets::tar_load(schedule_ical_file)
})

base_url <- yaml::read_yaml(here::here("_quarto.yml"))$website$`site-url`
ical_url_absolute <- paste0(base_url, "/", schedule_ical_file)
```

::: {.schedule-page}

- [**Prepare**](/s23/session/) ({{< fa book-open-reader >}}): This page contains readings and videos for the week. Read and watch these **before** our in-person class. 

- [**Sessions**](/s23/session/) ({{< fa laptop-code >}}): Here you can find the slides and further material from our in-person sessions. 

- [**Assignments**](/s23/session/) ({{< fa code >}}): This page contains the instructions for weekly problem sets. 



```{r build-table, include=FALSE} 
show_table <- function(group_id) {
  # Add a heading
  cat(as.character(paste("\n####", schedule_nested$group[[group_id]], "\n")))
  
  # Make the table
  tbl <- schedule_nested$data[[group_id]] %>% 
    rename("  " = subgroup) %>% 
    # dplyr::select(-subgroup) %>% 
    kbl(escape = FALSE, align = "rrlccc", table.attr = 'class="schedule-table"') %>% 
    kable_styling() %>% 
    column_spec(1, width = "10%", extra_css = "padding-right: 20px;") %>% 
    column_spec(2, width = "10%", extra_css = "padding-right: 20px;") %>% 
    column_spec(3, width = "50%") %>% 
    column_spec(4:6, width = "10%") 
    # pack_rows(index = schedule_nested$subgroup_index[[group_id]],
    #           label_row_css = "border-bottom: 1px solid #000000;")
  
  cat(tbl)
}
```

```{r show-table, echo=FALSE, results="asis"}
walk(seq(1, nrow(schedule_nested)), ~show_table(.x))
```

:::


<!-- ::: {.callout-tip} -->

<!-- ## Subscribe! -->

<!-- You can subscribe to this calendar URL in Outlook, Google Calendar, or Apple Calendar: -->

<!-- ::: {.grid} -->

<!-- ::: {.g-col-12 .g-col-md-2} -->
<!-- <p class="download-btn"><a class="btn btn-danger btn-sm" href="/`r schedule_ical_file`" role="button">{{< fa calendar-alt >}} Download</a></p> -->
<!-- ::: -->

<!-- ::: {.g-col-12 .g-col-md-10} -->
<!-- <p><input class="form-control" type="text" value="`r ical_url_absolute`" onclick="this.select()" readonly></p> -->
<!-- ::: -->

<!-- ::: -->

<!-- ::: -->

