{
  "hash": "62d07abd328f523e57ac448ba9cf830f",
  "result": {
    "markdown": "---\ntitle: \"Communicating Uncertainty with Simulations\"\nsubtitle: \"R for Data Analysis<br>Session 11\"\ntitle-slide-attributes:\n  data-background-size: stretch\n  data-slide-number: none\nauto-stretch: false\ninstitute: \"University of Mannheim<br>Fall 2023\"\nauthor: \"Viktoriia Semenova\"\nfooter: \"[🔗 r4da.live](https://r4da.live/)\"\nlogo: images/logo.png\nformat:\n  revealjs:\n    theme: slides.scss\n    transition: fade\n    incremental: true   \n    slide-number: true\n    chalkboard: true\nexecute:\n  echo: true\neditor_options: \n  chunk_output_type: console\neditor: \n  markdown: \n    wrap: 80\n---\n\n\n\n\n# Uncertainty and Inference\n\n## Model Plots and Confidence Intervals {.smaller}\n\n<!-- ::: columns -->\n\n<!-- ::: {.column width=\"50%\"} -->\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(m2, conf.int = T, conf.level = 0.99) %>%\n  dplyr::select(term, estimate, starts_with(\"conf\")) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|term        |   estimate|   conf.low|  conf.high|\n|:-----------|----------:|----------:|----------:|\n|(Intercept) |  3.7350210|  3.5351075|  3.9349345|\n|beauty      |  0.0787286|  0.0360562|  0.1214009|\n|female      | -0.2007897| -0.3326538| -0.0689256|\n:::\n:::\n\n\n<!-- ::: -->\n\n<!-- ::: {.column width=\"50%\"} -->\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodelplot(m2, conf_level = 0.99) +\n  geom_vline(xintercept = 0, lty = 2)\n```\n\n::: {.cell-output-display}\n![](11-slides_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=2100}\n:::\n:::\n\n\n<!-- ::: -->\n\n<!-- ::: -->\n\n## Sampling Distributions {.smaller}\n\n-   The sampling distribution of a statistic is a probability distribution based\n    on a large number of samples of size $N$ from a given population\n\n-   Sampling distributions represent the variability of our estimates: if we had\n    taken different samples from the population, we would have obtained slightly\n    different estimates\n\n-   Sampling distributions of most of the parameters are normal:\n\n    -   Determined by two parameters, mean (center) and standard deviation\n        (spread)\n\n## Draws from Simulated Sampling Distributions {.smaller}\n\nWe can use our coefficient estimates and uncertainty about them to simulate\nsampling distributions:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=2100 height=80%}\n:::\n:::\n\n\n## Simulated Sampling Distributions {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# get draws from multivariate normal distribution \nsims <- clarify::sim(m2, n = 1000)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n| (Intercept)|    beauty|     female|\n|-----------:|---------:|----------:|\n|    3.785188| 0.0552573| -0.1306640|\n|    3.634660| 0.0981444| -0.2005275|\n|    3.804106| 0.0564569| -0.1298170|\n|    3.744705| 0.0734567| -0.1548727|\n|    3.700973| 0.0927997| -0.2474655|\n|    3.678285| 0.0813183| -0.1310003|\n:::\n:::\n\n\n## Simulated Sampling Distributions {.smaller}\n\n<!-- ::: columns -->\n\n<!-- ::: {.column width=\"50%\"} -->\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas_tibble(sims$sim.coefs) %>% \n  summarise_all(.funs = list(mean = ~ mean(.))) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n| (Intercept)_mean| beauty_mean| female_mean|\n|----------------:|-----------:|-----------:|\n|         3.734268|   0.0788016|  -0.2021927|\n:::\n\n```{.r .cell-code}\nas_tibble(sims$sim.coefs) %>% \n  summarise_all(.funs = list(sd = ~ sd(.))) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n| (Intercept)_sd| beauty_sd| female_sd|\n|--------------:|---------:|---------:|\n|      0.0788563| 0.0162285| 0.0500556|\n:::\n:::\n\n\n<!-- ::: -->\n\n<!-- ::: {.column width=\"50%\"} -->\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(m2) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n|term        |   estimate| std.error| statistic|  p.value|\n|:-----------|----------:|---------:|---------:|--------:|\n|(Intercept) |  3.7350210| 0.0772894| 48.325167| 0.00e+00|\n|beauty      |  0.0787286| 0.0164977|  4.772087| 2.50e-06|\n|female      | -0.2007897| 0.0509805| -3.938559| 9.47e-05|\n:::\n:::\n\n\n<!-- ::: -->\n\n<!-- ::: -->\n\n## Calculations with Simulated Coefficients {.smaller}\n\n-   Now instead of one equation with *estimated* coefficients, we have many with\n    similar, *simulated* coefficients\n-   Each equation will result in slightly different expected value\n\n. . .\n\n$$\n{ \\begin{array}{c}\n        \\tilde{\\beta}_0^1 \\times 1+\\tilde{\\beta}_1^1 \\times   \\text{Beauty Score}_i  +\\tilde{\\beta}_2^1 \\times \\text{Female}_i &= E(\\tilde {\\text{Course Evaluation}_i}|\\text{Beauty Score}_i, \\text{Female}_i)\\\\\n \\tilde{\\beta}_0^2 \\times 1+\\tilde{\\beta}_1^2 \\times   \\text{Beauty Score}_i  +\\tilde{\\beta}_2^2 \\times \\text{Female}_i &= E(\\tilde {\\text{Course Evaluation}_i}|\\text{Beauty Score}_i, \\text{Female}_i)\\\\\n  \\tilde{\\beta}_0^3 \\times 1+\\tilde{\\beta}_1^3 \\times   \\text{Beauty Score}_i  +\\tilde{\\beta}_2^3 \\times \\text{Female}_i  &= E(\\tilde {\\text{Course Evaluation}_i}|\\text{Beauty Score}_i, \\text{Female}_i)\\\\\n        \\dots \\\\\n        \\tilde{\\beta}_0^{1000} \\times 1+\\tilde{\\beta}_1^{1000} \\times \\text{Beauty Score}_i  +\\tilde{\\beta}_2^{1000} \\times \\text{Female}_i  &= E(\\tilde {\\text{Course Evaluation}_i}|\\text{Beauty Score}_i, \\text{Female}_i)\\\\\n    \\end{array} }\n$$\n\n## Calculating Predicted Probabilities for Chosen Scenarios {.smaller}\n\n$$\n{\\text{Beauty Score} = 1,~\\text{Female} = 1}\n$$\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlo1 <- sims$sim.coefs[1,1] +  sims$sim.coefs[1,2] * 1 +\n  sims$sim.coefs[1,3] * 1 \nlo1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n   3.709781 \n```\n:::\n\n```{.r .cell-code}\nlo2 <- sims$sim.coefs[2,1] +  sims$sim.coefs[2,2] * 1 + \n  sims$sim.coefs[2,3] * 1\nlo2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n   3.532277 \n```\n:::\n\n```{.r .cell-code}\n# and so on for every row in the matrix \n```\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# with clarify \nevs <- sim_setx(sim = sims, # object with simulated coefs  \n         x = list(beauty = 1, # scenario \n                  female = 1))\n\n# compare to manual calculations \nas.matrix(evs) %>% head(6) %>% kable()\n```\n\n::: {.cell-output-display}\n|        1|\n|--------:|\n| 3.709781|\n| 3.532277|\n| 3.730746|\n| 3.663289|\n| 3.546307|\n| 3.628604|\n:::\n:::\n\n:::\n:::\n\n## Summarize Expected Values {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=2100}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n| Estimate|    2.5 %|   97.5 %|\n|--------:|--------:|--------:|\n|  3.61296| 3.470971| 3.745622|\n:::\n:::\n\n\n> We are 95% confident that expected course evaluation ranges from\n> 3.47 to\n> 3.75 percentage points in case\n> $${\\text{Beauty Score} = 1,~\\text{Female} = 1}$$\n:::\n:::\n\n## Expected Values for Two Scenarios {.smaller}\n\n$${\\text{Beauty Score} = 1,~\\text{Female} = 0}$$\n$${\\text{Beauty Score} = 1,~\\text{Female} = 1}$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n| female = 0| female = 1|\n|----------:|----------:|\n|   3.840445|   3.709781|\n|   3.732804|   3.532277|\n|   3.860563|   3.730746|\n|   3.818161|   3.663289|\n|   3.793773|   3.546307|\n|   3.759604|   3.628604|\n:::\n:::\n\n\n--------------------------------------------------------------------------------\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=2100}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|           | Estimate|    2.5 %|   97.5 %|\n|:----------|--------:|--------:|--------:|\n|female = 0 |  3.81375| 3.682049| 3.939730|\n|female = 1 |  3.61296| 3.470971| 3.745622|\n:::\n:::\n\n\n## What Is the Effect of Russian TV Propaganda? {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfds <- transform(evs, \n          `First Difference` = `female = 1` - `female = 0`) \nfds %>% \n  summary() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|                 |   Estimate|      2.5 %|    97.5 %|\n|:----------------|----------:|----------:|---------:|\n|female = 0       |  3.8137496|  3.6820494|  3.939730|\n|female = 1       |  3.6129599|  3.4709714|  3.745622|\n|First Difference | -0.2007897| -0.3014803| -0.102592|\n:::\n:::\n\n\n--------------------------------------------------------------------------------\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=2100}\n:::\n:::\n\n\n## Multiple Scenarios and First Differences {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nevs <- sim_setx(sim = sims, # object with simulated coefs  \n         x = list(female = 0:1, # scenario with desired (plausible) values \n                  beauty = c(1, 10)))\n\nas.matrix(evs) %>% head(3) %>% kable()\n```\n\n::: {.cell-output-display}\n| female = 0, beauty = 1| female = 0, beauty = 10| female = 1, beauty = 1| female = 1, beauty = 10|\n|----------------------:|-----------------------:|----------------------:|-----------------------:|\n|               3.840445|                4.337761|               3.709781|                4.207097|\n|               3.732804|                4.616104|               3.532277|                4.415577|\n|               3.860563|                4.368675|               3.730746|                4.238858|\n:::\n:::\n\n\n## Multiple Scenarios {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfds <- transform(\n  evs,\n  `FD_female = 0` = `female = 0, beauty = 10` - `female = 0, beauty = 1`,\n  `FD_female = 1` = `female = 1, beauty = 10` - `female = 1, beauty = 1`\n) \n\nsummary(fds) %>% kable()\n```\n\n::: {.cell-output-display}\n|                        | Estimate|     2.5 %|    97.5 %|\n|:-----------------------|--------:|---------:|---------:|\n|female = 0, beauty = 1  | 3.813750| 3.6820494| 3.9397304|\n|female = 0, beauty = 10 | 4.522307| 4.3377481| 4.7072476|\n|female = 1, beauty = 1  | 3.612960| 3.4709714| 3.7456223|\n|female = 1, beauty = 10 | 4.321517| 4.1326041| 4.5022782|\n|FD_female = 0           | 0.708557| 0.4208372| 0.9848888|\n|FD_female = 1           | 0.708557| 0.4208372| 0.9848888|\n:::\n:::\n\n\n--------------------------------------------------------------------------------\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=2100}\n:::\n:::\n\n\n# Visualising Interaction Effects\n\n## Marginal Effects Plot\n\n![](https://tompepinsky.files.wordpress.com/2017/04/mfx1.jpeg){fig-align=\"center\"}\n\n## Quiz: Which of these statements are correct? {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_1a9f5896\" data-update-every=\"1\" tabindex=\"0\" style=\"top:0;right:0;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">04</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\nIndridason and Bowler (2014) explore the determinants of cabinet size in\nparliamentary systems. Below you can find a plot based on one of their model.\n<!-- $$\\widehat {Cabinet~Size} = \\hat{\\beta}_{0} + \\hat{\\beta}_{1}(\\operatorname{Legislature Size}) + \\hat{\\beta}_{2}(\\operatorname{Legislature Size}) + \\hat{\\beta}_{3}(\\operatorname{Population Size}) + \\hat{\\beta}_{4}(\\operatorname{EU membership}) + \\epsilon$$ -->\n\n::: columns\n::: {.column width=\"50%\"}\n1.  Systematic component of the model likely includes variable *Legislature\n    Size* interacted with another variable.\\\n2.  Marginal effect of the variable *Legislature Size* is constant across all\n    values of *Legislature Size* variable.\n3.  The relationship between *legislature size* and *cabinet size* is strongest\n    for smaller values of *legislature size*.\n4.  For legislatures with sizes above 500, there is, on average, no significant\n    effect of *legislature size* on *cabinet size*.\n5.  *Legislature size* seems to be inversely related to *cabinet size*.\n:::\n\n::: {.column width=\"50%\"}\n::: r-stack\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides_files/figure-revealjs/unnamed-chunk-21-1.png){fig-align='center' width=2100}\n:::\n:::\n\n\n::: fragment\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides_files/figure-revealjs/unnamed-chunk-22-1.png){fig-align='center' width=2100}\n:::\n:::\n\n:::\n:::\n:::\n:::\n",
    "supporting": [
      "11-slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/countdown-0.4.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/countdown-0.4.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}