{
  "hash": "71f4905565dcae7b2780f08333ba253d",
  "result": {
    "markdown": "---\ntitle: \"Estimating Heterogeneous Effects\"\nsubtitle: \"Data Analytics and Visualization with R<br>Session 8\"\ntitle-slide-attributes:\n  data-background-size: stretch\n  data-slide-number: none\nauto-stretch: false\ninstitute: \"University of Mannheim<br>Spring 2023\"\nauthor: \"Viktoriia Semenova\"\nfooter: \"[🔗 r4da.live](https://r4da.live/)\"\nlogo: images/logo.png\nformat:\n  revealjs:\n    theme: ../slides.scss\n    transition: fade\n    incremental: true   \n    slide-number: true\n    chalkboard: true\nexecute:\n  echo: true\neditor_options: \n  chunk_output_type: console\neditor: \n  markdown: \n    wrap: 80\n---\n\n\n\n\n# Intro\n\n## Quiz: Which of these statements are correct? {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div class=\"countdown\" id=\"timer_04461012\" data-update-every=\"1\" tabindex=\"0\" style=\"bottom:0;left:0;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">04</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n:::\n:::\n\n\n\n::: columns\n::: {.column width=\"50%\"}\n1. $R^2$ is an important criterion only for the regression for the purpose of prediction, not for causal effect estimation.  \n2. If the variable is not statistically significant, it has no impact on the outcome and we can drop it from the regression equation. \n3. Holding all else constant, the estimates from more data would produce smaller confidence intervals. \n4. Overlapping confidence intervals for small and large values of *Beauty* mean that there is no significant difference between the teaching evaluations of male and female instructors.  \n\n::: \n::: {.column width=\"50%\"}\n\n::: {.r-stack}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-regression_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=2100}\n:::\n:::\n\n\n::: {.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-regression_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=2100}\n:::\n:::\n\n:::\n:::\n::: \n:::\n\n\n# Heterogeneous Effects \n\n## Which of These Hypotheses Specify Conditional Relationsip? {.smaller}\n\n1. Women representatives are more likely than men representatives to focus on issues of relative importance to women.\n2. The stronger the partisan identification of the voter, the stronger is anger in response to threat of electoral loss.\n3. For candidates that the voter has seen on posters, appearance has a stronger effect on vote choice than for candidates that the voter has not seen on posters.\n4. Women are more likely to substantively represent women if they were elected in districts with larger magnitude.\n5. Government parties are more likely to engage in constructive legislative review than opposition parties.\n\n\n## Dataset: Student Evaluations \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglimpse(evals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 463\nColumns: 9\n$ x1         <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20…\n$ eval       <dbl> 4.3, 4.5, 3.7, 4.3, 4.4, 4.2, 4.0, 3.4, 4.5, 3.9, 3.1, 4.0, 3.8, 3.4,…\n$ beauty     <dbl> 5.000000, 3.000000, 3.333333, 3.166667, 7.333333, 5.500000, 4.166667,…\n$ female     <dbl> 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, …\n$ age        <dbl> 36, 59, 51, 40, 31, 62, 33, 51, 33, 47, 35, 37, 42, 49, 37, 45, 56, 4…\n$ minority   <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, …\n$ nonenglish <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, …\n$ lower      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, …\n$ course_id  <dbl> 3, 0, 4, 2, 0, 0, 4, 0, 0, 4, 4, 0, 0, 0, 9, 9, 10, 0, 0, 0, 9, 8, 10…\n```\n:::\n:::\n\n\n## Baseline Model {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |    3.893|     0.177|    22.016|   0.000|    3.545|     4.240|\n|beauty      |    0.075|     0.017|     4.422|   0.000|    0.042|     0.109|\n|female      |   -0.212|     0.052|    -4.066|   0.000|   -0.315|    -0.110|\n|age         |   -0.002|     0.003|    -0.885|   0.377|   -0.008|     0.003|\n|nonenglish  |   -0.334|     0.104|    -3.228|   0.001|   -0.538|    -0.131|\n:::\n:::\n\n\n## Baseline Model {.smaller}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in is.na(x): is.na() applied to non-(list or vector) of type 'expression'\n\nWarning in is.na(x): is.na() applied to non-(list or vector) of type 'expression'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 row containing missing values (`geom_line()`).\n```\n:::\n\n::: {.cell-output-display}\n![](08-regression_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=2100 height=50%}\n:::\n:::\n\n\n## Heterogenous Effects of Beauty {.smaller}\n\n<!-- - The effect of beauty on course evaluations differs across male and female professors: -->\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n|term          | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)   |    3.751|     0.193|    19.443|   0.000|    3.372|     4.130|\n|beauty        |    0.103|     0.023|     4.501|   0.000|    0.058|     0.148|\n|female        |    0.056|     0.157|     0.356|   0.722|   -0.253|     0.365|\n|age           |   -0.002|     0.003|    -0.712|   0.477|   -0.007|     0.003|\n|nonenglish    |   -0.340|     0.103|    -3.289|   0.001|   -0.543|    -0.137|\n|beauty:female |   -0.060|     0.033|    -1.810|   0.071|   -0.124|     0.005|\n:::\n:::\n\n \n## Heterogenous Effects of Beauty {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\nWarning in is.na(x): is.na() applied to non-(list or vector) of type 'expression'\n\nWarning in is.na(x): is.na() applied to non-(list or vector) of type 'expression'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing missing values (`geom_line()`).\n```\n:::\n\n::: {.cell-output-display}\n![](08-regression_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=2100 height=50%}\n:::\n:::\n\n\n\n## Heterogenous Effects: Model Specification {.smaller}\n\n$$\n\\text{Evaluation}_i = \\underbrace{\\hat\\beta_0}_{\\text{Expected evaluation}\\\\\\text{for males if}\\\\\\text{beauty score = 0}} + \\underbrace{\\hat\\beta_1}_{\\text{Difference in}\\\\\\text{evaluation between}\\\\\\text{males and females}\\\\\\text{if beauty score = 0}} \\text{Female}_i + \\underbrace{\\hat\\beta_2}_{\\text{Effect of each}\\\\\\text{additional point}\\\\\\text{in score for males}} \\text{Beauty}_i \\\\ +  \\underbrace{\\hat\\beta_3}_{\\text{Difference in}\\\\\\text{effect of beauty}\\\\\\text{between males}\\\\\\text{and females}} \\text{Female}_i \\times \\text{Beauty}_i\n$$\n\n- $\\text{Female}_i$ and $\\text{Beauty}_i$: constitutive terms \n- $\\text{Female}_i \\times \\text{Beauty}_i$: interaction term \n \n## Heterogenous Effects: Model Specification {.smaller}\n \nWe are allowing the effects of beauty to vary across the subgroups:\n\nMale instructors:\n\n$$\n\\text{Evaluation}_i = \\hat\\beta_0 + \\hat\\beta_1 \\times [\\text{Female}_i = 0] + \\hat\\beta_2 \\text{Beauty}_i +  \\hat\\beta_3 \\times [\\text{Female}_i = 0] \\times \\text{Beauty}_i \\\\\n\\text{Evaluation}_i = \\hat\\beta_0 + \\hat\\beta_1 \\times 0 + \\hat\\beta_2 \\text{Beauty}_i +  \\hat\\beta_3 \\times 0 \\times \\text{Beauty}_i \\\\\n\\text{Evaluation}_i = {\\hat\\beta_0} + {\\hat\\beta_2} \\text{Beauty}_i\n$$\n\nFemale instructors:\n\n$$\n\\text{Evaluation}_i = \\hat\\beta_0 + \\hat\\beta_1 \\times [\\text{Female}_i = 1] + \\hat\\beta_2 \\text{Beauty}_i +  \\hat\\beta_3 \\times [\\text{Female}_i = 1] \\times \\text{Beauty}_i \\\\\n\\text{Evaluation}_i = (\\hat\\beta_0 + \\hat\\beta_1)  + (\\hat\\beta_2  +  \\hat\\beta_3 ) \\times \\text{Beauty}_i \n$$\n\n## Working with Interaction Effects {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n````{.cell-code}\n```{{r}}\n#| results: asis\nm1 <- lm(eval ~ beauty * female + age + nonenglish, data = evals)\nequatiomatic::extract_eq(m1, use_coefs = T, terms_per_line = 3, coef_digits = 3)\n```\n````\n\n::: {.cell-output-display}\n$$\n\\operatorname{\\widehat{eval}} = 3.751 + 0.103(\\operatorname{beauty}) + 0.056(\\operatorname{female}) - 0.002(\\operatorname{age}) - 0.34(\\operatorname{nonenglish}) - 0.06(\\operatorname{beauty} \\times \\operatorname{female})\n$$\n:::\n:::\n\n\n- Include all constitutive terms (i.e. those variables that compose the interaction)\n- Do not interpret the coefficients on constitutive terms as unconditional marginal effects:\n\n> Wrong: On average, beauty score is associated with an increase in teaching evaluations, holding all else constant. \\\n> Wrong: On average, female instructors receive 0.05 points more in teaching evaluations than males, holding all else constant. \\\n> Right: On average, beauty tends to have smaller effect on teaching evaluations among female instructors in comparison to male instructors, holding all else constant.  \n\n## Causal Interaction vs. Effect Modification {.smaller}\n\n$$\n\\text{Evaluation}_i = \\hat\\beta_0 + \\hat\\beta_1 \\times \\text{Female}_i  + \\hat\\beta_2 \\text{Beauty}_i +  \\hat\\beta_3 \\times \\text{Female}_i \\times \\text{Beauty}_i \\\\\n$$\n\nMathematically, interactions allow us to tell two stories: \n\n- the effect of *Beauty* on *Teaching Evaluations* differs between male and female instructors \n- the effect of *Gender* on *Teaching Evaluations* differs across values of beauty score  \n\n:::task \nInterpret the interaction coefficients in line with your causal story and your selected control variables.\n:::\n\n\n## Alternative: Using Subsets {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm3 <- lm(eval ~ beauty + age + nonenglish, \n         data = evals %>% filter(female == 1))\ntidy(m3, conf.int = T, conf.level = 0.9) %>% \n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |    4.253|     0.259|    16.392|   0.000|    3.824|     4.682|\n|beauty      |    0.034|     0.025|     1.376|   0.171|   -0.007|     0.075|\n|age         |   -0.011|     0.005|    -2.409|   0.017|   -0.019|    -0.003|\n|nonenglish  |   -0.117|     0.160|    -0.731|   0.466|   -0.382|     0.148|\n:::\n:::\n\n\n::: \n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm4 <- lm(eval ~ beauty + age + nonenglish, \n         data = evals %>% filter(female == 0))\ntidy(m4, conf.int = T, conf.level = 0.9) %>% \n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |    3.499|     0.230|    15.215|   0.000|    3.119|     3.878|\n|beauty      |    0.113|     0.023|     4.885|   0.000|    0.075|     0.152|\n|age         |    0.002|     0.003|     0.664|   0.507|   -0.003|     0.008|\n|nonenglish  |   -0.443|     0.137|    -3.237|   0.001|   -0.668|    -0.217|\n:::\n:::\n\n::: \n::: \n\n- Sample size: interactions rely on more data, hence smaller uncertainty \n- Comparisons are easier across effects with one model \n- Works straightforwardly when the moderator is categorical, continuous moderators require arbitrary decisions about cutoff points \n- Best: do both to make sure your results are robust \n\n\n## Intractions with Continous Variables {.smaller}\n\n$$\n\\text{Evaluation}_i = \\hat\\beta_0 + \\hat\\beta_1 \\times \\text{Age}_i  + \\hat\\beta_2 \\text{Beauty}_i +  \\hat\\beta_3 \\times \\text{Age}_i \\times \\text{Beauty}_i \\\\\n$$\n\n- Marginal effect of *Beauty* on *Teaching evaluation*: $\\hat\\beta_2  + \\hat\\beta_3 \\times \\text{Age}_i$\n\n- Marginal effect of *Age* on *Teaching evaluation*: $\\hat\\beta_1  +  \\hat\\beta_3 \\times \\text{Beauty}_i$\n\n## Quiz: What is the Marginal Effect of *Beauty*?\n\n$$\n\\text{Evaluation}_i = \\hat\\beta_0 + \\hat\\beta_1 \\times \\text{Age}_i  + \\hat\\beta_2 \\text{Beauty}_i +  \\hat\\beta_3 \\times \\text{Age}_i \\times \\text{Beauty}_i \\\\\n+ \\hat\\beta_4 \\text{Female}_i +  \\hat\\beta_5 \\times \\text{Female}_i \\times \\text{Beauty}_i\n$$\n\n1. $\\hat\\beta_2  +  \\hat\\beta_3 \\times \\text{Age}_i$\n2. $\\hat\\beta_2  +  \\hat\\beta_3 \\times \\text{Age}_i + \\hat\\beta_5 \\times \\text{Female}_i$\n3. $\\hat\\beta_2  +  \\hat\\beta_5 \\times \\text{Female}_i$\n4. $\\hat\\beta_3 \\times \\text{Age}_i + \\hat\\beta_5 \\times \\text{Female}_i$\n\n## Plotting Interactions with Continuous Variables {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 row containing missing values (`geom_line()`).\n```\n:::\n\n::: {.cell-output-display}\n![](08-regression_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=2100}\n:::\n:::\n\n\n## Plotting Interactions with Continuous Variables \n\n\n::: {.cell layout-ncol=\"2\" layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 row containing missing values (`geom_line()`).\n```\n:::\n\n::: {.cell-output-display}\n![](08-regression_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' width=2100}\n:::\n\n::: {.cell-output-display}\n![](08-regression_files/figure-html/unnamed-chunk-14-2.png){fig-align='center' width=2100}\n:::\n:::\n\n\n## Plotting Interactions with Continuous Variables II\n\n\n::: {.cell layout-ncol=\"2\" layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-regression_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=2100}\n:::\n\n::: {.cell-output-display}\n![](08-regression_files/figure-html/unnamed-chunk-15-2.png){fig-align='center' width=2100}\n:::\n:::\n\n\n\n# Appendix: Using Simulations for Interpretation \n\n## Approaches to Obtain Confidence Intervals {.smaller}\n\n- So far, we used stats to calculate confidence intervals: \n  - assumed sampling distributions are normal \n  - calculated point estimates and standard errors\n  - calculate confidence intervals from estimated SEs and critical values for $\\mathcal{N}(0, 1)$\n  \n- Another approach utilizes simulations:\n  - assumed sampling distributions are normal \n  - calculated point estimates and standard errors\n  - use these values to obtain sets of simulated coefficients\n  - use these simulated coefficients to make predictions \n\n## Draws from Simulated Sampling Distributions {.smaller}\n\nWe would use our coefficient estimates and uncertainty about them to calculate sampling distributions (our best guesses about them based on our data)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](08-regression_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=2100}\n:::\n:::\n\n\n\n## Calculating Expected Values {.smaller}\n\n$${ \\begin{array}{c}\n        \\tilde{\\beta}_0^1 \\times 1+\\tilde{\\beta}_1^1 \\times   \\text{Age}_i  +\\tilde{\\beta}_2^1 \\times \\text{Beauty}_i + \\tilde{\\beta}_3^1 \\times \\text{Age}_i \\times \\text{Beauty}_i &= \\tilde{y}^1\\\\\n \\tilde{\\beta}_0^2 \\times 1+\\tilde{\\beta}_1^2 \\times   \\text{Age}_i  +\\tilde{\\beta}_2^2 \\times \\text{Beauty}_i + \\tilde{\\beta}_3^2 \\times \\text{Age}_i \\times \\text{Beauty}_i &= \\tilde{y}^2\\\\\n  \\tilde{\\beta}_0^3 \\times 1+\\tilde{\\beta}_1^3 \\times   \\text{Age}_i  +\\tilde{\\beta}_2^3 \\times \\text{Beauty}_i + \\tilde{\\beta}_3^3 \\times \\text{Age}_i \\times \\text{Beauty}_i &= \\tilde{y}^3\\\\\n        \\dots \\\\\n        \\tilde{\\beta}_0^{1000} \\times 1+\\tilde{\\beta}_1^{1000} \\times \\text{Age}_i  +\\tilde{\\beta}_2^{1000} \\times \\text{Beauty}_i + \\tilde{\\beta}_3^{1000} \\times \\text{Age}_i \\times \\text{Beauty}_i &= \\tilde{y}^{1000}\\\\\n    \\end{array} }$$\n\n\n## Plotting Expected Values {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\nScale for fill is already present.\nAdding another scale for fill, which will replace the existing scale.\n```\n:::\n\n::: {.cell-output-display}\n![](08-regression_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=2100}\n:::\n:::\n\n\n## Evaluating the Effects with First Differences\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n```\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\nScale for fill is already present.\nAdding another scale for fill, which will replace the existing scale.\n```\n:::\n\n::: {.cell-output-display}\n![](08-regression_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=2100}\n:::\n:::\n\n\n\n\n\n## Using Simulations for Interpretation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(clarify)\nset.seed(2023)\nm1 <- lm(eval ~ beauty * female, data = evals)\n\n# get draws from multivariate normal distribution \nsims <- clarify::sim(m1)\n\n# obtain predictions based on specified values\nresults <- sim_setx(sims, \n                    x = list(female = 0:1,\n                             beauty = 1:10))\n\nplot(results) \n\nFD <- sim_setx(sims,\n               x = list(female = 0,\n                        beauty = 1:10)) -\n  sim_setx(sims,\n           x = list(female = 1,\n                    beauty = 1:10))\n\nplot(FD) +\n scale_color_viridis_d(end = 0.8) +\n  scale_fill_viridis_d(end = 0.8, alpha = 0.5) +\n  theme(legend.position = \"top\") +\n  scale_x_continuous(limits = c(1, 10), breaks = 1:10) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  # ylim(c(3, 5)) +\n  theme(panel.grid.minor = element_blank(),\n        plot.title.position = \"plot\") +\n  labs(y = \"Difference in Average Teaching Evaluation\",\n       subtitle = \"First Difference between Male and Female Instructors\")\n\nplot(FD) +\n scale_color_viridis_d(end = 0.8) +\n  scale_fill_viridis_d(end = 0.8, alpha = 0.5) +\n  theme(legend.position = \"top\") +\n  scale_x_continuous(limits = c(1, 10), breaks = 1:10) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  # ylim(c(3, 5)) +\n  theme(panel.grid.minor = element_blank(),\n        plot.title.position = \"plot\") +\n  labs(y = \"Difference in Average Teaching Evaluation\",\n       subtitle = \"First Difference between Male and Female Instructors\")\n```\n:::\n\n\n\n<!-- # Intro -->\n\n\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- countdown(minutes = 4, color_background = \"white\", left = 1) -->\n<!-- ``` -->\n\n\n\n<!-- ::: columns -->\n<!-- ::: {.column width=\"30%\"} -->\n\n<!-- ```{dot} -->\n<!-- //| echo: false -->\n<!-- //| fig-width: 3 -->\n<!-- //| fig-height: 3 -->\n<!-- //| out-width: 100% -->\n<!-- digraph D { -->\n<!--   node [shape=oval, fontname=\"AtkinsonHyperlegible-Regular\"]; -->\n<!--   edge [minlen = 1.2, arrowhead = vee, arrowsize=0.5]; -->\n<!--   a [label = \"Beauty Score\"]; -->\n<!--   b [label = \"Evaluations\"]; -->\n<!--   c [label = \"Female\"]; -->\n\n<!--   {rank=same a b}; -->\n<!--   {rank=sink c}; -->\n<!--   a->b; -->\n<!--   c->a; -->\n<!--   c->b; -->\n<!-- } -->\n<!-- ``` -->\n\n\n<!-- :::  -->\n<!-- ::: {.column width=\"70%\"} -->\n\n<!-- 1.  After specifying the DGP in a DAG and following our identification strategy, we can interpret the estimated coefficient for the effect of *Beauty Score* on *Evaluations* causally. -->\n\n<!-- 2.  After specifying the DGP in a DAG and following our identification strategy, we can interpret the estimated coefficient for the effect of *Female* on *Evaluations* causally. -->\n\n<!-- 3. On average, a 5-point increase in *Beauty Score* would be associated with 0.4-point increase in *Teaching Evaluations*, for both female and female instructors.  -->\n\n<!-- 4. The effect of *Female* on *Teaching Evaluations* would be represented through the change in the slope of the regression coefficient for *Beauty Score*.  -->\n\n<!-- 5. For $evals = \\beta_0 + \\beta_1 \\cdot Female$,  $\\beta_1$ would be the equal to difference-in-means estimator.  -->\n\n<!-- :::  -->\n<!-- :::  -->\n",
    "supporting": [
      "08-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../site_libs/countdown-0.4.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/countdown-0.4.0/countdown.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}